/**
 ******************************************************************************
 * @file    stm32h7xx_hal_conf.h
 * @brief   HAL configuration — generated from menuconfig (.config)
 *
 * AUTO-GENERATED by scripts/gen_stm32_hal_conf.py
 * DO NOT hand-edit module enables or clock values here.
 * Run  make menuconfig      to change settings interactively.
 * Run  make config-outputs  to regenerate this file.
 * Then rebuild with  make all.
 *
 * Original template: STMicroelectronics MCD Application Team
 * Adapted for FreeRTOS-OS Kconfig integration: Subhajit Roy
 ******************************************************************************
 */

#ifndef __STM32H7xx_HAL_CONF_H
#define __STM32H7xx_HAL_CONF_H

#ifdef __cplusplus
extern "C" {
#endif

/* Pull in every CONFIG_* symbol produced by "make config-outputs" */
#include "autoconf.h"


/* ##########################################################################
 * HAL Module Selection  —  generated from menuconfig
 * ########################################################################## */

#define HAL_MODULE_ENABLED   /* master HAL enable — always on */

/* Core */
#define HAL_CORTEX_MODULE_ENABLED
#define HAL_PWR_MODULE_ENABLED
#define HAL_RCC_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_EXTI_MODULE_ENABLED
#define HAL_FLASH_MODULE_ENABLED
#define HAL_DMA_MODULE_ENABLED
#define HAL_IWDG_MODULE_ENABLED

/* Communication */
#define HAL_UART_MODULE_ENABLED

/* Timer */
#define HAL_TIM_MODULE_ENABLED

/* Analog */
#define HAL_ADC_MODULE_ENABLED


/* ##########################################################################
 * Clock values  —  baked in from menuconfig integers
 * ########################################################################## */

#if !defined(HSE_VALUE)
  #define HSE_VALUE                    ((uint32_t)25000000U)
#endif

#if !defined(HSE_STARTUP_TIMEOUT)
  #define HSE_STARTUP_TIMEOUT          ((uint32_t)100U)
#endif

#if !defined(HSI_VALUE)
  #define HSI_VALUE                    ((uint32_t)64000000U)
#endif

#if !defined(LSI_VALUE)
  #define LSI_VALUE                    ((uint32_t)32000U)
#endif

#if !defined(LSE_VALUE)
  #define LSE_VALUE                    ((uint32_t)32768U)
#endif

#if !defined(LSE_STARTUP_TIMEOUT)
  #define LSE_STARTUP_TIMEOUT          ((uint32_t)5000U)
#endif

#if !defined(EXTERNAL_CLOCK_VALUE)
  #define EXTERNAL_CLOCK_VALUE         ((uint32_t)12288000U)
#endif

#if !defined(CSI_VALUE)
  #define CSI_VALUE                    ((uint32_t)4000000U)
#endif


/* ##########################################################################
 * System / board configuration
 * ########################################################################## */

#define VDD_VALUE                     ((uint32_t)3300U)
#define TICK_INT_PRIORITY             ((uint32_t)1U)
#define USE_RTOS                      0U   /* Must stay 0 — STM32 HAL rejects 1 */
#define PREFETCH_ENABLE               1U
#define INSTRUCTION_CACHE_ENABLE      1U
#define DATA_CACHE_ENABLE             1U

/* ##########################################################################
 * Register-callback switches  —  all off by default.
 * Enable per-peripheral if you need runtime-swappable callbacks.
 * ########################################################################## */

#define USE_HAL_ADC_REGISTER_CALLBACKS         0U
#define USE_HAL_CRYP_REGISTER_CALLBACKS        0U
#define USE_HAL_DAC_REGISTER_CALLBACKS         0U
#define USE_HAL_DCMI_REGISTER_CALLBACKS        0U
#define USE_HAL_DFSDM_REGISTER_CALLBACKS       0U
#define USE_HAL_DMA_REGISTER_CALLBACKS         0U
#define USE_HAL_DMA2D_REGISTER_CALLBACKS       0U
#define USE_HAL_DSI_REGISTER_CALLBACKS         0U
#define USE_HAL_ETH_REGISTER_CALLBACKS         0U
#define USE_HAL_FDCAN_REGISTER_CALLBACKS       0U
#define USE_HAL_HASH_REGISTER_CALLBACKS        0U
#define USE_HAL_HCD_REGISTER_CALLBACKS         0U
#define USE_HAL_I2C_REGISTER_CALLBACKS         0U
#define USE_HAL_I2S_REGISTER_CALLBACKS         0U
#define USE_HAL_IRDA_REGISTER_CALLBACKS        0U
#define USE_HAL_JPEG_REGISTER_CALLBACKS        0U
#define USE_HAL_LPTIM_REGISTER_CALLBACKS       0U
#define USE_HAL_LTDC_REGISTER_CALLBACKS        0U
#define USE_HAL_MDMA_REGISTER_CALLBACKS        0U
#define USE_HAL_MMC_REGISTER_CALLBACKS         0U
#define USE_HAL_NAND_REGISTER_CALLBACKS        0U
#define USE_HAL_NOR_REGISTER_CALLBACKS         0U
#define USE_HAL_OSPI_REGISTER_CALLBACKS        0U
#define USE_HAL_PCD_REGISTER_CALLBACKS         0U
#define USE_HAL_RNG_REGISTER_CALLBACKS         0U
#define USE_HAL_RTC_REGISTER_CALLBACKS         0U
#define USE_HAL_SAI_REGISTER_CALLBACKS         0U
#define USE_HAL_SD_REGISTER_CALLBACKS          0U
#define USE_HAL_SMARTCARD_REGISTER_CALLBACKS   0U
#define USE_HAL_SDRAM_REGISTER_CALLBACKS       0U
#define USE_HAL_SRAM_REGISTER_CALLBACKS        0U
#define USE_HAL_SMBUS_REGISTER_CALLBACKS       0U
#define USE_HAL_SPDIFRX_REGISTER_CALLBACKS     0U
#define USE_HAL_SPI_REGISTER_CALLBACKS         0U
#define USE_HAL_TIM_REGISTER_CALLBACKS         0U
#define USE_HAL_UART_REGISTER_CALLBACKS        0U
#define USE_HAL_USART_REGISTER_CALLBACKS       0U
#define USE_HAL_WWDG_REGISTER_CALLBACKS        0U

/* ##########################################################################
 * assert_param
 * ########################################################################## */

#ifdef USE_FULL_ASSERT
  #define assert_param(expr) \
      ((expr) ? (void)0U : assert_failed((uint8_t *)__FILE__, __LINE__))
  void assert_failed(uint8_t *file, uint32_t line);
#else
  #define assert_param(expr) ((void)0U)
#endif

/* ##########################################################################
 * SPI CRC feature
 * ########################################################################## */

#define USE_SPI_CRC    0U

/* ##########################################################################
 * HAL driver includes  —  only for modules enabled in menuconfig
 * ########################################################################## */

#include "stm32h7xx_hal_rcc.h"
#include "stm32h7xx_hal_gpio.h"
#include "stm32h7xx_hal_exti.h"
#include "stm32h7xx_hal_dma.h"
#include "stm32h7xx_hal_cortex.h"
#include "stm32h7xx_hal_adc.h"
#include "stm32h7xx_hal_flash.h"
#include "stm32h7xx_hal_iwdg.h"
#include "stm32h7xx_hal_pwr.h"
#include "stm32h7xx_hal_tim.h"
#include "stm32h7xx_hal_uart.h"


#include "device.h"

#ifdef __cplusplus
}
#endif

#endif /* __STM32H7xx_HAL_CONF_H */
