
obj-y += arch/devices/STM/stm32_f401_system.o
obj-y += arch/devices/STM/stm32_f401_startup.o


INCLUDES += -I$(CURDIR)/arch/arm/CMSIS_6



LINKER_SCRIPT += $(CURDIR)/arch/devices/STM/stm32_f401_D_FLASH.ld