/* AUTO-GENERATED - do not edit. Re-run: make config-outputs */
#ifndef __AUTOCONF_H__
#define __AUTOCONF_H__

#define CONFIG_CPU_ARCH "ARM-CM4"
#define CONFIG_DATA_CACHE_ENABLE 1
#define CONFIG_DEFAULT_DEBUG_EN 1
#define CONFIG_DRV_DEBUG_EN 1
#define CONFIG_EXTERNAL_CLOCK_VALUE 12288000
#define CONFIG_HAL_CORTEX_MODULE_ENABLED 1
#define CONFIG_HAL_GPIO_MODULE_ENABLED 1
#define CONFIG_HAL_PWR_MODULE_ENABLED 1
#define CONFIG_HAL_RCC_MODULE_ENABLED 1
#define CONFIG_HAL_USART_MODULE_ENABLED 1
#define CONFIG_HSE_STARTUP_TIMEOUT 100
#define CONFIG_HSE_VALUE 2500000
#define CONFIG_HSI_VALUE 16000000
#define CONFIG_INC_SERVICE_OS_SHELL_MGMT 1
#define CONFIG_INC_SERVICE_UART_MGMT 1
#define CONFIG_INSTRUCTION_CACHE_ENABLE 1
#define CONFIG_ITM_PRINT_BUFF_LENGTH 64
#define CONFIG_LSE_STARTUP_TIMEOUT 5000
#define CONFIG_LSE_VALUE 32768
#define CONFIG_LSI_VALUE 32000
#define CONFIG_NO_OF_IIC 0
#define CONFIG_NO_OF_UART 1
#define CONFIG_PIPE_UART_1_DRV_RX_SIZE 512
#define CONFIG_PIPE_UART_1_DRV_TX_SIZE 512
#define CONFIG_PREFETCH_ENABLE 1
#define CONFIG_RTOS_LIBRARY_LOWEST_IRQ_PRIORITY 15
#define CONFIG_RTOS_LIBRARY_MAX_SYSCALL_IRQ_PRIORITY 5
#define CONFIG_RTOS_MAX_PRIORITIES 56
#define CONFIG_RTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_RTOS_MINIMAL_STACK_SIZE 512
#define CONFIG_RTOS_QUEUE_REGISTRY_SIZE 8
#define CONFIG_RTOS_TICK_RATE_HZ 1000
#define CONFIG_RTOS_TIMER_QUEUE_LENGTH 10
#define CONFIG_RTOS_TIMER_TASK_PRIORITY 2
#define CONFIG_RTOS_TIMER_TASK_STACK_DEPTH 256
#define CONFIG_RTOS_TOTAL_HEAP_SIZE 80000
#define CONFIG_RTOS_USE_COUNTING_SEMAPHORES 1
#define CONFIG_RTOS_USE_MUTEXES 1
#define CONFIG_RTOS_USE_PREEMPTION 1
#define CONFIG_RTOS_USE_RECURSIVE_MUTEXES 1
#define CONFIG_RTOS_USE_TIMERS 1
#define CONFIG_RTOS_USE_TIME_SLICING 1
#define CONFIG_TARGET_MCU "STM32F411xE"
#define CONFIG_TICK_INT_PRIORITY 1
#define CONFIG_VDD_VALUE 3300

#endif /* __AUTOCONF_H__ */
