/* Auto-generated config header */
#ifndef __STM32F4xx_HAL_CONF_H
#define __STM32F4xx_HAL_CONF_H 



#define HAL_MODULE_ENABLED 




#define TARGET_MCU "STM32F411"
#define CPU_ARCH "ARM-CM4"
#define HAL_CORTEX_MODULE_ENABLED 1
#define HAL_PWR_MODULE_ENABLED 1
#define HAL_RCC_MODULE_ENABLED 1
#define HAL_GPIO_MODULE_ENABLED 1
#define HAL_EXTI_MODULE_ENABLED 1
#define HSE_VALUE "8000000U"
#define HSE_STARTUP_TIMEOUT "100U"
#define HSI_VALUE "16000000U"
#define LSI_VALUE "32000U"
#define LSE_VALUE "32768U"
#define LSE_STARTUP_TIMEOUT "5000U"
#define EXTERNAL_CLOCK_VALUE "12288000U"
#define HAL_UART_MODULE_ENABLED 1
#define HAL_CAN_MODULE_ENABLED 1
#define HAL_TIM_MODULE_ENABLED 1
#define HAL_CRYP_MODULE_ENABLED 1



#endif
