#!/usr/bin/env python3
"""
gen_active_debug.py  —  Auto-detect CONFIG_TARGET_MCU from autoconf.h and
generate build/active_debug.cfg (the OpenOCD wrapper used by VS Code launch.json).

Run from the FreeRTOS-OS/ directory (or pass --workspace):
    python3 scripts/gen_active_debug.py

Outputs (all in build/):
    build/active_debug.cfg   — OpenOCD config sourcing the correct MCU .cfg
    build/debug_env.json     — JSON properties (device, svd, cpu_freq, …)

Also creates:
    arch/debug_cfg/active_target.svd  — symlink to the MCU-specific SVD file
                                        (used by VS Code svdFile setting)
"""

import os
import sys
import re
import json
import argparse


# ── MCU → debug properties ────────────────────────────────────────────────────
# Add new MCU entries here as more families are supported.
# openocd_cfg: path relative to FreeRTOS-OS/  (workspace root when opened there)
# svd:         path relative to FreeRTOS-OS/
MCU_DEBUG_MAP = {
    "STM32F411xE": {
        "openocd_cfg": "arch/debug_cfg/stm32_f411xx_debug.cfg",
        "svd":         "arch/debug_cfg/STM32F411.svd",
        "device":      "STM32F411VE",
        "cpu_freq":    100_000_000,
        "cpu_core":    "cortex-m4",
        "fpu":         "fpv4-sp-d16",
        "swo_freq":    2_000_000,
    },
    "STM32F401xE": {
        "openocd_cfg": "arch/debug_cfg/stm32_f401xx_debug.cfg",
        "svd":         "arch/debug_cfg/STM32F401.svd",
        "device":      "STM32F401xE",
        "cpu_freq":    84_000_000,
        "cpu_core":    "cortex-m4",
        "fpu":         "fpv4-sp-d16",
        "swo_freq":    2_000_000,
    },
}

AUTOCONF_H  = "config/autoconf.h"
BUILD_DIR   = "build"
OUTPUT_CFG  = os.path.join(BUILD_DIR, "active_debug.cfg")
OUTPUT_ENV  = os.path.join(BUILD_DIR, "debug_env.json")
SVD_LINK    = os.path.join("arch", "debug_cfg", "active_target.svd")


# ── Helpers ───────────────────────────────────────────────────────────────────

def read_target_mcu(autoconf_path: str):
    """Return the CONFIG_TARGET_MCU string value from autoconf.h, or None."""
    pat = re.compile(r'^\s*#define\s+CONFIG_TARGET_MCU\s+"([^"]+)"')
    try:
        with open(autoconf_path) as fh:
            for line in fh:
                m = pat.match(line)
                if m:
                    return m.group(1)
    except FileNotFoundError:
        pass
    return None


def make_active_svd_link(svd_rel: str):
    """Create/update arch/debug_cfg/active_target.svd symlink."""
    svd_abs = os.path.abspath(svd_rel)
    link    = os.path.abspath(SVD_LINK)
    if not os.path.exists(svd_abs):
        print(f"[detect-target] SVD not found: {svd_abs}")
        print( "               Run the 'install-debug-tools' VS Code task to download it.")
        return
    if os.path.lexists(link):
        os.remove(link)
    # Use a relative symlink so it survives directory moves
    os.symlink(os.path.basename(svd_abs), link)
    print(f"[detect-target] SVD symlink : {link} → {os.path.basename(svd_abs)}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Detect CONFIG_TARGET_MCU and write build/active_debug.cfg")
    parser.add_argument("--autoconf", default=AUTOCONF_H,
                        help=f"Path to autoconf.h  (default: {AUTOCONF_H})")
    args = parser.parse_args()

    # ── 1. Read MCU from autoconf.h ───────────────────────────────────────────
    mcu = read_target_mcu(args.autoconf)
    if not mcu:
        print(f"ERROR: CONFIG_TARGET_MCU not found in '{args.autoconf}'", file=sys.stderr)
        print( "       Run 'make config-outputs' or 'make menuconfig' first.", file=sys.stderr)
        sys.exit(1)

    info = MCU_DEBUG_MAP.get(mcu)
    if not info:
        supported = ", ".join(MCU_DEBUG_MAP.keys())
        print(f"ERROR: MCU '{mcu}' not in MCU_DEBUG_MAP.", file=sys.stderr)
        print(f"       Supported: {supported}", file=sys.stderr)
        print( "       Add an entry to scripts/gen_active_debug.py to support it.", file=sys.stderr)
        sys.exit(1)

    os.makedirs(BUILD_DIR, exist_ok=True)

    # ── 2. Resolve absolute path for the OpenOCD cfg ──────────────────────────
    # Cortex-Debug launches OpenOCD with cwd = ${workspaceFolder} (FreeRTOS-OS/).
    # We use absolute paths so the generated file works on any machine regardless
    # of how OpenOCD resolves its working directory.
    workspace      = os.path.abspath(".")
    openocd_abs    = os.path.join(workspace, info["openocd_cfg"])

    if not os.path.exists(openocd_abs):
        print(f"WARNING: OpenOCD cfg not found: {openocd_abs}", file=sys.stderr)

    # ── 3. Write build/active_debug.cfg ──────────────────────────────────────
    with open(OUTPUT_CFG, "w") as fh:
        fh.write("# ── Auto-generated by scripts/gen_active_debug.py — do not edit ──────────\n")
        fh.write(f"# TARGET_MCU  : {mcu}\n")
        fh.write(f"# Generated   : {workspace}\n")
        fh.write("#\n")
        fh.write("# This file is regenerated every time the 'detect-target' VS Code task runs\n")
        fh.write("# (preLaunchTask for all debug/flash launch configurations).\n")
        fh.write("# ─────────────────────────────────────────────────────────────────────────\n")
        fh.write(f"source {{{openocd_abs}}}\n")

    # ── 4. Write build/debug_env.json ────────────────────────────────────────
    env = {
        "target_mcu":  mcu,
        "device":      info["device"],
        "svd_file":    os.path.join(workspace, info["svd"]),
        "cpu_freq":    info["cpu_freq"],
        "cpu_core":    info["cpu_core"],
        "fpu":         info["fpu"],
        "swo_freq":    info["swo_freq"],
        "openocd_cfg": openocd_abs,
        "workspace":   workspace,
    }
    with open(OUTPUT_ENV, "w") as fh:
        json.dump(env, fh, indent=2)
        fh.write("\n")

    # ── 5. Create active_target.svd symlink ──────────────────────────────────
    make_active_svd_link(info["svd"])

    # ── 6. Print summary ─────────────────────────────────────────────────────
    print(f"[detect-target] MCU        : {mcu}")
    print(f"[detect-target] Device     : {info['device']}")
    print(f"[detect-target] OpenOCD    : {info['openocd_cfg']}")
    print(f"[detect-target] CPU freq   : {info['cpu_freq'] // 1_000_000} MHz")
    print(f"[detect-target] Written    : {OUTPUT_CFG}")
    print(f"[detect-target] Env JSON   : {OUTPUT_ENV}")


if __name__ == "__main__":
    main()
