# File:        ipc/Makefile
# Module:      ipc
# Info:        IPC subsystem: message-queues, ring-buffers, global queue ID tables
#
# This file is part of FreeRTOS-OS Project.

include autoconf.mk

obj-y += ipc/global_var.o
obj-y += ipc/mqueue.o
obj-y += ipc/ringbuffer.o
