FreeRTOS-OS: drv_dma.h File Reference
drv_dma.h File Reference
#include <def_std.h>
#include <def_err.h>
#include <mm/list.h>
Classes
struct dma_async_tx_descriptor
struct dma_chan
struct dma_chan_hal_ops_t
struct dma_device
struct dma_slave_config_t
Macros
#define DMA_DESC_POOL_SIZE 4 /* descriptor pool depth per channel */
#define DMA_MAX_CHANNELS 8 /* streams per controller (STM32F4) */
#define DMA_MAX_DEVICES 2 /* DMA1 + DMA2 */
#define DMA_MIN_COOKIE 1
Typedefs
typedef struct dma_async_tx_descriptor dma_async_tx_descriptor_t
typedef struct dma_chan dma_chan_t
typedef int32_t dma_cookie_t
typedef struct dma_device dma_device_t
Enumerations
enum dma_addr_adj_t { DMA_ADDR_INCREMENT = 0 , DMA_ADDR_FIXED }
enum dma_chan_state_t { DMA_CHAN_IDLE = 0 , DMA_CHAN_ALLOCATED , DMA_CHAN_BUSY }
enum dma_desc_state_t {
DMA_DESC_FREE = 0 , DMA_DESC_PREPARED , DMA_DESC_SUBMITTED , DMA_DESC_IN_PROGRESS ,
DMA_DESC_COMPLETE , DMA_DESC_ERROR
}
enum dma_slave_buswidth_t { DMA_SLAVE_BUSWIDTH_UNDEFINED = 0 , DMA_SLAVE_BUSWIDTH_1_BYTE = 1 , DMA_SLAVE_BUSWIDTH_2_BYTES = 2 , DMA_SLAVE_BUSWIDTH_4_BYTES = 4 }
enum dma_transfer_direction_t { DMA_MEM_TO_MEM = 0 , DMA_MEM_TO_DEV , DMA_DEV_TO_MEM , DMA_DEV_TO_DEV }
enum dma_xfer_mode_t { DMA_XFER_NORMAL = 0 , DMA_XFER_CYCLIC }
Functions
void dma_async_issue_pending (dma_chan_t *chan)
void dma_complete_callback (dma_chan_t *chan)
void dma_error_callback (dma_chan_t *chan)
int32_t dma_register_device (dma_device_t *dev)
void dma_release_chan (dma_chan_t *chan)
dma_chan_t * dma_request_chan (const char *dev_name, uint8_t chan_id)
uint32_t dmaengine_get_residue (dma_chan_t *chan)
int32_t dmaengine_pause (dma_chan_t *chan)
dma_async_tx_descriptor_t * dmaengine_prep_dma_cyclic (dma_chan_t *chan, uint32_t buf_addr, uint32_t buf_len, uint32_t period_len, dma_transfer_direction_t dir)
dma_async_tx_descriptor_t * dmaengine_prep_dma_memcpy (dma_chan_t *chan, uint32_t dst, uint32_t src, uint32_t len)
dma_async_tx_descriptor_t * dmaengine_prep_slave_single (dma_chan_t *chan, uint32_t buf, uint32_t len, dma_transfer_direction_t dir)
int32_t dmaengine_resume (dma_chan_t *chan)
int32_t dmaengine_slave_config (dma_chan_t *chan, const dma_slave_config_t *cfg)
dma_cookie_t dmaengine_submit (dma_async_tx_descriptor_t *desc)
int32_t dmaengine_terminate_all (dma_chan_t *chan)
Macro Definition Documentation
DMA_DESC_POOL_SIZE
#define DMA_DESC_POOL_SIZE 4 /* descriptor pool depth per channel */
Definition at line 55 of file drv_dma.h.
DMA_MAX_CHANNELS
#define DMA_MAX_CHANNELS 8 /* streams per controller (STM32F4) */
Definition at line 54 of file drv_dma.h.
DMA_MAX_DEVICES
#define DMA_MAX_DEVICES 2 /* DMA1 + DMA2 */
Definition at line 53 of file drv_dma.h.
DMA_MIN_COOKIE
#define DMA_MIN_COOKIE 1
Definition at line 111 of file drv_dma.h.
Typedef Documentation
dma_async_tx_descriptor_t
typedef struct dma_async_tx_descriptor dma_async_tx_descriptor_t
dma_chan_t
typedef struct dma_chan dma_chan_t
Definition at line 115 of file drv_dma.h.
dma_cookie_t
typedef int32_t dma_cookie_t
Definition at line 110 of file drv_dma.h.
dma_device_t
typedef struct dma_device dma_device_t
Definition at line 116 of file drv_dma.h.
Enumeration Type Documentation
dma_addr_adj_t
enum dma_addr_adj_t
Enumerator
DMA_ADDR_INCREMENT
DMA_ADDR_FIXED
Definition at line 77 of file drv_dma.h.
             {
    DMA_ADDR_INCREMENT = 0,  /* advance pointer — use for memory buffers    */
    DMA_ADDR_FIXED,          /* keep pointer constant — use for peripheral DR */
} dma_addr_adj_t;
dma_chan_state_t
enum dma_chan_state_t
Enumerator
DMA_CHAN_IDLE
DMA_CHAN_ALLOCATED
DMA_CHAN_BUSY
Definition at line 102 of file drv_dma.h.
             {
    DMA_CHAN_IDLE = 0,   /* not allocated      */
    DMA_CHAN_ALLOCATED,  /* owned, idle        */
    DMA_CHAN_BUSY,       /* transfer in flight */
} dma_chan_state_t;
dma_desc_state_t
enum dma_desc_state_t
Enumerator
DMA_DESC_FREE
DMA_DESC_PREPARED
DMA_DESC_SUBMITTED
DMA_DESC_IN_PROGRESS
DMA_DESC_COMPLETE
DMA_DESC_ERROR
Definition at line 91 of file drv_dma.h.
             {
    DMA_DESC_FREE = 0,
    DMA_DESC_PREPARED,
    DMA_DESC_SUBMITTED,
    DMA_DESC_IN_PROGRESS,
    DMA_DESC_COMPLETE,
    DMA_DESC_ERROR,
} dma_desc_state_t;
dma_slave_buswidth_t
enum dma_slave_buswidth_t
Enumerator
DMA_SLAVE_BUSWIDTH_UNDEFINED
DMA_SLAVE_BUSWIDTH_1_BYTE
DMA_SLAVE_BUSWIDTH_2_BYTES
DMA_SLAVE_BUSWIDTH_4_BYTES
Definition at line 68 of file drv_dma.h.
             {
    DMA_SLAVE_BUSWIDTH_UNDEFINED = 0,
    DMA_SLAVE_BUSWIDTH_1_BYTE    = 1,
    DMA_SLAVE_BUSWIDTH_2_BYTES   = 2,
    DMA_SLAVE_BUSWIDTH_4_BYTES   = 4,
} dma_slave_buswidth_t;
dma_transfer_direction_t
enum dma_transfer_direction_t
Enumerator
DMA_MEM_TO_MEM
DMA_MEM_TO_DEV
DMA_DEV_TO_MEM
DMA_DEV_TO_DEV
Definition at line 59 of file drv_dma.h.
             {
    DMA_MEM_TO_MEM = 0,
    DMA_MEM_TO_DEV,
    DMA_DEV_TO_MEM,
    DMA_DEV_TO_DEV,
} dma_transfer_direction_t;
dma_xfer_mode_t
enum dma_xfer_mode_t
Enumerator
DMA_XFER_NORMAL
DMA_XFER_CYCLIC
Definition at line 84 of file drv_dma.h.
             {
    DMA_XFER_NORMAL = 0,  /* single-shot; stream stops after len bytes */
    DMA_XFER_CYCLIC,      /* auto-reload; callback fires every period_len */
} dma_xfer_mode_t;
Function Documentation
dma_async_issue_pending()
void dma_async_issue_pending (dma_chan_t * chan)
Definition at line 224 of file drv_dma.c.
{
    if (!chan || chan->state == DMA_CHAN_IDLE)
        return;
    if (chan->active_desc)
        return; /* already running — will auto-chain on complete */
    if (list_empty(&chan->pending))
        return;
    dma_async_tx_descriptor_t *desc = list_first_entry(
        &chan->pending, dma_async_tx_descriptor_t, node);
    list_delete(&desc->node);
    desc->state      = DMA_DESC_IN_PROGRESS;
    chan->active_desc = desc;
    chan->state       = DMA_CHAN_BUSY;
    if (chan->device->ops->start)
        chan->device->ops->start(chan, desc);
}
References dma_chan::active_desc, dma_chan::device, DMA_CHAN_BUSY, DMA_CHAN_IDLE, DMA_DESC_IN_PROGRESS, list_delete(), list_empty, list_first_entry, dma_async_tx_descriptor::node, dma_device::ops, dma_chan::pending, dma_chan_hal_ops_t::start, dma_async_tx_descriptor::state, and dma_chan::state.
dma_complete_callback()
void dma_complete_callback (dma_chan_t * chan)
Definition at line 300 of file drv_dma.c.
{
    if (!chan)
        return;
    dma_async_tx_descriptor_t *desc = chan->active_desc;
    if (!desc)
        return;
    chan->completed_cookie = desc->cookie;
    if (desc->callback)
        desc->callback(desc->callback_param);
    /* Cyclic: keep descriptor active; HAL re-arms automatically */
    if (desc->mode == DMA_XFER_CYCLIC)
    {
        desc->state = DMA_DESC_IN_PROGRESS;
        return;
    }
    desc->state      = DMA_DESC_COMPLETE;
    _desc_free(desc);
    chan->active_desc = NULL;
    chan->state       = DMA_CHAN_ALLOCATED;
    /* Auto-start next queued descriptor */
    dma_async_issue_pending(chan);
}
References _desc_free(), dma_chan::active_desc, dma_async_tx_descriptor::callback, dma_async_tx_descriptor::callback_param, dma_chan::completed_cookie, dma_async_tx_descriptor::cookie, dma_async_issue_pending(), DMA_CHAN_ALLOCATED, DMA_DESC_COMPLETE, DMA_DESC_IN_PROGRESS, DMA_XFER_CYCLIC, dma_async_tx_descriptor::mode, dma_async_tx_descriptor::state, and dma_chan::state.
dma_error_callback()
void dma_error_callback (dma_chan_t * chan)
Definition at line 330 of file drv_dma.c.
{
    if (!chan)
        return;
    dma_async_tx_descriptor_t *desc = chan->active_desc;
    if (!desc)
        return;
    if (desc->error_callback)
        desc->error_callback(desc->callback_param);
    desc->state      = DMA_DESC_ERROR;
    _desc_free(desc);
    chan->active_desc = NULL;
    chan->state       = DMA_CHAN_ALLOCATED;
}
References _desc_free(), dma_chan::active_desc, dma_async_tx_descriptor::callback_param, DMA_CHAN_ALLOCATED, DMA_DESC_ERROR, dma_async_tx_descriptor::error_callback, dma_async_tx_descriptor::state, and dma_chan::state.
dma_register_device()
int32_t dma_register_device (dma_device_t * dev)
Definition at line 62 of file drv_dma.c.
{
    if (!dev || !dev->ops || _dev_count >= DMA_MAX_DEVICES)
        return OS_ERR_OP;
    for (uint8_t i = 0; i < dev->nr_channels && i < DMA_MAX_CHANNELS; i++)
    {
        dma_chan_t *ch   = &dev->channels[i];
        ch->device       = dev;
        ch->chan_id      = i;
        ch->state        = DMA_CHAN_IDLE;
        ch->cookie       = 0;
        ch->completed_cookie = 0;
        ch->active_desc  = NULL;
        INIT_LIST_NODE(&ch->pending);
        for (int j = 0; j < DMA_DESC_POOL_SIZE; j++)
            ch->desc_pool[j].state = DMA_DESC_FREE;
        if (dev->ops->chan_init)
            dev->ops->chan_init(ch);
    }
    list_add_tail(&dev->list, &_dev_list);
    _dev_count++;
    return OS_ERR_NONE;
}
References _dev_count, _dev_list, dma_chan::active_desc, dma_chan::chan_id, dma_chan_hal_ops_t::chan_init, dma_device::channels, dma_chan::completed_cookie, dma_chan::cookie, dma_chan::desc_pool, dma_chan::device, DMA_CHAN_IDLE, DMA_DESC_FREE, DMA_DESC_POOL_SIZE, DMA_MAX_CHANNELS, DMA_MAX_DEVICES, INIT_LIST_NODE, dma_device::list, list_add_tail(), dma_device::nr_channels, dma_device::ops, OS_ERR_NONE, OS_ERR_OP, dma_chan::pending, dma_async_tx_descriptor::state, and dma_chan::state.
dma_release_chan()
void dma_release_chan (dma_chan_t * chan)
Definition at line 117 of file drv_dma.c.
{
    if (!chan)
        return;
    dmaengine_terminate_all(chan);
    chan->state = DMA_CHAN_IDLE;
}
References DMA_CHAN_IDLE, dmaengine_terminate_all(), and dma_chan::state.
dma_request_chan()
dma_chan_t * dma_request_chan (const char * dev_name, uint8_t chan_id)
Definition at line 92 of file drv_dma.c.
{
    if (!dev_name)
        return NULL;
    dma_device_t *dev;
    list_for_each_entry(dev, &_dev_list, list)
    {
        if (strcmp(dev->name, dev_name) != 0)
            continue;
        if (chan_id >= dev->nr_channels)
            return NULL;
        dma_chan_t *ch = &dev->channels[chan_id];
        if (ch->state == DMA_CHAN_IDLE)
        {
            ch->state = DMA_CHAN_ALLOCATED;
            return ch;
        }
    }
    return NULL;
}
References _dev_list, dma_device::channels, DMA_CHAN_ALLOCATED, DMA_CHAN_IDLE, list_for_each_entry, dma_device::name, dma_device::nr_channels, and dma_chan::state.
dmaengine_get_residue()
uint32_t dmaengine_get_residue (dma_chan_t * chan)
Definition at line 291 of file drv_dma.c.
{
    if (!chan || !chan->device->ops->get_residue)
        return 0;
    return chan->device->ops->get_residue(chan);
}
References dma_chan::device, dma_chan_hal_ops_t::get_residue, and dma_device::ops.
dmaengine_pause()
int32_t dmaengine_pause (dma_chan_t * chan)
Definition at line 277 of file drv_dma.c.
{
    if (!chan || !chan->device->ops->pause)
        return OS_ERR_OP;
    return chan->device->ops->pause(chan);
}
References dma_chan::device, dma_device::ops, OS_ERR_OP, and dma_chan_hal_ops_t::pause.
dmaengine_prep_dma_cyclic()
dma_async_tx_descriptor_t * dmaengine_prep_dma_cyclic (dma_chan_t * chan, uint32_t buf_addr, uint32_t buf_len, uint32_t period_len, dma_transfer_direction_t dir)
Definition at line 188 of file drv_dma.c.
{
    if (!chan || chan->state == DMA_CHAN_IDLE || buf_len == 0 || period_len == 0)
        return NULL;
    dma_async_tx_descriptor_t *desc = _desc_alloc(chan);
    if (!desc)
        return NULL;
    desc->direction  = dir;
    desc->mode       = DMA_XFER_CYCLIC;
    desc->len        = buf_len;
    desc->period_len = period_len;
    desc->src = (dir == DMA_DEV_TO_MEM) ? chan->slave_cfg.src_addr : buf_addr;
    desc->dst = (dir == DMA_MEM_TO_DEV) ? chan->slave_cfg.dst_addr : buf_addr;
    return desc;
}
References _desc_alloc(), dma_async_tx_descriptor::direction, DMA_CHAN_IDLE, DMA_DEV_TO_MEM, DMA_MEM_TO_DEV, DMA_XFER_CYCLIC, dma_async_tx_descriptor::dst, dma_slave_config_t::dst_addr, dma_async_tx_descriptor::len, dma_async_tx_descriptor::mode, dma_async_tx_descriptor::period_len, dma_chan::slave_cfg, dma_async_tx_descriptor::src, dma_slave_config_t::src_addr, and dma_chan::state.
dmaengine_prep_dma_memcpy()
dma_async_tx_descriptor_t * dmaengine_prep_dma_memcpy (dma_chan_t * chan, uint32_t dst, uint32_t src, uint32_t len)
Definition at line 170 of file drv_dma.c.
{
    if (!chan || chan->state == DMA_CHAN_IDLE || len == 0)
        return NULL;
    dma_async_tx_descriptor_t *desc = _desc_alloc(chan);
    if (!desc)
        return NULL;
    desc->direction = DMA_MEM_TO_MEM;
    desc->mode      = DMA_XFER_NORMAL;
    desc->src       = src;
    desc->dst       = dst;
    desc->len       = len;
    return desc;
}
References _desc_alloc(), dma_async_tx_descriptor::direction, DMA_CHAN_IDLE, DMA_MEM_TO_MEM, DMA_XFER_NORMAL, dma_async_tx_descriptor::dst, dma_async_tx_descriptor::len, dma_async_tx_descriptor::mode, dma_async_tx_descriptor::src, and dma_chan::state.
dmaengine_prep_slave_single()
dma_async_tx_descriptor_t * dmaengine_prep_slave_single (dma_chan_t * chan, uint32_t buf, uint32_t len, dma_transfer_direction_t dir)
Definition at line 142 of file drv_dma.c.
{
    if (!chan || chan->state == DMA_CHAN_IDLE || len == 0)
        return NULL;
    dma_async_tx_descriptor_t *desc = _desc_alloc(chan);
    if (!desc)
        return NULL;
    desc->direction = dir;
    desc->mode      = DMA_XFER_NORMAL;
    desc->len       = len;
    if (dir == DMA_MEM_TO_DEV)
    {
        desc->src = buf;
        desc->dst = chan->slave_cfg.dst_addr;
    }
    else /* DEV_TO_MEM */
    {
        desc->src = chan->slave_cfg.src_addr;
        desc->dst = buf;
    }
    return desc;
}
References _desc_alloc(), dma_async_tx_descriptor::direction, DMA_CHAN_IDLE, DMA_MEM_TO_DEV, DMA_XFER_NORMAL, dma_async_tx_descriptor::dst, dma_slave_config_t::dst_addr, dma_async_tx_descriptor::len, dma_async_tx_descriptor::mode, dma_chan::slave_cfg, dma_async_tx_descriptor::src, dma_slave_config_t::src_addr, and dma_chan::state.
dmaengine_resume()
int32_t dmaengine_resume (dma_chan_t * chan)
Definition at line 284 of file drv_dma.c.
{
    if (!chan || !chan->device->ops->resume)
        return OS_ERR_OP;
    return chan->device->ops->resume(chan);
}
References dma_chan::device, dma_device::ops, OS_ERR_OP, and dma_chan_hal_ops_t::resume.
dmaengine_slave_config()
int32_t dmaengine_slave_config (dma_chan_t * chan, const dma_slave_config_t * cfg)
Definition at line 127 of file drv_dma.c.
{
    if (!chan || !cfg || chan->state == DMA_CHAN_IDLE)
        return OS_ERR_OP;
    chan->slave_cfg = *cfg;
    if (chan->device->ops->slave_config)
        return chan->device->ops->slave_config(chan, cfg);
    return OS_ERR_NONE;
}
References dma_chan::device, DMA_CHAN_IDLE, dma_device::ops, OS_ERR_NONE, OS_ERR_OP, dma_chan::slave_cfg, dma_chan_hal_ops_t::slave_config, and dma_chan::state.
dmaengine_submit()
dma_cookie_t dmaengine_submit (dma_async_tx_descriptor_t * desc)
Definition at line 210 of file drv_dma.c.
{
    if (!desc || !desc->chan)
        return (dma_cookie_t)(-OS_ERR_OP);
    desc->cookie = _cookie_alloc();
    desc->state  = DMA_DESC_SUBMITTED;
    list_add_tail(&desc->node, &desc->chan->pending);
    desc->chan->cookie = desc->cookie;
    return desc->cookie;
}
References _cookie_alloc(), dma_async_tx_descriptor::chan, dma_async_tx_descriptor::cookie, dma_chan::cookie, DMA_DESC_SUBMITTED, list_add_tail(), dma_async_tx_descriptor::node, OS_ERR_OP, dma_chan::pending, and dma_async_tx_descriptor::state.
dmaengine_terminate_all()
int32_t dmaengine_terminate_all (dma_chan_t * chan)
Definition at line 248 of file drv_dma.c.
{
    if (!chan)
        return OS_ERR_OP;
    int32_t ret = OS_ERR_NONE;
    if (chan->device->ops->terminate_all)
        ret = chan->device->ops->terminate_all(chan);
    while (!list_empty(&chan->pending))
    {
        dma_async_tx_descriptor_t *desc = list_first_entry(
            &chan->pending, dma_async_tx_descriptor_t, node);
        list_delete(&desc->node);
        _desc_free(desc);
    }
    if (chan->active_desc)
    {
        _desc_free(chan->active_desc);
        chan->active_desc = NULL;
    }
    if (chan->state == DMA_CHAN_BUSY)
        chan->state = DMA_CHAN_ALLOCATED;
    return ret;
}
References _desc_free(), dma_chan::active_desc, dma_chan::device, DMA_CHAN_ALLOCATED, DMA_CHAN_BUSY, list_delete(), list_empty, list_first_entry, dma_async_tx_descriptor::node, dma_device::ops, OS_ERR_NONE, OS_ERR_OP, dma_chan::pending, dma_chan::state, and dma_chan_hal_ops_t::terminate_all.