FreeRTOS-OS: drv_rcc.c File Reference
drv_rcc.c File Reference
#include <stddef.h>
#include <drivers/drv_rcc.h>
#include <board/mcu_config.h>
#include <def_err.h>
Functions
void _hal_rcc_stm32_register (const drv_rcc_hal_ops_t **ops_out)
Register RCC HAL backend.
int32_t drv_rcc_clock_init (void)
uint32_t drv_rcc_get_apb1_hz (void)
uint32_t drv_rcc_get_apb2_hz (void)
uint32_t drv_rcc_get_sysclk_hz (void)
void drv_rcc_gpio_clk_en (void *port)
void drv_rcc_periph_clk_en (drv_rcc_periph_t periph)
int32_t drv_rcc_register (const drv_rcc_hal_ops_t *ops)
void hal_rcc_stm32_gpio_clk_en (void *port)
Enable GPIO port clock.
void hal_rcc_stm32_periph_clk_en (drv_rcc_periph_t periph)
Enable peripheral clock.
Variables
static const drv_rcc_hal_ops_t * _ops
Function Documentation
_hal_rcc_stm32_register()
void _hal_rcc_stm32_register (const drv_rcc_hal_ops_t ** ops_out)
Register RCC HAL backend.
Parameters
ops_out Output pointer to HAL ops table
Definition at line 292 of file hal_rcc_stm32.c.
{
    *ops_out = &_stm32_rcc_ops;
}
drv_rcc_clock_init()
int32_t drv_rcc_clock_init (void)
Definition at line 37 of file drv_rcc.c.
{
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
    _hal_rcc_stm32_register(&_ops);
#endif
    if (_ops == NULL || _ops->clock_init == NULL)
        return OS_ERR_OP;
    return _ops->clock_init();
}
References _hal_rcc_stm32_register(), _ops, drv_rcc_hal_ops_t::clock_init, and OS_ERR_OP.
drv_rcc_get_apb1_hz()
uint32_t drv_rcc_get_apb1_hz (void)
Definition at line 56 of file drv_rcc.c.
{
    if (_ops && _ops->get_apb1_hz)
        return _ops->get_apb1_hz();
    return 0U;
}
References _ops, and drv_rcc_hal_ops_t::get_apb1_hz.
drv_rcc_get_apb2_hz()
uint32_t drv_rcc_get_apb2_hz (void)
Definition at line 63 of file drv_rcc.c.
{
    if (_ops && _ops->get_apb2_hz)
        return _ops->get_apb2_hz();
    return 0U;
}
References _ops, and drv_rcc_hal_ops_t::get_apb2_hz.
drv_rcc_get_sysclk_hz()
uint32_t drv_rcc_get_sysclk_hz (void)
Definition at line 49 of file drv_rcc.c.
{
    if (_ops && _ops->get_sysclk_hz)
        return _ops->get_sysclk_hz();
    return 0U;
}
References _ops, and drv_rcc_hal_ops_t::get_sysclk_hz.
drv_rcc_gpio_clk_en()
void drv_rcc_gpio_clk_en (void * port)
Definition at line 77 of file drv_rcc.c.
{
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
    hal_rcc_stm32_gpio_clk_en(port);
#endif
}
References hal_rcc_stm32_gpio_clk_en().
drv_rcc_periph_clk_en()
void drv_rcc_periph_clk_en (drv_rcc_periph_t periph)
Definition at line 70 of file drv_rcc.c.
{
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
    hal_rcc_stm32_periph_clk_en(periph);
#endif
}
References hal_rcc_stm32_periph_clk_en().
drv_rcc_register()
int32_t drv_rcc_register (const drv_rcc_hal_ops_t * ops)
Definition at line 27 of file drv_rcc.c.
{
    if (ops == NULL)
        return OS_ERR_OP;
    _ops = ops;
    return OS_ERR_NONE;
}
References _ops, OS_ERR_NONE, and OS_ERR_OP.
hal_rcc_stm32_gpio_clk_en()
void hal_rcc_stm32_gpio_clk_en (void * port)
Enable GPIO port clock.
Parameters
port GPIO port base address (GPIOA, GPIOB, ...)
Definition at line 266 of file hal_rcc_stm32.c.
{
    if      (port == GPIOA) { __HAL_RCC_GPIOA_CLK_ENABLE(); }
    else if (port == GPIOB) { __HAL_RCC_GPIOB_CLK_ENABLE(); }
    else if (port == GPIOC) { __HAL_RCC_GPIOC_CLK_ENABLE(); }
}
hal_rcc_stm32_periph_clk_en()
void hal_rcc_stm32_periph_clk_en (drv_rcc_periph_t periph)
Enable peripheral clock.
Parameters
periph Peripheral identifier
Centralized control for all peripheral clock enables. Prevents direct HAL_RCC_* usage in upper layers.
Definition at line 246 of file hal_rcc_stm32.c.
{
    switch (periph)
    {
        case DRV_RCC_PERIPH_USART1: __HAL_RCC_USART1_CLK_ENABLE(); break;
        case DRV_RCC_PERIPH_USART2: __HAL_RCC_USART2_CLK_ENABLE(); break;
        case DRV_RCC_PERIPH_I2C1:   __HAL_RCC_I2C1_CLK_ENABLE();   break;
        case DRV_RCC_PERIPH_SPI1:   __HAL_RCC_SPI1_CLK_ENABLE();   break;
        case DRV_RCC_PERIPH_TIM1:   __HAL_RCC_TIM1_CLK_ENABLE();   break;
        case DRV_RCC_PERIPH_SYSCFG: __HAL_RCC_SYSCFG_CLK_ENABLE(); break;
        case DRV_RCC_PERIPH_PWR:    __HAL_RCC_PWR_CLK_ENABLE();    break;
        default: break;
    }
}
Variable Documentation
_ops
const drv_rcc_hal_ops_t* _ops static
Definition at line 25 of file drv_rcc.c.