FreeRTOS-OS: drv_rcc.h File Reference
drv_rcc.h File Reference
#include <stdint.h>
#include <def_err.h>
Classes
struct drv_rcc_hal_ops_t
Enumerations
enum drv_rcc_periph_t {
DRV_RCC_PERIPH_USART1 = 0 , DRV_RCC_PERIPH_USART2 , DRV_RCC_PERIPH_I2C1 , DRV_RCC_PERIPH_SPI1 ,
DRV_RCC_PERIPH_TIM1 , DRV_RCC_PERIPH_SYSCFG , DRV_RCC_PERIPH_PWR , DRV_RCC_PERIPH_GPIOA ,
DRV_RCC_PERIPH_GPIOB , DRV_RCC_PERIPH_GPIOC
}
Functions
int32_t drv_rcc_clock_init (void)
uint32_t drv_rcc_get_apb1_hz (void)
uint32_t drv_rcc_get_apb2_hz (void)
uint32_t drv_rcc_get_sysclk_hz (void)
void drv_rcc_gpio_clk_en (void *port)
void drv_rcc_periph_clk_en (drv_rcc_periph_t periph)
int32_t drv_rcc_register (const drv_rcc_hal_ops_t *ops)
Enumeration Type Documentation
drv_rcc_periph_t
enum drv_rcc_periph_t
Enumerator
DRV_RCC_PERIPH_USART1
DRV_RCC_PERIPH_USART2
DRV_RCC_PERIPH_I2C1
DRV_RCC_PERIPH_SPI1
DRV_RCC_PERIPH_TIM1
DRV_RCC_PERIPH_SYSCFG
DRV_RCC_PERIPH_PWR
DRV_RCC_PERIPH_GPIOA
DRV_RCC_PERIPH_GPIOB
DRV_RCC_PERIPH_GPIOC
Definition at line 28 of file drv_rcc.h.
             {
    DRV_RCC_PERIPH_USART1 = 0,
    DRV_RCC_PERIPH_USART2,
    DRV_RCC_PERIPH_I2C1,
    DRV_RCC_PERIPH_SPI1,
    DRV_RCC_PERIPH_TIM1,
    DRV_RCC_PERIPH_SYSCFG,
    DRV_RCC_PERIPH_PWR,
    DRV_RCC_PERIPH_GPIOA,
    DRV_RCC_PERIPH_GPIOB,
    DRV_RCC_PERIPH_GPIOC,
} drv_rcc_periph_t;
Function Documentation
drv_rcc_clock_init()
int32_t drv_rcc_clock_init (void)
Definition at line 37 of file drv_rcc.c.
{
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
    _hal_rcc_stm32_register(&_ops);
#endif
    if (_ops == NULL || _ops->clock_init == NULL)
        return OS_ERR_OP;
    return _ops->clock_init();
}
References _hal_rcc_stm32_register(), _ops, drv_rcc_hal_ops_t::clock_init, and OS_ERR_OP.
drv_rcc_get_apb1_hz()
uint32_t drv_rcc_get_apb1_hz (void)
Definition at line 56 of file drv_rcc.c.
{
    if (_ops && _ops->get_apb1_hz)
        return _ops->get_apb1_hz();
    return 0U;
}
References _ops, and drv_rcc_hal_ops_t::get_apb1_hz.
drv_rcc_get_apb2_hz()
uint32_t drv_rcc_get_apb2_hz (void)
Definition at line 63 of file drv_rcc.c.
{
    if (_ops && _ops->get_apb2_hz)
        return _ops->get_apb2_hz();
    return 0U;
}
References _ops, and drv_rcc_hal_ops_t::get_apb2_hz.
drv_rcc_get_sysclk_hz()
uint32_t drv_rcc_get_sysclk_hz (void)
Definition at line 49 of file drv_rcc.c.
{
    if (_ops && _ops->get_sysclk_hz)
        return _ops->get_sysclk_hz();
    return 0U;
}
References _ops, and drv_rcc_hal_ops_t::get_sysclk_hz.
drv_rcc_gpio_clk_en()
void drv_rcc_gpio_clk_en (void * port)
Definition at line 77 of file drv_rcc.c.
{
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
    hal_rcc_stm32_gpio_clk_en(port);
#endif
}
References hal_rcc_stm32_gpio_clk_en().
drv_rcc_periph_clk_en()
void drv_rcc_periph_clk_en (drv_rcc_periph_t periph)
Definition at line 70 of file drv_rcc.c.
{
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
    hal_rcc_stm32_periph_clk_en(periph);
#endif
}
References hal_rcc_stm32_periph_clk_en().
drv_rcc_register()
int32_t drv_rcc_register (const drv_rcc_hal_ops_t * ops)
Definition at line 27 of file drv_rcc.c.
{
    if (ops == NULL)
        return OS_ERR_OP;
    _ops = ops;
    return OS_ERR_NONE;
}
References _ops, OS_ERR_NONE, and OS_ERR_OP.