FreeRTOS-OS: drv_irq.h File Reference
drv_irq.h File Reference
#include <board/mcu_config.h>
#include <irq/irq_notify.h>
#include <device.h>
Functions
void drv_irq_disable (int32_t irqn)
Disable an interrupt line.
void drv_irq_dispatch (irq_id_t id, void *data)
Dispatch an IRQ event from task context. Calls every callback registered for id.
void drv_irq_dispatch_from_isr (irq_id_t id, void *data, BaseType_t *pxHPT)
Dispatch an IRQ event from ISR context. Each registered callback receives pxHPT so it can accumulate the FreeRTOS yield flag. Caller must call portYIELD_FROM_ISR(*pxHPT) after this returns.
void drv_irq_enable (int32_t irqn, uint32_t preempt_priority)
Set priority and enable an interrupt line.
int32_t drv_irq_register (irq_id_t id, irq_notify_cb_t cb, void *arg)
Register a callback for a software IRQ ID. Thin wrapper over irq_register() — upper layers include only this header and never touch irq_notify.h directly.
void drv_irq_set_priority (int32_t irqn, uint32_t preempt_priority)
Set only the priority of an interrupt without enabling it. Used for Cortex-M core exceptions (SVCall, PendSV) that are always present and do not need to be explicitly enabled.
Function Documentation
drv_irq_disable()
void drv_irq_disable (int32_t irqn)
Disable an interrupt line.
Definition at line 35 of file drv_irq.c.
{
    HAL_NVIC_DisableIRQ((IRQn_Type)irqn);
}
drv_irq_dispatch()
void drv_irq_dispatch (irq_id_t id, void * data)
Dispatch an IRQ event from task context. Calls every callback registered for id.
Definition at line 49 of file drv_irq.c.
{
    __do_IRQ(id, data);
}
References __do_IRQ().
drv_irq_dispatch_from_isr()
void drv_irq_dispatch_from_isr (irq_id_t id, void * data, BaseType_t * pxHPT)
Dispatch an IRQ event from ISR context. Each registered callback receives pxHPT so it can accumulate the FreeRTOS yield flag. Caller must call portYIELD_FROM_ISR(*pxHPT) after this returns.
Definition at line 54 of file drv_irq.c.
{
    __do_IRQ_from_isr(id, data, pxHPT);
}
References __do_IRQ_from_isr().
drv_irq_enable()
void drv_irq_enable (int32_t irqn, uint32_t preempt_priority)
Set priority and enable an interrupt line.
Parameters
irqn IRQ number cast to int32_t (IRQn_Type on Cortex-M).
preempt_priority NVIC preemption priority (0 = highest).
Definition at line 24 of file drv_irq.c.
{
    HAL_NVIC_SetPriority((IRQn_Type)irqn, preempt_priority, 0);
    HAL_NVIC_EnableIRQ((IRQn_Type)irqn);
}
drv_irq_register()
int32_t drv_irq_register (irq_id_t id, irq_notify_cb_t cb, void * arg)
Register a callback for a software IRQ ID. Thin wrapper over irq_register() — upper layers include only this header and never touch irq_notify.h directly.
Returns
0 on success, negative on error (subscriber table full, bad id).
Definition at line 44 of file drv_irq.c.
{
    return irq_register(id, cb, arg);
}
References irq_register().
drv_irq_set_priority()
void drv_irq_set_priority (int32_t irqn, uint32_t preempt_priority)
Set only the priority of an interrupt without enabling it. Used for Cortex-M core exceptions (SVCall, PendSV) that are always present and do not need to be explicitly enabled.
Definition at line 30 of file drv_irq.c.
{
    HAL_NVIC_SetPriority((IRQn_Type)irqn, preempt_priority, 0);
}