FreeRTOS-OS: drv_gpio.c File Reference
drv_gpio.c File Reference
#include <drivers/drv_handle.h>
#include <board/mcu_config.h>
#include <def_err.h>
Macros
#define DRV_GPIO_MAX_LINES 32
Functions
int32_t drv_gpio_clear_pin (uint8_t dev_id)
drv_gpio_handle_t * drv_gpio_get_handle (uint8_t dev_id)
uint8_t drv_gpio_read_pin (uint8_t dev_id)
int32_t drv_gpio_register (uint8_t dev_id, const drv_gpio_hal_ops_t *ops)
int32_t drv_gpio_set_pin (uint8_t dev_id)
int32_t drv_gpio_toggle_pin (uint8_t dev_id)
int32_t drv_gpio_write_pin (uint8_t dev_id, uint8_t state)
Variables
static drv_gpio_handle_t _gpio_handles [32]
static uint8_t _gpio_registered_count = 0
Macro Definition Documentation
DRV_GPIO_MAX_LINES
#define DRV_GPIO_MAX_LINES 32
Definition at line 20 of file drv_gpio.c.
Function Documentation
drv_gpio_clear_pin()
int32_t drv_gpio_clear_pin (uint8_t dev_id)
Definition at line 68 of file drv_gpio.c.
{
    drv_gpio_handle_t *h = drv_gpio_get_handle(dev_id);
    if (h == NULL || !h->initialized || h->ops == NULL)
        return OS_ERR_OP;
    h->ops->clear(h);
    return OS_ERR_NONE;
}
References drv_gpio_hal_ops::clear, drv_gpio_get_handle(), drv_gpio_handle::initialized, drv_gpio_handle::ops, OS_ERR_NONE, and OS_ERR_OP.
drv_gpio_get_handle()
drv_gpio_handle_t * drv_gpio_get_handle (uint8_t dev_id)
Definition at line 50 of file drv_gpio.c.
{
    if (dev_id >= DRV_GPIO_MAX_LINES)
        return NULL;
    return &_gpio_handles[dev_id];
}
References _gpio_handles, and DRV_GPIO_MAX_LINES.
drv_gpio_read_pin()
uint8_t drv_gpio_read_pin (uint8_t dev_id)
Definition at line 95 of file drv_gpio.c.
{
    drv_gpio_handle_t *h = drv_gpio_get_handle(dev_id);
    if (h == NULL || !h->initialized || h->ops == NULL)
        return 0;
    return h->ops->read(h);
}
References drv_gpio_get_handle(), drv_gpio_handle::initialized, drv_gpio_handle::ops, and drv_gpio_hal_ops::read.
drv_gpio_register()
int32_t drv_gpio_register (uint8_t dev_id, const drv_gpio_hal_ops_t * ops)
Definition at line 30 of file drv_gpio.c.
{
    if (dev_id >= DRV_GPIO_MAX_LINES || ops == NULL)
        return OS_ERR_OP;
    drv_gpio_handle_t *h = &_gpio_handles[dev_id];
    h->dev_id      = dev_id;
    h->ops         = ops;
    h->initialized = 0;
    h->last_err    = OS_ERR_NONE;
    if (_gpio_registered_count <= dev_id)
        _gpio_registered_count = (uint8_t)(dev_id + 1);
    return h->ops->hw_init(h);
}
References _gpio_handles, _gpio_registered_count, drv_gpio_handle::dev_id, DRV_GPIO_MAX_LINES, drv_gpio_hal_ops::hw_init, drv_gpio_handle::initialized, drv_gpio_handle::last_err, drv_gpio_handle::ops, OS_ERR_NONE, and OS_ERR_OP.
drv_gpio_set_pin()
int32_t drv_gpio_set_pin (uint8_t dev_id)
Definition at line 59 of file drv_gpio.c.
{
    drv_gpio_handle_t *h = drv_gpio_get_handle(dev_id);
    if (h == NULL || !h->initialized || h->ops == NULL)
        return OS_ERR_OP;
    h->ops->set(h);
    return OS_ERR_NONE;
}
References drv_gpio_get_handle(), drv_gpio_handle::initialized, drv_gpio_handle::ops, OS_ERR_NONE, OS_ERR_OP, and drv_gpio_hal_ops::set.
drv_gpio_toggle_pin()
int32_t drv_gpio_toggle_pin (uint8_t dev_id)
Definition at line 77 of file drv_gpio.c.
{
    drv_gpio_handle_t *h = drv_gpio_get_handle(dev_id);
    if (h == NULL || !h->initialized || h->ops == NULL)
        return OS_ERR_OP;
    h->ops->toggle(h);
    return OS_ERR_NONE;
}
References drv_gpio_get_handle(), drv_gpio_handle::initialized, drv_gpio_handle::ops, OS_ERR_NONE, OS_ERR_OP, and drv_gpio_hal_ops::toggle.
drv_gpio_write_pin()
int32_t drv_gpio_write_pin (uint8_t dev_id, uint8_t state)
Definition at line 86 of file drv_gpio.c.
{
    drv_gpio_handle_t *h = drv_gpio_get_handle(dev_id);
    if (h == NULL || !h->initialized || h->ops == NULL)
        return OS_ERR_OP;
    h->ops->write(h, state);
    return OS_ERR_NONE;
}
References drv_gpio_get_handle(), drv_gpio_handle::initialized, drv_gpio_handle::ops, OS_ERR_NONE, OS_ERR_OP, and drv_gpio_hal_ops::write.
Variable Documentation
_gpio_handles
drv_gpio_handle_t _gpio_handles[32] static
Definition at line 25 of file drv_gpio.c.
_gpio_registered_count
uint8_t _gpio_registered_count = 0 static
Definition at line 26 of file drv_gpio.c.