FreeRTOS-OS: fsm.c File Reference
fsm.c File Reference
#include "fsm.h"
Macros
#define FSM_LOCK(fsm) (void)(fsm)
#define FSM_LOCK_ISR(fsm) (void)(fsm)
#define FSM_UNLOCK(fsm) (void)(fsm)
#define FSM_UNLOCK_ISR(fsm) (void)(fsm)
Functions
int fsm_dispatch (fsm_ctx_t *fsm, fsm_event_id_t id, void *data)
Post an event from task / thread context.
int fsm_dispatch_from_isr (fsm_ctx_t *fsm, fsm_event_id_t id, void *data)
Post an event from an ISR.
static void fsm_enter_down_from (fsm_ctx_t *fsm, const fsm_state_t *ancestor, fsm_state_t *target)
Walk down from 'ancestor' to 'target' calling on_entry.
static fsm_event_t * fsm_event_alloc (fsm_event_id_t id, void *data)
static void fsm_exit_up_to (fsm_ctx_t *fsm, const fsm_state_t *stop)
Walk up the parent chain calling on_exit until 'stop'.
int fsm_init (fsm_ctx_t *fsm, fsm_state_t *initial, const fsm_transition_t *table, size_t table_len, void *user_data)
Initialise an FSM instance.
static fsm_state_t * fsm_lca (const fsm_state_t *a, const fsm_state_t *b)
Find the Lowest Common Ancestor (LCA) of states a and b.
void fsm_run (fsm_ctx_t *fsm)
Process all pending events — call this in your task loop.
void fsm_stop (fsm_ctx_t *fsm)
Signal the FSM to stop after the current event finishes.
static fsm_event_t * queue_pop (fsm_ctx_t *fsm)
Remove and return the event at the head of the queue.
static void queue_push (fsm_ctx_t *fsm, fsm_event_t *event)
Append an event to the tail of the internal queue.
Macro Definition Documentation
FSM_LOCK
#define FSM_LOCK (fsm) (void)(fsm)
Definition at line 37 of file fsm.c.
FSM_LOCK_ISR
#define FSM_LOCK_ISR (fsm) (void)(fsm)
Definition at line 39 of file fsm.c.
FSM_UNLOCK
#define FSM_UNLOCK (fsm) (void)(fsm)
Definition at line 38 of file fsm.c.
FSM_UNLOCK_ISR
#define FSM_UNLOCK_ISR (fsm) (void)(fsm)
Definition at line 40 of file fsm.c.
Function Documentation
fsm_dispatch()
int fsm_dispatch (fsm_ctx_t * fsm, fsm_event_id_t id, void * data)
Post an event from task / thread context.
Allocates an event on the heap and appends it to the internal queue. The event is freed automatically by fsm_run() after processing.
Parameters
fsm FSM context.
id Event identifier.
data Optional payload pointer (caller manages lifetime).
Returns
FSM_OK, FSM_ERR_NULL, or FSM_ERR_ALLOC.
< NULL pointer passed
< malloc returned NULL
Definition at line 277 of file fsm.c.
{
    if (fsm == NULL)
    {
        return FSM_ERR_NULL;
    }
    fsm_event_t *e = fsm_event_alloc(id, data);
    if (e == NULL)
    {
        return FSM_ERR_ALLOC;
    }
    FSM_LOCK(fsm);
    queue_push(fsm, e);
    FSM_UNLOCK(fsm);
    return FSM_OK;
}
References FSM_ERR_ALLOC, FSM_ERR_NULL, fsm_event_alloc(), FSM_LOCK, FSM_OK, FSM_UNLOCK, and queue_push().
fsm_dispatch_from_isr()
int fsm_dispatch_from_isr (fsm_ctx_t * fsm, fsm_event_id_t id, void * data)
Post an event from an ISR.
Identical to fsm_dispatch() but uses the ISR lock/unlock hooks instead of the task hooks.
Note
malloc() is called internally. Ensure your heap allocator is interrupt-safe (e.g. FreeRTOS heap_4 with configUSE_NEWLIB_REENTRANT or a custom ISR-safe allocator). Alternatively call from a deferred interrupt task.
Parameters
fsm FSM context.
id Event identifier.
data Optional payload pointer.
Returns
FSM_OK, FSM_ERR_NULL, or FSM_ERR_ALLOC.
< NULL pointer passed
< malloc returned NULL
Definition at line 299 of file fsm.c.
{
    if (fsm == NULL)
    {
        return FSM_ERR_NULL;
    }
    fsm_event_t *e = fsm_event_alloc(id, data);
    if (e == NULL)
    {
        return FSM_ERR_ALLOC;
    }
    FSM_LOCK_ISR(fsm);
    queue_push(fsm, e);
    FSM_UNLOCK_ISR(fsm);
    return FSM_OK;
}
References FSM_ERR_ALLOC, FSM_ERR_NULL, fsm_event_alloc(), FSM_LOCK_ISR, FSM_OK, FSM_UNLOCK_ISR, and queue_push().
fsm_enter_down_from()
static void fsm_enter_down_from (fsm_ctx_t * fsm, const fsm_state_t * ancestor, fsm_state_t * target) static
Walk down from 'ancestor' to 'target' calling on_entry.
Entry handlers are fired top-down so that outer (parent) states are always entered before inner (child) states.
Definition at line 129 of file fsm.c.
{
    /* Build the path from target up to (not including) ancestor */
    fsm_state_t *stack[FSM_HIERARCHY_DEPTH_MAX];
    uint32_t     depth = 0U;
    fsm_state_t *s     = target;
    while (s != NULL && s != ancestor)
    {
        if (depth < FSM_HIERARCHY_DEPTH_MAX)
        {
            stack[depth++] = s;
        }
        s = s->parent;
    }
    /* Replay entry handlers from ancestor downwards */
    while (depth > 0U)
    {
        --depth;
        if (stack[depth]->on_entry != NULL)
        {
            stack[depth]->on_entry(stack[depth], fsm);
        }
    }
}
References FSM_HIERARCHY_DEPTH_MAX, fsm_state::on_entry, and fsm_state::parent.
fsm_event_alloc()
static fsm_event_t * fsm_event_alloc (fsm_event_id_t id, void * data) static
Definition at line 191 of file fsm.c.
{
    fsm_event_t *e = (fsm_event_t *)malloc(sizeof(fsm_event_t));
    if (e == NULL)
    {
        return NULL;
    }
    e->id   = id;
    e->data = data;
    e->next = NULL;
    return e;
}
References fsm_event::data, fsm_event::id, and fsm_event::next.
fsm_exit_up_to()
static void fsm_exit_up_to (fsm_ctx_t * fsm, const fsm_state_t * stop) static
Walk up the parent chain calling on_exit until 'stop'.
'stop' is NOT exited (it is the LCA — common ancestor of source and target states, or NULL to exit all the way to the root).
Definition at line 108 of file fsm.c.
{
    fsm_state_t *s = fsm->current;
    while (s != NULL && s != stop)
    {
        if (s->on_exit != NULL)
        {
            s->on_exit(s, fsm);
        }
        s = s->parent;
    }
}
References fsm_ctx::current, fsm_state::on_exit, and fsm_state::parent.
fsm_init()
int fsm_init (fsm_ctx_t * fsm, fsm_state_t * initial, const fsm_transition_t * table, size_t table_len, void * user_data)
Initialise an FSM instance.
Clears the internal queue, sets the initial state, and fires its on_entry handler.
Parameters
fsm FSM context (caller-allocated; may be static).
initial First active state.
table Transition table array (may be const / ROM).
table_len Number of rows in 'table'.
user_data Arbitrary context passed to every callback.
Returns
FSM_OK or FSM_ERR_NULL.
< NULL pointer passed
Definition at line 212 of file fsm.c.
{
    if (fsm == NULL || initial == NULL || table == NULL)
    {
        return FSM_ERR_NULL;
    }
    fsm->current    = initial;
    fsm->table      = table;
    fsm->table_len  = table_len;
    fsm->user_data  = user_data;
    fsm->queue_head = NULL;
    fsm->queue_tail = NULL;
    fsm->running    = 1;
#if (FSM_THREAD_SAFE == 1)
    fsm->lock        = NULL;
    fsm->unlock      = NULL;
    fsm->lock_isr    = NULL;
    fsm->unlock_isr  = NULL;
#endif
    /* Fire entry handler of the initial state */
    if (initial->on_entry != NULL)
    {
        initial->on_entry(initial, fsm);
    }
    return FSM_OK;
}
References fsm_ctx::current, FSM_ERR_NULL, FSM_OK, fsm_state::on_entry, fsm_ctx::queue_head, fsm_ctx::queue_tail, fsm_ctx::running, fsm_ctx::table, fsm_ctx::table_len, and fsm_ctx::user_data.
fsm_lca()
static fsm_state_t * fsm_lca (const fsm_state_t * a, const fsm_state_t * b) static
Find the Lowest Common Ancestor (LCA) of states a and b.
Walks the parent chain of 'a' and for each ancestor checks whether it also appears in the ancestry of 'b'.
Returns NULL when there is no common ancestor (flat, no parents).
Definition at line 167 of file fsm.c.
{
    const fsm_state_t *pa;
    const fsm_state_t *pb;
    for (pa = a; pa != NULL; pa = pa->parent)
    {
        for (pb = b; pb != NULL; pb = pb->parent)
        {
            if (pa == pb)
            {
                return (fsm_state_t *)pa;
            }
        }
    }
    return NULL;
}
References fsm_state::parent.
fsm_run()
void fsm_run (fsm_ctx_t * fsm)
Process all pending events — call this in your task loop.
Drains the internal queue: for each event it finds the matching transition, runs exit → action → entry handlers, updates the active state, and frees the event. Returns when the queue is empty.
Events with no matching transition for the current state are silently discarded.
Typical patterns:
// Bare-metal super-loop
for (;;) { fsm_run(&fsm); }
// RTOS task — unblock via semaphore/notification, then drain
for (;;) {
    ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
    fsm_run(&fsm);
}
Parameters
fsm FSM context.
Definition at line 321 of file fsm.c.
{
    if (fsm == NULL || fsm->running == 0)
    {
        return;
    }
    fsm_event_t *event;
    /* Drain the entire queue before returning */
    for (;;)
    {
        /* Pop under lock to avoid race with concurrent dispatch */
        FSM_LOCK(fsm);
        event = queue_pop(fsm);
        FSM_UNLOCK(fsm);
        if (event == NULL)
        {
            break;  /* Queue empty — done for this cycle */
        }
        /* Search transition table for (current_state, event_id) */
        for (size_t i = 0U; i < fsm->table_len; ++i)
        {
            if (fsm->table[i].from  == fsm->current &&
                fsm->table[i].event == event->id)
            {
                fsm_state_t *target = fsm->table[i].to;
                /* Find LCA for correct HSM entry/exit ordering */
                fsm_state_t *lca = fsm_lca(fsm->current, target);
                /* 1. Exit current state up to (not including) LCA */
                fsm_exit_up_to(fsm, lca);
                /* 2. Execute transition action */
                if (fsm->table[i].action != NULL)
                {
                    fsm->table[i].action(event, fsm);
                }
                /* 3. Enter target state down from LCA */
                fsm_enter_down_from(fsm, lca, target);
                /* 4. Commit new state */
                fsm->current = target;
                break;
            }
        }
        /* Events with no matching transition are silently discarded */
        free(event);
    }
}
References fsm_transition_t::action, fsm_ctx::current, fsm_transition_t::event, fsm_transition_t::from, fsm_enter_down_from(), fsm_exit_up_to(), fsm_lca(), FSM_LOCK, FSM_UNLOCK, fsm_event::id, queue_pop(), fsm_ctx::running, fsm_ctx::table, fsm_ctx::table_len, and fsm_transition_t::to.
fsm_stop()
void fsm_stop (fsm_ctx_t * fsm)
Signal the FSM to stop after the current event finishes.
Sets fsm->running = 0. fsm_run() will return immediately on the next call.
Parameters
fsm FSM context.
Definition at line 268 of file fsm.c.
{
    if (fsm != NULL)
    {
        fsm->running = 0;
    }
}
References fsm_ctx::running.
queue_pop()
static fsm_event_t * queue_pop (fsm_ctx_t * fsm) static
Remove and return the event at the head of the queue.
Returns NULL if the queue is empty. Caller must hold the appropriate lock before calling.
Definition at line 78 of file fsm.c.
{
    fsm_event_t *e = fsm->queue_head;
    if (e != NULL)
    {
        fsm->queue_head = e->next;
        if (fsm->queue_head == NULL)
        {
            fsm->queue_tail = NULL;
        }
        e->next = NULL;
    }
    return e;
}
References fsm_event::next, fsm_ctx::queue_head, and fsm_ctx::queue_tail.
queue_push()
static void queue_push (fsm_ctx_t * fsm, fsm_event_t * event) static
Append an event to the tail of the internal queue.
Caller must hold the appropriate lock before calling.
Definition at line 54 of file fsm.c.
{
    event->next = NULL;
    if (fsm->queue_tail == NULL)
    {
        /* Queue was empty */
        fsm->queue_head = event;
        fsm->queue_tail = event;
    }
    else
    {
        fsm->queue_tail->next = event;
        fsm->queue_tail       = event;
    }
}
References fsm_event::next, fsm_ctx::queue_head, and fsm_ctx::queue_tail.