FreeRTOS-OS: gpio_app.h File Reference
gpio_app.h File Reference
#include <def_std.h>
#include <def_err.h>
#include <services/gpio_mgmt.h>
Functions
int32_t gpio_async_clear (uint8_t gpio_id)
Clear pin to its inactive state (non-blocking).
int32_t gpio_async_delayed (uint8_t gpio_id, gpio_mgmt_cmd_t cmd, uint8_t state, uint32_t delay_ms)
Schedule a GPIO command with an optional pre-execution delay.
int32_t gpio_async_set (uint8_t gpio_id)
Set pin to its active state (non-blocking).
int32_t gpio_async_toggle (uint8_t gpio_id)
Toggle pin state (non-blocking).
int32_t gpio_async_write (uint8_t gpio_id, uint8_t state)
Write an explicit 0/1 level to the pin (non-blocking).
uint8_t gpio_read (uint8_t gpio_id)
Read current logical state of a GPIO pin.
Function Documentation
gpio_async_clear()
int32_t gpio_async_clear (uint8_t gpio_id)
Clear pin to its inactive state (non-blocking).
Definition at line 27 of file gpio_app.c.
{
    return gpio_mgmt_post(gpio_id, GPIO_MGMT_CMD_CLEAR, 0, 0);
}
References GPIO_MGMT_CMD_CLEAR, and gpio_mgmt_post().
gpio_async_delayed()
int32_t gpio_async_delayed (uint8_t gpio_id, gpio_mgmt_cmd_t cmd, uint8_t state, uint32_t delay_ms)
Schedule a GPIO command with an optional pre-execution delay.
The management thread waits delay_ms before executing the command. Useful for generating reset pulses or timed enable sequences.
Parameters
gpio_id Logical GPIO line ID.
cmd Command (GPIO_MGMT_CMD_SET / CLEAR / TOGGLE / WRITE).
state State value (only used for GPIO_MGMT_CMD_WRITE).
delay_ms Delay before executing the command (0 = immediate).
Definition at line 42 of file gpio_app.c.
{
    return gpio_mgmt_post(gpio_id, cmd, state, delay_ms);
}
References gpio_mgmt_post().
gpio_async_set()
int32_t gpio_async_set (uint8_t gpio_id)
Set pin to its active state (non-blocking).
Definition at line 22 of file gpio_app.c.
{
    return gpio_mgmt_post(gpio_id, GPIO_MGMT_CMD_SET, 0, 0);
}
References GPIO_MGMT_CMD_SET, and gpio_mgmt_post().
gpio_async_toggle()
int32_t gpio_async_toggle (uint8_t gpio_id)
Toggle pin state (non-blocking).
Definition at line 32 of file gpio_app.c.
{
    return gpio_mgmt_post(gpio_id, GPIO_MGMT_CMD_TOGGLE, 0, 0);
}
References GPIO_MGMT_CMD_TOGGLE, and gpio_mgmt_post().
gpio_async_write()
int32_t gpio_async_write (uint8_t gpio_id, uint8_t state)
Write an explicit 0/1 level to the pin (non-blocking).
Parameters
state 1 = active state, 0 = inactive state.
Definition at line 37 of file gpio_app.c.
{
    return gpio_mgmt_post(gpio_id, GPIO_MGMT_CMD_WRITE, state, 0);
}
References GPIO_MGMT_CMD_WRITE, and gpio_mgmt_post().
gpio_read()
uint8_t gpio_read (uint8_t gpio_id)
Read current logical state of a GPIO pin.
Calls the driver read() op directly — no management queue involved. Safe to call from any task at any time after gpio_mgmt has initialised.
Parameters
gpio_id Logical GPIO line ID.
Returns
1 if pin is at its active state, 0 otherwise, 0xFF on error.
Definition at line 12 of file gpio_app.c.
{
    drv_gpio_handle_t *h = drv_gpio_get_handle(gpio_id);
    if (h == NULL || h->ops == NULL || !h->initialized)
        return 0xFFU;
    return h->ops->read(h);
}
References drv_gpio_get_handle(), drv_gpio_handle::initialized, drv_gpio_handle::ops, and drv_gpio_hal_ops::read.