FreeRTOS-OS: hal_timebase_stm32.c File Reference
hal_timebase_stm32.c File Reference
#include <board/mcu_config.h>
#include <device.h>
#include <irq/irq_desc.h>
#include <drivers/hal/stm32/hal_timebase_stm32.h>
#include <drivers/timer/drv_time.h>
#include <drivers/drv_rcc.h>
Functions
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
void HAL_ResumeTick (void)
void HAL_SuspendTick (void)
void hal_timebase_stm32_irq_handler (void)
Variables
static TIM_HandleTypeDef _htim1
Function Documentation
HAL_InitTick()
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
Definition at line 40 of file hal_timebase_stm32.c.
{
    RCC_ClkInitTypeDef clkconfig;
    uint32_t           uwTimclock;
    uint32_t           uwPrescalerValue;
    uint32_t           pFLatency;
    HAL_StatusTypeDef  status;
    drv_rcc_periph_clk_en(DRV_RCC_PERIPH_TIM1);
    HAL_RCC_GetClockConfig(&clkconfig, &pFLatency);
    uwTimclock       = 2U * HAL_RCC_GetPCLK2Freq();
    uwPrescalerValue = (uwTimclock / 1000000U) - 1U;
    _htim1.Instance               = TIM1;
    _htim1.Init.Period            = (1000000U / 1000U) - 1U;
    _htim1.Init.Prescaler         = uwPrescalerValue;
    _htim1.Init.ClockDivision     = 0;
    _htim1.Init.CounterMode       = TIM_COUNTERMODE_UP;
    _htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    status = HAL_TIM_Base_Init(&_htim1);
    if (status == HAL_OK)
    {
        status = HAL_TIM_Base_Start_IT(&_htim1);
        if (status == HAL_OK)
        {
            HAL_NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);
            if (TickPriority < (1UL << __NVIC_PRIO_BITS))
            {
                HAL_NVIC_SetPriority(TIM1_UP_TIM10_IRQn, TickPriority, 0U);
                uwTickPrio = TickPriority;
            }
            else
            {
                status = HAL_ERROR;
            }
        }
    }
    return status;
}
References _htim1, drv_rcc_periph_clk_en(), and DRV_RCC_PERIPH_TIM1.
HAL_ResumeTick()
void HAL_ResumeTick (void)
Definition at line 90 of file hal_timebase_stm32.c.
{
    __HAL_TIM_ENABLE_IT(&_htim1, TIM_IT_UPDATE);
}
References _htim1.
HAL_SuspendTick()
void HAL_SuspendTick (void)
Definition at line 85 of file hal_timebase_stm32.c.
{
    __HAL_TIM_DISABLE_IT(&_htim1, TIM_IT_UPDATE);
}
References _htim1.
hal_timebase_stm32_irq_handler()
void hal_timebase_stm32_irq_handler (void)
Called from TIM1_UP_TIM10_IRQHandler to advance the HAL tick.
Definition at line 97 of file hal_timebase_stm32.c.
{
    BaseType_t pxHPT = pdFALSE;
    /* Service hardware first — clear pending flag and advance tick counters.
     * Done unconditionally so the system works before irq_hw_init_all(). */
    __HAL_TIM_CLEAR_FLAG(&_htim1, TIM_FLAG_UPDATE);
    g_ms_ticks++;
    HAL_IncTick();
    /* Notify any irq_desc subscribers (populated after irq_hw_init_all). */
    struct irq_desc *desc = irq_to_desc(IRQ_ID_TIM_TICK);
    if (desc != NULL && desc->handle_irq != NULL)
        __do_IRQ_from_isr(IRQ_ID_TIM_TICK, NULL, &pxHPT);
    portYIELD_FROM_ISR(pxHPT);
}
References __do_IRQ_from_isr(), _htim1, g_ms_ticks, irq_desc::handle_irq, and irq_to_desc().
Variable Documentation
_htim1
TIM_HandleTypeDef _htim1 static
Definition at line 36 of file hal_timebase_stm32.c.