FreeRTOS-OS: hal_iic_stm32.h File Reference
hal_iic_stm32.h File Reference
#include <board/mcu_config.h>
#include <drivers/drv_handle.h>
Functions
void hal_iic_stm32_er_irq_handler (I2C_TypeDef *instance)
Called from I2Cx_ER_IRQHandler to dispatch HAL_I2C_ER_IRQHandler to whichever generic handle owns instance.
void hal_iic_stm32_ev_irq_handler (I2C_TypeDef *instance)
Called from I2Cx_EV_IRQHandler to dispatch HAL_I2C_EV_IRQHandler to whichever generic handle owns instance.
const drv_iic_hal_ops_t * hal_iic_stm32_get_ops (void)
Return pointer to the STM32 I2C HAL ops table.
void hal_iic_stm32_set_config (drv_iic_handle_t *h, I2C_TypeDef *instance, uint32_t addr_mode, uint32_t dual_addr)
Populate the hardware context in a generic I2C handle.
Function Documentation
hal_iic_stm32_er_irq_handler()
void hal_iic_stm32_er_irq_handler (I2C_TypeDef * instance)
Called from I2Cx_ER_IRQHandler to dispatch HAL_I2C_ER_IRQHandler to whichever generic handle owns instance.
Definition at line 286 of file hal_iic_stm32.c.
{
    for (uint8_t id = 0; id < NO_OF_IIC; id++)
    {
        drv_iic_handle_t *h = drv_iic_get_handle(id);
        if (h == NULL || !h->initialized || h->hw.hi2c.Instance != instance)
            continue;
        HAL_I2C_ER_IRQHandler(&h->hw.hi2c);
        uint32_t err = HAL_I2C_GetError(&h->hw.hi2c);
        h->last_err  = OS_ERR_OP;
        BaseType_t hpt = pdFALSE;
        drv_irq_dispatch_from_isr(IRQ_ID_I2C_ERROR(id), &err, &hpt);
        portYIELD_FROM_ISR(hpt);
        return;
    }
}
References drv_iic_get_handle(), drv_irq_dispatch_from_isr(), drv_hw_iic_ctx_t::hi2c, drv_iic_handle::hw, drv_iic_handle::initialized, drv_iic_handle::last_err, and OS_ERR_OP.
hal_iic_stm32_ev_irq_handler()
void hal_iic_stm32_ev_irq_handler (I2C_TypeDef * instance)
Called from I2Cx_EV_IRQHandler to dispatch HAL_I2C_EV_IRQHandler to whichever generic handle owns instance.
Definition at line 253 of file hal_iic_stm32.c.
{
    for (uint8_t id = 0; id < NO_OF_IIC; id++)
    {
        drv_iic_handle_t *h = drv_iic_get_handle(id);
        if (h == NULL || !h->initialized || h->hw.hi2c.Instance != instance)
            continue;
        HAL_I2C_StateTypeDef prev = HAL_I2C_GetState(&h->hw.hi2c);
        HAL_I2C_EV_IRQHandler(&h->hw.hi2c);
        HAL_I2C_StateTypeDef next = HAL_I2C_GetState(&h->hw.hi2c);
        if (next == HAL_I2C_STATE_READY && prev != HAL_I2C_STATE_READY)
        {
            h->last_err = OS_ERR_NONE;
            BaseType_t hpt = pdFALSE;
            if (prev == HAL_I2C_STATE_BUSY_TX)
                drv_irq_dispatch_from_isr(IRQ_ID_I2C_TX_DONE(id), NULL, &hpt);
            else
                drv_irq_dispatch_from_isr(IRQ_ID_I2C_RX_DONE(id), NULL, &hpt);
            portYIELD_FROM_ISR(hpt);
        }
        return;
    }
}
References drv_iic_get_handle(), drv_irq_dispatch_from_isr(), drv_hw_iic_ctx_t::hi2c, drv_iic_handle::hw, drv_iic_handle::initialized, drv_iic_handle::last_err, and OS_ERR_NONE.
hal_iic_stm32_get_ops()
const drv_iic_hal_ops_t * hal_iic_stm32_get_ops (void)
Return pointer to the STM32 I2C HAL ops table.
Definition at line 217 of file hal_iic_stm32.c.
{
    return &_stm32_iic_ops;
}
References _stm32_iic_ops.
hal_iic_stm32_set_config()
void hal_iic_stm32_set_config (drv_iic_handle_t * h, I2C_TypeDef * instance, uint32_t addr_mode, uint32_t dual_addr)
Populate the hardware context in a generic I2C handle.
Parameters
h Generic I2C handle.
instance I2C peripheral instance (I2C1, I2C2, …).
addr_mode I2C_ADDRESSINGMODE_7BIT / I2C_ADDRESSINGMODE_10BIT
dual_addr I2C_DUALADDRESS_DISABLE / I2C_DUALADDRESS_ENABLE
Definition at line 222 of file hal_iic_stm32.c.
{
    if (h == NULL || instance == NULL)
        return;
    I2C_HandleTypeDef *hi2c = &h->hw.hi2c;
    hi2c->Instance              = instance;
    hi2c->Init.AddressingMode   = addr_mode;
    hi2c->Init.DualAddressMode  = dual_addr;
    hi2c->Init.OwnAddress1      = 0;
    hi2c->Init.OwnAddress2      = 0;
    hi2c->Init.GeneralCallMode  = I2C_GENERALCALL_DISABLE;
    hi2c->Init.NoStretchMode    = I2C_NOSTRETCH_DISABLE;
    /* ClockSpeed will be set from h->clock_hz in hw_init */
}
References drv_hw_iic_ctx_t::hi2c, and drv_iic_handle::hw.