FreeRTOS-OS: hal_dma_stm32.c File Reference
hal_dma_stm32.c File Reference
#include <drivers/dma/hal/stm32/hal_dma_stm32.h>
#include <def_err.h>
Functions
static int32_t _chan_deinit (dma_chan_t *chan)
static int32_t _chan_init (dma_chan_t *chan)
static int32_t _dma_start (dma_chan_t *chan, dma_async_tx_descriptor_t *desc)
static uint32_t _get_residue (dma_chan_t *chan)
static uint32_t _hal_align (dma_slave_buswidth_t w)
static void _hal_cplt_cb (DMA_HandleTypeDef *hdma)
static uint32_t _hal_dir (dma_transfer_direction_t d)
static void _hal_error_cb (DMA_HandleTypeDef *hdma)
static int32_t _pause (dma_chan_t *chan)
static int32_t _resume (dma_chan_t *chan)
static int32_t _slave_config (dma_chan_t *chan, const dma_slave_config_t *cfg)
static int32_t _terminate_all (dma_chan_t *chan)
void hal_dma_stm32_init (void)
void hal_dma_stm32_irq_dispatch (uint8_t ctrl_idx, uint8_t stream_idx)
Variables
static drv_hw_dma_chan_ctx_t _dma1_ctx [8]
static const IRQn_Type _dma1_irqn [8]
static DMA_Stream_TypeDef *const _dma1_stream [8]
static drv_hw_dma_chan_ctx_t _dma2_ctx [8]
static const IRQn_Type _dma2_irqn [8]
static DMA_Stream_TypeDef *const _dma2_stream [8]
static const dma_chan_hal_ops_t _stm32_ops
dma_device_t hal_dma1_device
dma_device_t hal_dma2_device
Function Documentation
_chan_deinit()
static int32_t _chan_deinit (dma_chan_t * chan) static
Definition at line 105 of file hal_dma_stm32.c.
{
    drv_hw_dma_chan_ctx_t *ctx = (drv_hw_dma_chan_ctx_t *)chan->hw_ctx;
    if (ctx->hdma.State != HAL_DMA_STATE_RESET)
        HAL_DMA_DeInit(&ctx->hdma);
    HAL_NVIC_DisableIRQ(ctx->irqn);
    return OS_ERR_NONE;
}
References drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, drv_hw_dma_chan_ctx_t::irqn, and OS_ERR_NONE.
_chan_init()
static int32_t _chan_init (dma_chan_t * chan) static
Definition at line 98 of file hal_dma_stm32.c.
{
    (void)chan;
    /* hw_ctx already wired by hal_dma_stm32_init() before registration */
    return OS_ERR_NONE;
}
References OS_ERR_NONE.
_dma_start()
static int32_t _dma_start (dma_chan_t * chan, dma_async_tx_descriptor_t * desc) static
Definition at line 148 of file hal_dma_stm32.c.
{
    drv_hw_dma_chan_ctx_t *ctx = (drv_hw_dma_chan_ctx_t *)chan->hw_ctx;
    DMA_HandleTypeDef     *h   = &ctx->hdma;
    /* Switch mode if needed */
    uint32_t mode = (desc->mode == DMA_XFER_CYCLIC) ? DMA_CIRCULAR : DMA_NORMAL;
    if (h->Init.Mode != mode)
    {
        h->Init.Mode = mode;
        HAL_DMA_Init(h);
        h->XferCpltCallback  = _hal_cplt_cb;
        h->XferErrorCallback = _hal_error_cb;
        h->Parent            = (void *)chan;
    }
    /* Compute element count from byte length and peripheral width */
    const dma_slave_config_t *cfg   = &chan->slave_cfg;
    uint8_t                   width = (uint8_t)(cfg->src_addr_width
                                       ? cfg->src_addr_width : 1U);
    uint32_t                  count = desc->len / width;
    if (desc->direction == DMA_MEM_TO_MEM)
    {
        /* memcpy: both sides increment with byte width */
        h->Init.PeriphInc           = DMA_PINC_ENABLE;
        h->Init.MemInc              = DMA_MINC_ENABLE;
        h->Init.PeriphDataAlignment = DMA_PDATAALIGN_BYTE;
        h->Init.MemDataAlignment    = DMA_MDATAALIGN_BYTE;
        HAL_DMA_Init(h);
        h->XferCpltCallback  = _hal_cplt_cb;
        h->XferErrorCallback = _hal_error_cb;
        h->Parent            = (void *)chan;
        count = desc->len;
    }
    if (HAL_DMA_Start_IT(h, desc->src, desc->dst, count) != HAL_OK)
        return OS_ERR_OP;
    return OS_ERR_NONE;
}
References _hal_cplt_cb(), _hal_error_cb(), dma_async_tx_descriptor::direction, DMA_MEM_TO_MEM, DMA_XFER_CYCLIC, dma_async_tx_descriptor::dst, drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, dma_async_tx_descriptor::len, dma_async_tx_descriptor::mode, OS_ERR_NONE, OS_ERR_OP, dma_chan::slave_cfg, dma_async_tx_descriptor::src, and dma_slave_config_t::src_addr_width.
_get_residue()
static uint32_t _get_residue (dma_chan_t * chan) static
Definition at line 211 of file hal_dma_stm32.c.
{
    drv_hw_dma_chan_ctx_t *ctx = (drv_hw_dma_chan_ctx_t *)chan->hw_ctx;
    uint8_t width = (uint8_t)(chan->slave_cfg.src_addr_width
                               ? chan->slave_cfg.src_addr_width : 1U);
    return ctx->hdma.Instance->NDTR * width;
}
References drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, dma_chan::slave_cfg, and dma_slave_config_t::src_addr_width.
_hal_align()
static uint32_t _hal_align (dma_slave_buswidth_t w) static
Definition at line 85 of file hal_dma_stm32.c.
{
    switch (w) {
    case DMA_SLAVE_BUSWIDTH_2_BYTES: return DMA_PDATAALIGN_HALFWORD;
    case DMA_SLAVE_BUSWIDTH_4_BYTES: return DMA_PDATAALIGN_WORD;
    default:                         return DMA_PDATAALIGN_BYTE;
    }
}
References DMA_SLAVE_BUSWIDTH_2_BYTES, and DMA_SLAVE_BUSWIDTH_4_BYTES.
_hal_cplt_cb()
static void _hal_cplt_cb (DMA_HandleTypeDef * hdma) static
Definition at line 61 of file hal_dma_stm32.c.
{
    dma_complete_callback((dma_chan_t *)hdma->Parent);
}
References dma_complete_callback().
_hal_dir()
static uint32_t _hal_dir (dma_transfer_direction_t d) static
Definition at line 73 of file hal_dma_stm32.c.
{
    switch (d) {
    case DMA_MEM_TO_DEV: return DMA_MEMORY_TO_PERIPH;
    case DMA_DEV_TO_MEM: return DMA_PERIPH_TO_MEMORY;
    case DMA_MEM_TO_MEM: return DMA_MEMORY_TO_MEMORY;
    default:             return DMA_PERIPH_TO_MEMORY;
    }
}
References DMA_DEV_TO_MEM, DMA_MEM_TO_DEV, and DMA_MEM_TO_MEM.
_hal_error_cb()
static void _hal_error_cb (DMA_HandleTypeDef * hdma) static
Definition at line 66 of file hal_dma_stm32.c.
{
    dma_error_callback((dma_chan_t *)hdma->Parent);
}
References dma_error_callback().
_pause()
static int32_t _pause (dma_chan_t * chan) static
Definition at line 197 of file hal_dma_stm32.c.
{
    drv_hw_dma_chan_ctx_t *ctx = (drv_hw_dma_chan_ctx_t *)chan->hw_ctx;
    ctx->hdma.Instance->CR &= ~DMA_SxCR_EN;
    return OS_ERR_NONE;
}
References drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, and OS_ERR_NONE.
_resume()
static int32_t _resume (dma_chan_t * chan) static
Definition at line 204 of file hal_dma_stm32.c.
{
    drv_hw_dma_chan_ctx_t *ctx = (drv_hw_dma_chan_ctx_t *)chan->hw_ctx;
    ctx->hdma.Instance->CR |= DMA_SxCR_EN;
    return OS_ERR_NONE;
}
References drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, and OS_ERR_NONE.
_slave_config()
static int32_t _slave_config (dma_chan_t * chan, const dma_slave_config_t * cfg) static
Definition at line 114 of file hal_dma_stm32.c.
{
    drv_hw_dma_chan_ctx_t *ctx = (drv_hw_dma_chan_ctx_t *)chan->hw_ctx;
    DMA_HandleTypeDef     *h   = &ctx->hdma;
    h->Init.Direction           = _hal_dir(cfg->direction);
    h->Init.Channel             = (uint32_t)cfg->request << DMA_SxCR_CHSEL_Pos;
    h->Init.PeriphInc           = (cfg->src_addr_adj == DMA_ADDR_INCREMENT)
                                    ? DMA_PINC_ENABLE : DMA_PINC_DISABLE;
    h->Init.MemInc              = (cfg->dst_addr_adj == DMA_ADDR_INCREMENT)
                                    ? DMA_MINC_ENABLE : DMA_MINC_DISABLE;
    h->Init.PeriphDataAlignment = _hal_align(cfg->src_addr_width);
    h->Init.MemDataAlignment    = _hal_align(cfg->dst_addr_width);
    h->Init.Mode                = DMA_NORMAL;
    h->Init.Priority            = DMA_PRIORITY_HIGH;
    h->Init.FIFOMode            = DMA_FIFOMODE_DISABLE;
    h->Init.FIFOThreshold       = DMA_FIFO_THRESHOLD_FULL;
    h->Init.MemBurst            = DMA_MBURST_SINGLE;
    h->Init.PeriphBurst         = DMA_PBURST_SINGLE;
    HAL_DMA_DeInit(h);
    if (HAL_DMA_Init(h) != HAL_OK)
        return OS_ERR_OP;
    h->XferCpltCallback  = _hal_cplt_cb;
    h->XferErrorCallback = _hal_error_cb;
    h->Parent            = (void *)chan; /* back-link for ISR dispatch */
    HAL_NVIC_SetPriority(ctx->irqn, 5, 0);
    HAL_NVIC_EnableIRQ(ctx->irqn);
    return OS_ERR_NONE;
}
References _hal_align(), _hal_cplt_cb(), _hal_dir(), _hal_error_cb(), dma_slave_config_t::direction, DMA_ADDR_INCREMENT, dma_slave_config_t::dst_addr_adj, dma_slave_config_t::dst_addr_width, drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, drv_hw_dma_chan_ctx_t::irqn, OS_ERR_NONE, OS_ERR_OP, dma_slave_config_t::request, dma_slave_config_t::src_addr_adj, and dma_slave_config_t::src_addr_width.
_terminate_all()
static int32_t _terminate_all (dma_chan_t * chan) static
Definition at line 190 of file hal_dma_stm32.c.
{
    drv_hw_dma_chan_ctx_t *ctx = (drv_hw_dma_chan_ctx_t *)chan->hw_ctx;
    HAL_DMA_Abort(&ctx->hdma);
    return OS_ERR_NONE;
}
References drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, and OS_ERR_NONE.
hal_dma_stm32_init()
void hal_dma_stm32_init (void)
Definition at line 248 of file hal_dma_stm32.c.
{
    __HAL_RCC_DMA1_CLK_ENABLE();
    __HAL_RCC_DMA2_CLK_ENABLE();
    for (uint8_t i = 0; i < 8; i++)
    {
        _dma1_ctx[i].hdma.Instance = _dma1_stream[i];
        _dma1_ctx[i].irqn          = _dma1_irqn[i];
        hal_dma1_device.channels[i].hw_ctx = &_dma1_ctx[i];
        _dma2_ctx[i].hdma.Instance = _dma2_stream[i];
        _dma2_ctx[i].irqn          = _dma2_irqn[i];
        hal_dma2_device.channels[i].hw_ctx = &_dma2_ctx[i];
    }
    dma_register_device(&hal_dma1_device);
    dma_register_device(&hal_dma2_device);
}
References _dma1_ctx, _dma1_irqn, _dma1_stream, _dma2_ctx, _dma2_irqn, _dma2_stream, dma_device::channels, dma_register_device(), hal_dma1_device, hal_dma2_device, drv_hw_dma_chan_ctx_t::hdma, dma_chan::hw_ctx, and drv_hw_dma_chan_ctx_t::irqn.
hal_dma_stm32_irq_dispatch()
void hal_dma_stm32_irq_dispatch (uint8_t ctrl_idx, uint8_t stream_idx)
Definition at line 281 of file hal_dma_stm32.c.
{
    if (stream_idx >= 8)
        return;
    if (ctrl_idx == 1)
        HAL_DMA_IRQHandler(&_dma1_ctx[stream_idx].hdma);
    else if (ctrl_idx == 2)
        HAL_DMA_IRQHandler(&_dma2_ctx[stream_idx].hdma);
}
References _dma1_ctx, and _dma2_ctx.
Variable Documentation
_dma1_ctx
drv_hw_dma_chan_ctx_t _dma1_ctx[8] static
Definition at line 56 of file hal_dma_stm32.c.
_dma1_irqn
const IRQn_Type _dma1_irqn[8] static
Initial value:
= {
    DMA1_Stream0_IRQn, DMA1_Stream1_IRQn, DMA1_Stream2_IRQn, DMA1_Stream3_IRQn,
    DMA1_Stream4_IRQn, DMA1_Stream5_IRQn, DMA1_Stream6_IRQn, DMA1_Stream7_IRQn,
}
Definition at line 44 of file hal_dma_stm32.c.
{
    DMA1_Stream0_IRQn, DMA1_Stream1_IRQn, DMA1_Stream2_IRQn, DMA1_Stream3_IRQn,
    DMA1_Stream4_IRQn, DMA1_Stream5_IRQn, DMA1_Stream6_IRQn, DMA1_Stream7_IRQn,
};
_dma1_stream
DMA_Stream_TypeDef* const _dma1_stream[8] static
Initial value:
= {
    DMA1_Stream0, DMA1_Stream1, DMA1_Stream2, DMA1_Stream3,
    DMA1_Stream4, DMA1_Stream5, DMA1_Stream6, DMA1_Stream7,
}
Definition at line 34 of file hal_dma_stm32.c.
{
    DMA1_Stream0, DMA1_Stream1, DMA1_Stream2, DMA1_Stream3,
    DMA1_Stream4, DMA1_Stream5, DMA1_Stream6, DMA1_Stream7,
};
_dma2_ctx
drv_hw_dma_chan_ctx_t _dma2_ctx[8] static
Definition at line 57 of file hal_dma_stm32.c.
_dma2_irqn
const IRQn_Type _dma2_irqn[8] static
Initial value:
= {
    DMA2_Stream0_IRQn, DMA2_Stream1_IRQn, DMA2_Stream2_IRQn, DMA2_Stream3_IRQn,
    DMA2_Stream4_IRQn, DMA2_Stream5_IRQn, DMA2_Stream6_IRQn, DMA2_Stream7_IRQn,
}
Definition at line 49 of file hal_dma_stm32.c.
{
    DMA2_Stream0_IRQn, DMA2_Stream1_IRQn, DMA2_Stream2_IRQn, DMA2_Stream3_IRQn,
    DMA2_Stream4_IRQn, DMA2_Stream5_IRQn, DMA2_Stream6_IRQn, DMA2_Stream7_IRQn,
};
_dma2_stream
DMA_Stream_TypeDef* const _dma2_stream[8] static
Initial value:
= {
    DMA2_Stream0, DMA2_Stream1, DMA2_Stream2, DMA2_Stream3,
    DMA2_Stream4, DMA2_Stream5, DMA2_Stream6, DMA2_Stream7,
}
Definition at line 39 of file hal_dma_stm32.c.
{
    DMA2_Stream0, DMA2_Stream1, DMA2_Stream2, DMA2_Stream3,
    DMA2_Stream4, DMA2_Stream5, DMA2_Stream6, DMA2_Stream7,
};
_stm32_ops
const dma_chan_hal_ops_t _stm32_ops static
Initial value:
= {
    .chan_init     = _chan_init,
    .chan_deinit   = _chan_deinit,
    .slave_config  = _slave_config,
    .start         = _dma_start,
    .terminate_all = _terminate_all,
    .pause         = _pause,
    .resume        = _resume,
    .get_residue   = _get_residue,
}
Definition at line 221 of file hal_dma_stm32.c.
{
    .chan_init     = _chan_init,
    .chan_deinit   = _chan_deinit,
    .slave_config  = _slave_config,
    .start         = _dma_start,
    .terminate_all = _terminate_all,
    .pause         = _pause,
    .resume        = _resume,
    .get_residue   = _get_residue,
};
hal_dma1_device
dma_device_t hal_dma1_device
Initial value:
= {
    .name        = "DMA1",
    .nr_channels = 8,
    .ops         = &_stm32_ops,
}
Definition at line 234 of file hal_dma_stm32.c.
{
    .name        = "DMA1",
    .nr_channels = 8,
    .ops         = &_stm32_ops,
};
hal_dma2_device
dma_device_t hal_dma2_device
Initial value:
= {
    .name        = "DMA2",
    .nr_channels = 8,
    .ops         = &_stm32_ops,
}
Definition at line 240 of file hal_dma_stm32.c.
{
    .name        = "DMA2",
    .nr_channels = 8,
    .ops         = &_stm32_ops,
};