FreeRTOS-OS: ringbuffer.h File Reference
ringbuffer.h File Reference
#include <stdint.h>
#include <stddef.h>
Classes
struct ringbuffer
Macros
#define ringbuffer_empty_space(rb) ((uint16_t)((rb)->buffer_size) - ringbuffer_data_len(rb))
Enumerations
enum ringbuffer_state { RT_RINGBUFFER_EMPTY , RT_RINGBUFFER_FULL , RT_RINGBUFFER_HALFFULL }
Functions
struct ringbuffer * ringbuffer_create (uint16_t size)
uint16_t ringbuffer_data_len (struct ringbuffer *rb)
void ringbuffer_destroy (struct ringbuffer *rb)
void ringbuffer_flush (struct ringbuffer *rb)
uint32_t ringbuffer_get (struct ringbuffer *rb, uint8_t *ptr, uint16_t length)
uint16_t ringbuffer_get_size (struct ringbuffer *rb)
uint32_t ringbuffer_getchar (struct ringbuffer *rb, uint8_t *ch)
uint32_t ringbuffer_getchar_from_isr (struct ringbuffer *rb, uint8_t *ch)
void ringbuffer_init (struct ringbuffer *rb, uint8_t *pool, int16_t size)
uint32_t ringbuffer_put (struct ringbuffer *rb, const uint8_t *ptr, uint16_t length)
uint32_t ringbuffer_put_force (struct ringbuffer *rb, const uint8_t *ptr, uint16_t length)
uint32_t ringbuffer_putchar (struct ringbuffer *rb, uint8_t ch)
uint32_t ringbuffer_putchar_force (struct ringbuffer *rb, uint8_t ch)
enum ringbuffer_state ringbuffer_status (struct ringbuffer *rb)
Macro Definition Documentation
ringbuffer_empty_space
#define ringbuffer_empty_space (rb) ((uint16_t)((rb)->buffer_size) - ringbuffer_data_len(rb))
Definition at line 90 of file ipc/ringbuffer.h.
Enumeration Type Documentation
ringbuffer_state
enum ringbuffer_state
Enumerator
RT_RINGBUFFER_EMPTY
RT_RINGBUFFER_FULL
RT_RINGBUFFER_HALFFULL
Definition at line 46 of file ipc/ringbuffer.h.
                      {
    RT_RINGBUFFER_EMPTY,
    RT_RINGBUFFER_FULL,
    RT_RINGBUFFER_HALFFULL,
};
Function Documentation
ringbuffer_create()
struct ringbuffer * ringbuffer_create (uint16_t size)
Definition at line 52 of file ringbuffer.c.
{
    if (size == 0)
        return NULL;
    struct ringbuffer *rb = (struct ringbuffer *)kmaloc(sizeof(*rb));
    if (rb == NULL)
        return NULL;
    uint8_t *buf = (uint8_t *)kmaloc(size);
    if (buf == NULL) {
        kfree(rb);
        return NULL;
    }
    ringbuffer_init(rb, buf, (int16_t)size);
    return rb;
}
References kfree(), kmaloc(), and ringbuffer_init().
ringbuffer_data_len()
uint16_t ringbuffer_data_len (struct ringbuffer * rb)
Definition at line 112 of file ringbuffer.c.
{
    taskENTER_CRITICAL();
    uint16_t len = _data_len(rb);
    taskEXIT_CRITICAL();
    return len;
}
References _data_len().
ringbuffer_destroy()
void ringbuffer_destroy (struct ringbuffer * rb)
Definition at line 71 of file ringbuffer.c.
{
    if (rb == NULL)
        return;
    if (rb->buffer_ptr != NULL)
        kfree(rb->buffer_ptr);
    kfree(rb);
}
References ringbuffer::buffer_ptr, and kfree().
ringbuffer_flush()
void ringbuffer_flush (struct ringbuffer * rb)
Definition at line 92 of file ringbuffer.c.
{
    taskENTER_CRITICAL();
    rb->read_mirror  = 0;
    rb->read_index   = 0;
    rb->write_mirror = 0;
    rb->write_index  = 0;
    taskEXIT_CRITICAL();
}
References ringbuffer::read_index, ringbuffer::read_mirror, ringbuffer::write_index, and ringbuffer::write_mirror.
ringbuffer_get()
uint32_t ringbuffer_get (struct ringbuffer * rb, uint8_t * ptr, uint16_t length)
Definition at line 231 of file ringbuffer.c.
{
    taskENTER_CRITICAL();
    uint16_t avail = _data_len(rb);
    if (avail == 0) {
        taskEXIT_CRITICAL();
        return 0;
    }
    if (avail < length)
        length = avail;
    uint16_t tail = (uint16_t)rb->buffer_size - rb->read_index;
    if (tail > length) {
        memcpy(ptr, &rb->buffer_ptr[rb->read_index], length);
        rb->read_index += length;
    } else {
        memcpy(ptr, &rb->buffer_ptr[rb->read_index], tail);
        memcpy(ptr + tail, &rb->buffer_ptr[0], length - tail);
        rb->read_mirror = (uint16_t)(~rb->read_mirror) & 1U;
        rb->read_index  = length - tail;
    }
    taskEXIT_CRITICAL();
    return length;
}
References _data_len(), ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::read_index, and ringbuffer::read_mirror.
ringbuffer_get_size()
uint16_t ringbuffer_get_size (struct ringbuffer * rb)
Definition at line 120 of file ringbuffer.c.
{
    return (uint16_t)rb->buffer_size;
}
References ringbuffer::buffer_size.
ringbuffer_getchar()
uint32_t ringbuffer_getchar (struct ringbuffer * rb, uint8_t * ch)
Definition at line 260 of file ringbuffer.c.
{
    taskENTER_CRITICAL();
    uint32_t ret = 0;
    if (_data_len(rb) > 0) {
        *ch = rb->buffer_ptr[rb->read_index];
        if (rb->read_index == (uint16_t)(rb->buffer_size - 1)) {
            rb->read_mirror = (uint16_t)(~rb->read_mirror) & 1U;
            rb->read_index  = 0;
        } else {
            rb->read_index++;
        }
        ret = 1;
    }
    taskEXIT_CRITICAL();
    return ret;
}
References _data_len(), ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::read_index, and ringbuffer::read_mirror.
ringbuffer_getchar_from_isr()
uint32_t ringbuffer_getchar_from_isr (struct ringbuffer * rb, uint8_t * ch)
Definition at line 282 of file ringbuffer.c.
{
    UBaseType_t ux = taskENTER_CRITICAL_FROM_ISR();
    uint32_t ret = 0;
    if (_data_len(rb) > 0) {
        *ch = rb->buffer_ptr[rb->read_index];
        if (rb->read_index == (uint16_t)(rb->buffer_size - 1)) {
            rb->read_mirror = (uint16_t)(~rb->read_mirror) & 1U;
            rb->read_index  = 0;
        } else {
            rb->read_index++;
        }
        ret = 1;
    }
    taskEXIT_CRITICAL_FROM_ISR(ux);
    return ret;
}
References _data_len(), ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::read_index, and ringbuffer::read_mirror.
ringbuffer_init()
void ringbuffer_init (struct ringbuffer * rb, uint8_t * pool, int16_t size)
Definition at line 82 of file ringbuffer.c.
{
    rb->read_mirror  = 0;
    rb->read_index   = 0;
    rb->write_mirror = 0;
    rb->write_index  = 0;
    rb->buffer_ptr   = pool;
    rb->buffer_size  = size;
}
References ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::read_index, ringbuffer::read_mirror, ringbuffer::write_index, and ringbuffer::write_mirror.
ringbuffer_put()
uint32_t ringbuffer_put (struct ringbuffer * rb, const uint8_t * ptr, uint16_t length)
Definition at line 127 of file ringbuffer.c.
{
    taskENTER_CRITICAL();
    uint16_t space = (uint16_t)rb->buffer_size - _data_len(rb);
    if (space == 0) {
        taskEXIT_CRITICAL();
        return 0;
    }
    if (space < length)
        length = space;
    uint16_t tail = (uint16_t)rb->buffer_size - rb->write_index;
    if (tail > length) {
        memcpy(&rb->buffer_ptr[rb->write_index], ptr, length);
        rb->write_index += length;
    } else {
        memcpy(&rb->buffer_ptr[rb->write_index], ptr, tail);
        memcpy(&rb->buffer_ptr[0], ptr + tail, length - tail);
        rb->write_mirror = (uint16_t)(~rb->write_mirror) & 1U;
        rb->write_index  = length - tail;
    }
    taskEXIT_CRITICAL();
    return length;
}
References _data_len(), ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::write_index, and ringbuffer::write_mirror.
ringbuffer_put_force()
uint32_t ringbuffer_put_force (struct ringbuffer * rb, const uint8_t * ptr, uint16_t length)
Definition at line 154 of file ringbuffer.c.
{
    taskENTER_CRITICAL();
    enum ringbuffer_state old = _status(rb);
    if (length > (uint16_t)rb->buffer_size)
        length = (uint16_t)rb->buffer_size;
    uint16_t tail = (uint16_t)rb->buffer_size - rb->write_index;
    if (tail > length) {
        memcpy(&rb->buffer_ptr[rb->write_index], ptr, length);
        rb->write_index += length;
        if (old == RT_RINGBUFFER_FULL)
            rb->read_index = rb->write_index;
    } else {
        memcpy(&rb->buffer_ptr[rb->write_index], ptr, tail);
        memcpy(&rb->buffer_ptr[0], ptr + tail, length - tail);
        rb->write_mirror = (uint16_t)(~rb->write_mirror) & 1U;
        rb->write_index  = length - tail;
        if (old == RT_RINGBUFFER_FULL) {
            rb->read_mirror = (uint16_t)(~rb->read_mirror) & 1U;
            rb->read_index  = rb->write_index;
        }
    }
    taskEXIT_CRITICAL();
    return length;
}
References _status(), ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::read_index, ringbuffer::read_mirror, RT_RINGBUFFER_FULL, ringbuffer::write_index, and ringbuffer::write_mirror.
ringbuffer_putchar()
uint32_t ringbuffer_putchar (struct ringbuffer * rb, uint8_t ch)
Definition at line 185 of file ringbuffer.c.
{
    UBaseType_t ux = taskENTER_CRITICAL_FROM_ISR();
    uint32_t ret = 0;
    if (_data_len(rb) < (uint16_t)rb->buffer_size) {
        rb->buffer_ptr[rb->write_index] = ch;
        if (rb->write_index == (uint16_t)(rb->buffer_size - 1)) {
            rb->write_mirror = (uint16_t)(~rb->write_mirror) & 1U;
            rb->write_index  = 0;
        } else {
            rb->write_index++;
        }
        ret = 1;
    }
    taskEXIT_CRITICAL_FROM_ISR(ux);
    return ret;
}
References _data_len(), ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::write_index, and ringbuffer::write_mirror.
ringbuffer_putchar_force()
uint32_t ringbuffer_putchar_force (struct ringbuffer * rb, uint8_t ch)
Definition at line 205 of file ringbuffer.c.
{
    UBaseType_t ux = taskENTER_CRITICAL_FROM_ISR();
    enum ringbuffer_state old = _status(rb);
    rb->buffer_ptr[rb->write_index] = ch;
    if (rb->write_index == (uint16_t)(rb->buffer_size - 1)) {
        rb->write_mirror = (uint16_t)(~rb->write_mirror) & 1U;
        rb->write_index  = 0;
        if (old == RT_RINGBUFFER_FULL) {
            rb->read_mirror = (uint16_t)(~rb->read_mirror) & 1U;
            rb->read_index  = 0;
        }
    } else {
        rb->write_index++;
        if (old == RT_RINGBUFFER_FULL)
            rb->read_index = rb->write_index;
    }
    taskEXIT_CRITICAL_FROM_ISR(ux);
    return 1;
}
References _status(), ringbuffer::buffer_ptr, ringbuffer::buffer_size, ringbuffer::read_index, ringbuffer::read_mirror, RT_RINGBUFFER_FULL, ringbuffer::write_index, and ringbuffer::write_mirror.
ringbuffer_status()
enum ringbuffer_state ringbuffer_status (struct ringbuffer * rb)
Definition at line 104 of file ringbuffer.c.
{
    taskENTER_CRITICAL();
    enum ringbuffer_state s = _status(rb);
    taskEXIT_CRITICAL();
    return s;
}
References _status().