FreeRTOS-OS: irq_notify.h File Reference
irq_notify.h File Reference
#include <board/irq_hw_conf.h>
#include <FreeRTOS.h>
Typedefs
typedef void(* irq_notify_cb_t) (irq_id_t id, void *data, void *arg, BaseType_t *pxHPT)
Functions
void irq_notify (irq_id_t id, void *data)
Dispatch notification to all registered callbacks (task context). pxHPT is passed as NULL — callbacks must not call FromISR APIs.
void irq_notify_from_isr (irq_id_t id, void *data, BaseType_t *pxHPT)
Dispatch notification from ISR context. Each registered callback receives the same pxHPT pointer so they can accumulate the yield flag. Caller must call portYIELD_FROM_ISR(*pxHPT) after this function returns.
int32_t irq_register (irq_id_t id, irq_notify_cb_t cb, void *arg)
Register a callback for a generic IRQ ID. Call from task context before interrupts fire. Duplicate (id, cb, arg) tuples are silently ignored.
Typedef Documentation
irq_notify_cb_t
typedef void(* irq_notify_cb_t) (irq_id_t id, void *data, void *arg, BaseType_t *pxHPT)
irq_notify_cb_t — subscriber callback invoked by irq_notify / irq_notify_from_isr.
Parameters
id The IRQ ID that fired.
data Event-specific payload pointer (e.g. received byte ptr, error code ptr).
arg User-supplied argument passed to irq_register().
pxHPT FreeRTOS higher-priority-task-woken accumulator. Set via vTaskNotifyGiveFromISR() etc. if a task was unblocked. NULL when called from task context (irq_notify).
Definition at line 53 of file irq_notify.h.
Function Documentation
irq_notify()
void irq_notify (irq_id_t id, void * data)
Dispatch notification to all registered callbacks (task context). pxHPT is passed as NULL — callbacks must not call FromISR APIs.
Definition at line 100 of file irq_notify.c.
{
    __do_IRQ(id, data);
}
References __do_IRQ().
irq_notify_from_isr()
void irq_notify_from_isr (irq_id_t id, void * data, BaseType_t * pxHPT)
Dispatch notification from ISR context. Each registered callback receives the same pxHPT pointer so they can accumulate the yield flag. Caller must call portYIELD_FROM_ISR(*pxHPT) after this function returns.
Definition at line 105 of file irq_notify.c.
{
    __do_IRQ_from_isr(id, data, pxHPT);
}
References __do_IRQ_from_isr().
irq_register()
int32_t irq_register (irq_id_t id, irq_notify_cb_t cb, void * arg)
Register a callback for a generic IRQ ID. Call from task context before interrupts fire. Duplicate (id, cb, arg) tuples are silently ignored.
Returns
0 on success, -1 if the subscriber table for id is full.
Definition at line 72 of file irq_notify.c.
{
    if (id >= IRQ_ID_TOTAL || cb == NULL)
        return OS_ERR_OP;
    /* Reject duplicate (id, cb, arg) registrations */
    for (unsigned int i = 0; i < _TRAMPOLINE_POOL_SIZE; i++)
    {
        if (_trampoline_pool[i].used &&
            _trampoline_pool[i].cb  == cb &&
            _trampoline_pool[i].arg == arg)
            return OS_ERR_NONE;
    }
    _notify_trampoline_t *t = _alloc_trampoline(cb, arg);
    if (t == NULL)
        return OS_ERR_MEM_OF;
    int32_t err = request_irq(id, _notify_trampoline, NULL, t);
    if (err != OS_ERR_NONE)
    {
        t->used = 0;
        return err;
    }
    return OS_ERR_NONE;
}
References _alloc_trampoline(), _notify_trampoline(), _trampoline_pool, _TRAMPOLINE_POOL_SIZE, OS_ERR_MEM_OF, OS_ERR_NONE, OS_ERR_OP, request_irq(), and _notify_trampoline_t::used.