FreeRTOS-OS: irq_chip_nvic.c File Reference
irq_chip_nvic.c File Reference
NVIC-backed irq_chip implementation for ARM Cortex-M (STM32)
#include <board/mcu_config.h>
#include <device.h>
#include <drivers/hal/stm32/irq_chip_nvic.h>
Functions
void irq_chip_nvic_bind_hwirq (irq_id_t irq, int32_t irqn, uint32_t priority)
Bind logical IRQ to NVIC hardware interrupt.
struct irq_chip * irq_chip_nvic_get (void)
Retrieve NVIC irq_chip instance.
static void nvic_irq_ack (struct irq_data *data)
Acknowledge IRQ.
static void nvic_irq_disable (struct irq_data *data)
Disable IRQ line.
static void nvic_irq_enable (struct irq_data *data)
Enable IRQ line.
static void nvic_irq_eoi (struct irq_data *data)
End Of Interrupt (EOI)
static void nvic_irq_mask (struct irq_data *data)
Mask IRQ (disable delivery)
static void nvic_irq_set_affinity (struct irq_data *data, uint32_t priority)
Set IRQ priority.
static int nvic_irq_set_type (struct irq_data *data, unsigned int flow_type)
Configure IRQ trigger type.
static void nvic_irq_unmask (struct irq_data *data)
Unmask IRQ (enable delivery)
Variables
static struct irq_chip _nvic_chip
NVIC irq_chip singleton.
Detailed Description
NVIC-backed irq_chip implementation for ARM Cortex-M (STM32)
Author
Subhajit Roy (subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
This module implements the generic IRQ controller abstraction (struct irq_chip) using the ARM Cortex-M NVIC hardware.
It provides a translation layer between:
Generic IRQ subsystem (irq_desc / irq_data)
STM32 HAL NVIC APIs
This allows upper layers to remain platform-independent while delegating interrupt control to the NVIC.
IRQ Execution Flow
Typical interrupt handling path:
Vector Table → ISR (startup.s)
    → HAL IRQ Handler
        → Generic IRQ Dispatcher
            → irq_chip callbacks (this file)
NVIC Hardware Constraints
No explicit ACK mechanism
No End-Of-Interrupt (EOI) signaling required
Interrupt trigger type is fixed (peripheral-defined)
Masking == disabling at NVIC level
Priority-based preemption supported
Note
Compiled only when CONFIG_DEVICE_VARIANT == MCU_VAR_STM
Definition in file irq_chip_nvic.c.
Function Documentation
irq_chip_nvic_bind_hwirq()
void irq_chip_nvic_bind_hwirq (irq_id_t irq, int32_t irqn, uint32_t priority)
Bind logical IRQ to NVIC hardware interrupt.
Parameters
irq Logical IRQ ID
irqn NVIC IRQ number
priority Interrupt priority
Associates a generic IRQ descriptor with a physical NVIC line and initializes its priority.
Precondition
irq must map to a valid irq_desc
Definition at line 225 of file irq_chip_nvic.c.
{
    struct irq_desc *desc = irq_to_desc(irq);
    if (desc == NULL)
        return;
    desc->irq_data.hwirq = irqn;
    HAL_NVIC_SetPriority((IRQn_Type)irqn, priority, 0);
}
References irq_data::hwirq, irq_desc::irq_data, and irq_to_desc().
irq_chip_nvic_get()
struct irq_chip * irq_chip_nvic_get (void)
Retrieve NVIC irq_chip instance.
Returns
Pointer to static irq_chip instance
Definition at line 203 of file irq_chip_nvic.c.
{
    return &_nvic_chip;
}
References _nvic_chip.
nvic_irq_ack()
static void nvic_irq_ack (struct irq_data * data) static
Acknowledge IRQ.
NVIC does not require explicit acknowledgment. Interrupt flags must be cleared at the peripheral level before returning from ISR.
Parameters
data IRQ descriptor data
Definition at line 121 of file irq_chip_nvic.c.
{
    (void)data;
}
nvic_irq_disable()
static void nvic_irq_disable (struct irq_data * data) static
Disable IRQ line.
Parameters
data IRQ descriptor data
Definition at line 81 of file irq_chip_nvic.c.
{
    if (data == NULL || data->hwirq < 0)
        return;
    HAL_NVIC_DisableIRQ((IRQn_Type)data->hwirq);
}
References irq_data::hwirq.
nvic_irq_enable()
static void nvic_irq_enable (struct irq_data * data) static
Enable IRQ line.
Parameters
data IRQ descriptor data (must be valid)
Note
No effect if data is NULL or hwirq is invalid.
Definition at line 68 of file irq_chip_nvic.c.
{
    if (data == NULL || data->hwirq < 0)
        return;
    HAL_NVIC_EnableIRQ((IRQn_Type)data->hwirq);
}
References irq_data::hwirq.
nvic_irq_eoi()
static void nvic_irq_eoi (struct irq_data * data) static
End Of Interrupt (EOI)
Cortex-M automatically completes interrupt handling on ISR exit.
Parameters
data IRQ descriptor data
Definition at line 134 of file irq_chip_nvic.c.
{
    (void)data;
}
nvic_irq_mask()
static void nvic_irq_mask (struct irq_data * data) static
Mask IRQ (disable delivery)
On Cortex-M, masking is implemented by disabling the NVIC line.
Parameters
data IRQ descriptor data
Definition at line 97 of file irq_chip_nvic.c.
{
    nvic_irq_disable(data);
}
References nvic_irq_disable().
nvic_irq_set_affinity()
static void nvic_irq_set_affinity (struct irq_data * data, uint32_t priority) static
Set IRQ priority.
Parameters
data IRQ descriptor data
priority Preemption priority (implementation-defined range)
Warning
Priority encoding depends on NVIC configuration (PRIGROUP).
Definition at line 148 of file irq_chip_nvic.c.
{
    if (data == NULL || data->hwirq < 0)
        return;
    HAL_NVIC_SetPriority((IRQn_Type)data->hwirq, priority, 0);
}
References irq_data::hwirq.
nvic_irq_set_type()
static int nvic_irq_set_type (struct irq_data * data, unsigned int flow_type) static
Configure IRQ trigger type.
Not supported on NVIC. Trigger behavior is fixed by hardware.
Parameters
data IRQ descriptor data
flow_type Requested trigger type (ignored)
Return values
0 Always succeeds
Definition at line 167 of file irq_chip_nvic.c.
{
    (void)data;
    (void)flow_type;
    return 0;
}
nvic_irq_unmask()
static void nvic_irq_unmask (struct irq_data * data) static
Unmask IRQ (enable delivery)
Parameters
data IRQ descriptor data
Definition at line 107 of file irq_chip_nvic.c.
{
    nvic_irq_enable(data);
}
References nvic_irq_enable().
Variable Documentation
_nvic_chip
struct irq_chip _nvic_chip static
Initial value:
= {
    .name             = "NVIC",
    .irq_enable       = nvic_irq_enable,
    .irq_disable      = nvic_irq_disable,
    .irq_ack          = nvic_irq_ack,
    .irq_mask         = nvic_irq_mask,
    .irq_mask_ack     = NULL,
    .irq_unmask       = nvic_irq_unmask,
    .irq_eoi          = nvic_irq_eoi,
    .irq_retrigger    = NULL,
    .irq_set_type     = nvic_irq_set_type,
    .irq_set_affinity = nvic_irq_set_affinity,
    .flags            = 0,
}
NVIC irq_chip singleton.
Provides the concrete implementation of the generic irq_chip interface.
Definition at line 183 of file irq_chip_nvic.c.
{
    .name             = "NVIC",
    .irq_enable       = nvic_irq_enable,
    .irq_disable      = nvic_irq_disable,
    .irq_ack          = nvic_irq_ack,
    .irq_mask         = nvic_irq_mask,
    .irq_mask_ack     = NULL,   /**< Separate mask + ack */
    .irq_unmask       = nvic_irq_unmask,
    .irq_eoi          = nvic_irq_eoi,
    .irq_retrigger    = NULL,
    .irq_set_type     = nvic_irq_set_type,
    .irq_set_affinity = nvic_irq_set_affinity,
    .flags            = 0,
};