FreeRTOS-OS: irq_desc.h File Reference
irq_desc.h File Reference
#include <def_std.h>
#include <FreeRTOS.h>
#include <irq/irq_notify.h>
#include <mm/list.h>
Classes
struct irq_chip
struct irq_common_data
struct irq_data
struct irq_desc
struct irqaction
Macros
#define IRQ_HANDLED 1 /* handler serviced this IRQ */
#define IRQ_NONE 0 /* handler did not service this IRQ */
Typedefs
typedef void(* irq_flow_handler_t) (struct irq_desc *desc, void *data, BaseType_t *pxHPT)
typedef irqreturn_t(* irq_handler_t) (irq_id_t irq, void *data, void *dev_id, BaseType_t *pxHPT)
typedef int irqreturn_t
Functions
void __do_IRQ (irq_id_t irq, void *data)
void __do_IRQ_from_isr (irq_id_t irq, void *data, BaseType_t *pxHPT)
void free_irq (irq_id_t irq, void *dev_id)
void handle_edge_irq (struct irq_desc *desc, void *data, BaseType_t *pxHPT)
void handle_irq_event (struct irq_desc *desc, void *data, BaseType_t *pxHPT)
void handle_level_irq (struct irq_desc *desc, void *data, BaseType_t *pxHPT)
void handle_simple_irq (struct irq_desc *desc, void *data, BaseType_t *pxHPT)
void irq_desc_init_all (void)
void irq_disable (irq_id_t irq)
void irq_enable (irq_id_t irq)
void irq_set_chip (irq_id_t irq, struct irq_chip *chip)
void irq_set_chip_and_handler (irq_id_t irq, struct irq_chip *chip, irq_flow_handler_t handle)
void irq_set_handler (irq_id_t irq, irq_flow_handler_t handle)
struct irq_desc * irq_to_desc (irq_id_t irq)
int request_irq (irq_id_t irq, irq_handler_t handler, const char *name, void *dev_id)
Macro Definition Documentation
IRQ_HANDLED
#define IRQ_HANDLED 1 /* handler serviced this IRQ */
Definition at line 44 of file irq_desc.h.
IRQ_NONE
#define IRQ_NONE 0 /* handler did not service this IRQ */
Definition at line 43 of file irq_desc.h.
Typedef Documentation
irq_flow_handler_t
typedef void(* irq_flow_handler_t) (struct irq_desc *desc, void *data, BaseType_t *pxHPT)
Definition at line 117 of file irq_desc.h.
irq_handler_t
typedef irqreturn_t(* irq_handler_t) (irq_id_t irq, void *data, void *dev_id, BaseType_t *pxHPT)
Parameters
irq Software IRQ ID that fired.
data Event payload (e.g. pointer to received byte, error code).
dev_id Opaque context supplied to request_irq().
pxHPT FreeRTOS yield accumulator; pass to portYIELD_FROM_ISR() after the dispatch chain returns. NULL in task context.
Returns
IRQ_HANDLED or IRQ_NONE.
Definition at line 101 of file irq_desc.h.
irqreturn_t
typedef int irqreturn_t
Definition at line 46 of file irq_desc.h.
Function Documentation
__do_IRQ()
void __do_IRQ (irq_id_t irq, void * data)
__do_IRQ — task-context variant (pxHPT = NULL).
Definition at line 148 of file irq_desc.c.
{
    struct irq_desc *desc = irq_to_desc(irq);
    if (desc == NULL)
        return;
    desc->irq_count++;
    desc->tot_count++;
    if (desc->depth > 0)
    {
        desc->irqs_unhandled++;
        return;
    }
    if (desc->handle_irq != NULL)
        desc->handle_irq(desc, data, NULL);
}
References irq_desc::depth, irq_desc::handle_irq, irq_desc::irq_count, irq_to_desc(), irq_desc::irqs_unhandled, and irq_desc::tot_count.
__do_IRQ_from_isr()
void __do_IRQ_from_isr (irq_id_t irq, void * data, BaseType_t * pxHPT)
__do_IRQ_from_isr — called from HAL ISR handlers. Increments irq_count, calls desc->handle_irq(). portYIELD_FROM_ISR(*pxHPT) must be called by the caller after return.
Definition at line 129 of file irq_desc.c.
{
    struct irq_desc *desc = irq_to_desc(irq);
    if (desc == NULL)
        return;
    desc->irq_count++;
    desc->tot_count++;
    if (desc->depth > 0)
    {
        desc->irqs_unhandled++;
        return;
    }
    if (desc->handle_irq != NULL)
        desc->handle_irq(desc, data, pxHPT);
}
References irq_desc::depth, irq_desc::handle_irq, irq_desc::irq_count, irq_to_desc(), irq_desc::irqs_unhandled, and irq_desc::tot_count.
free_irq()
void free_irq (irq_id_t irq, void * dev_id)
free_irq — remove the handler registered with @dev_id from the chain.
Definition at line 190 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL)
        return;
    struct irq_desc  *desc = &_irq_desc_table[irq];
    struct irqaction *cur;
    list_for_each_entry(cur, &desc->action_list, node)
    {
        if (cur->dev_id == dev_id)
        {
            list_delete(&cur->node);
            _free_action(cur);
            return;
        }
    }
}
References _free_action(), _irq_desc_table, irq_desc::action_list, irqaction::dev_id, list_delete(), list_for_each_entry, and irqaction::node.
handle_edge_irq()
void handle_edge_irq (struct irq_desc * desc, void * data, BaseType_t * pxHPT)
handle_edge_irq — ack chip (clears pending), then walk action chain. Used for GPIO EXTI and peripherals with edge-mode.
Definition at line 91 of file irq_desc.c.
{
    if (desc == NULL)
        return;
    struct irq_chip *chip = desc->irq_data.chip;
    if (chip != NULL && chip->irq_ack != NULL)
        chip->irq_ack(&desc->irq_data);
    handle_irq_event(desc, data, pxHPT);
}
References irq_data::chip, handle_irq_event(), irq_chip::irq_ack, and irq_desc::irq_data.
handle_irq_event()
void handle_irq_event (struct irq_desc * desc, void * data, BaseType_t * pxHPT)
Definition at line 60 of file irq_desc.c.
{
    if (desc == NULL)
        return;
    struct irqaction *action;
    irqreturn_t       res = IRQ_NONE;
    list_for_each_entry(action, &desc->action_list, node)
    {
        if (action->handler != NULL)
            res |= action->handler(desc->irq_data.irq, data,
                                   action->dev_id, pxHPT);
    }
    if (res == IRQ_NONE)
    {
        desc->irqs_unhandled++;
        desc->last_unhandled = desc->irq_count; /* snapshot for debug */
    }
}
References irq_desc::action_list, irqaction::dev_id, irqaction::handler, irq_data::irq, irq_desc::irq_count, irq_desc::irq_data, IRQ_NONE, irq_desc::irqs_unhandled, irq_desc::last_unhandled, list_for_each_entry, and irqaction::node.
handle_level_irq()
void handle_level_irq (struct irq_desc * desc, void * data, BaseType_t * pxHPT)
handle_level_irq — mask → ack → walk chain → unmask. Used for level-sensitive interrupt lines.
Definition at line 104 of file irq_desc.c.
{
    if (desc == NULL)
        return;
    struct irq_chip *chip = desc->irq_data.chip;
    if (chip != NULL && chip->irq_mask_ack != NULL)
        chip->irq_mask_ack(&desc->irq_data);
    else if (chip != NULL)
    {
        if (chip->irq_mask != NULL)
            chip->irq_mask(&desc->irq_data);
        if (chip->irq_ack != NULL)
            chip->irq_ack(&desc->irq_data);
    }
    handle_irq_event(desc, data, pxHPT);
    if (chip != NULL && chip->irq_unmask != NULL)
        chip->irq_unmask(&desc->irq_data);
}
References irq_data::chip, handle_irq_event(), irq_chip::irq_ack, irq_desc::irq_data, irq_chip::irq_mask, irq_chip::irq_mask_ack, and irq_chip::irq_unmask.
handle_simple_irq()
void handle_simple_irq (struct irq_desc * desc, void * data, BaseType_t * pxHPT)
handle_simple_irq — no chip operations, just walk the action chain. Used for software IRQ IDs (UART_RX, I2C_TX_DONE, ...).
Definition at line 84 of file irq_desc.c.
{
    if (desc == NULL)
        return;
    handle_irq_event(desc, data, pxHPT);
}
References handle_irq_event().
irq_desc_init_all()
void irq_desc_init_all (void)
Definition at line 272 of file irq_desc.c.
{
    for (irq_id_t i = 0; i < IRQ_ID_TOTAL; i++)
    {
        struct irq_desc *desc = &_irq_desc_table[i];
        desc->irq_common_data.state_use_accessors = 0;
        desc->irq_common_data.handler_data        = NULL;
        desc->irq_data.irq       = i;
        desc->irq_data.hwirq     = -1;
        desc->irq_data.chip      = NULL;
        desc->irq_data.desc      = desc;
        desc->irq_data.chip_data = NULL;
        desc->handle_irq            = handle_simple_irq;
        list_init(&desc->action_list);
        desc->status_use_accessors  = 0;
        desc->depth                 = 0;
        desc->tot_count             = 0;
        desc->irq_count             = 0;
        desc->last_unhandled        = 0;
        desc->irqs_unhandled        = 0;
        desc->name                  = irq_table_get_name(i);
    }
}
References _irq_desc_table, irq_desc::action_list, irq_data::chip, irq_data::chip_data, irq_desc::depth, irq_data::desc, irq_desc::handle_irq, handle_simple_irq(), irq_common_data::handler_data, irq_data::hwirq, irq_data::irq, irq_desc::irq_common_data, irq_desc::irq_count, irq_desc::irq_data, irq_table_get_name(), irq_desc::irqs_unhandled, irq_desc::last_unhandled, list_init(), irq_desc::name, irq_common_data::state_use_accessors, irq_desc::status_use_accessors, and irq_desc::tot_count.
irq_disable()
void irq_disable (irq_id_t irq)
irq_disable / irq_enable increment / decrement the depth counter. Dispatch is skipped while depth > 0.
Definition at line 236 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL)
        return;
    struct irq_desc *desc = &_irq_desc_table[irq];
    desc->depth++;
    struct irq_chip *chip = desc->irq_data.chip;
    if (chip != NULL && chip->irq_disable != NULL)
        chip->irq_disable(&desc->irq_data);
    else if (chip != NULL && chip->irq_mask != NULL)
        chip->irq_mask(&desc->irq_data);
}
References _irq_desc_table, irq_data::chip, irq_desc::depth, irq_desc::irq_data, irq_chip::irq_disable, and irq_chip::irq_mask.
irq_enable()
void irq_enable (irq_id_t irq)
Definition at line 251 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL)
        return;
    struct irq_desc *desc = &_irq_desc_table[irq];
    if (desc->depth > 0)
        desc->depth--;
    if (desc->depth == 0)
    {
        struct irq_chip *chip = desc->irq_data.chip;
        if (chip != NULL && chip->irq_enable != NULL)
            chip->irq_enable(&desc->irq_data);
        else if (chip != NULL && chip->irq_unmask != NULL)
            chip->irq_unmask(&desc->irq_data);
    }
}
References _irq_desc_table, irq_data::chip, irq_desc::depth, irq_desc::irq_data, irq_chip::irq_enable, and irq_chip::irq_unmask.
irq_set_chip()
void irq_set_chip (irq_id_t irq, struct irq_chip * chip)
Definition at line 211 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL)
        return;
    _irq_desc_table[irq].irq_data.chip = chip;
}
References _irq_desc_table, irq_data::chip, and irq_desc::irq_data.
irq_set_chip_and_handler()
void irq_set_chip_and_handler (irq_id_t irq, struct irq_chip * chip, irq_flow_handler_t handle)
Definition at line 225 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL)
        return;
    _irq_desc_table[irq].irq_data.chip = chip;
    _irq_desc_table[irq].handle_irq    = handle;
}
References _irq_desc_table, irq_data::chip, irq_desc::handle_irq, and irq_desc::irq_data.
irq_set_handler()
void irq_set_handler (irq_id_t irq, irq_flow_handler_t handle)
Definition at line 218 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL)
        return;
    _irq_desc_table[irq].handle_irq = handle;
}
References _irq_desc_table, and irq_desc::handle_irq.
irq_to_desc()
struct irq_desc * irq_to_desc (irq_id_t irq)
O(1) lookup — returns NULL for out-of-range IRQ IDs.
Definition at line 51 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL)
        return NULL;
    return &_irq_desc_table[irq];
}
References _irq_desc_table.
request_irq()
int request_irq (irq_id_t irq, irq_handler_t handler, const char * name, void * dev_id)
request_irq — register a driver ISR for a software IRQ ID.
May be called multiple times with different dev_id values to chain handlers. Handlers are called in registration order.
Returns
0 on success, OS_ERR_OP / OS_ERR_MEM_OF on failure.
Definition at line 169 of file irq_desc.c.
{
    if (irq >= IRQ_ID_TOTAL || handler == NULL)
        return OS_ERR_OP;
    struct irq_desc *desc = &_irq_desc_table[irq];
    struct irqaction *new_action = _alloc_action();
    if (new_action == NULL)
        return OS_ERR_MEM_OF;
    new_action->handler = handler;
    new_action->dev_id  = dev_id;
    new_action->name    = name;
    list_add_tail(&new_action->node, &desc->action_list);
    return OS_ERR_NONE;
}
References _alloc_action(), _irq_desc_table, irq_desc::action_list, irqaction::dev_id, irqaction::handler, list_add_tail(), irqaction::name, irqaction::node, OS_ERR_MEM_OF, OS_ERR_NONE, and OS_ERR_OP.