FreeRTOS-OS: kernel_service_task_manager.c File Reference
kernel_service_task_manager.c File Reference
#include <os/kernel_services.h>
#include <os/kernel_task_mgr.h>
#include <os/kernel.h>
#include <FreeRTOS.h>
#include <task.h>
#include <timers.h>
Macros
#define TASK_MGR_SCAN_PERIOD_MS 5000
Functions
static void _collect_task (task_health_t *out, TaskHandle_t h, uint32_t tid)
static void _scan_heap (void)
static void _scan_tasks (void)
static void _scan_timer_task (void)
const sys_health_t * task_mgr_get_health (void)
void thread_task_mgmt (void *arg)
void vApplicationIdleHook (void)
void vApplicationMallocFailedHook (void)
void vApplicationStackOverflowHook (TaskHandle_t xTask, char *pcTaskName)
Variables
static sys_health_t _health
static volatile uint32_t _idle_tick_count = 0
static volatile uint32_t _malloc_fail_count = 0
static volatile uint32_t _stack_overflow_count = 0
Macro Definition Documentation
TASK_MGR_SCAN_PERIOD_MS
#define TASK_MGR_SCAN_PERIOD_MS 5000
Definition at line 34 of file kernel_service_task_manager.c.
Function Documentation
_collect_task()
static void _collect_task (task_health_t * out, TaskHandle_t h, uint32_t tid) static
Definition at line 48 of file kernel_service_task_manager.c.
{
    out->handle    = h;
    out->name      = pcTaskGetName(h);
    out->state     = eTaskGetState(h);
    out->stack_hwm = uxTaskGetStackHighWaterMark(h);
    out->thread_id = tid;
}
References task_health_t::handle, task_health_t::name, task_health_t::stack_hwm, task_health_t::state, and task_health_t::thread_id.
_scan_heap()
static void _scan_heap (void) static
Definition at line 96 of file kernel_service_task_manager.c.
{
    _health.heap_free          = xPortGetFreeHeapSize();
    _health.heap_min_ever_free = xPortGetMinimumEverFreeHeapSize();
}
References _health, sys_health_t::heap_free, and sys_health_t::heap_min_ever_free.
_scan_tasks()
static void _scan_tasks (void) static
Definition at line 59 of file kernel_service_task_manager.c.
{
    _health.task_count = 0;
    thread_handle_t *pos;
    list_for_each_entry(pos, os_thread_list_get(), list)
    {
        if (_health.task_count >= TASK_MGR_MAX_TASKS)
            break;
        _collect_task(&_health.tasks[_health.task_count],
                      pos->thread_handle,
                      pos->thread_id);
        _health.task_count++;
    }
}
References _collect_task(), _health, list_for_each_entry, os_thread_list_get(), sys_health_t::task_count, TASK_MGR_MAX_TASKS, sys_health_t::tasks, thread_handle_t::thread_handle, and thread_handle_t::thread_id.
_scan_timer_task()
static void _scan_timer_task (void) static
Definition at line 78 of file kernel_service_task_manager.c.
{
#if (configUSE_TIMERS == 1)
    TaskHandle_t h = xTimerGetTimerDaemonTaskHandle();
    if (h != NULL)
    {
        _collect_task(&_health.timer_task, h, 0);
        _health.timer_task_valid = 1;
    }
    else
#endif
    {
        _health.timer_task_valid = 0;
    }
}
References _collect_task(), _health, sys_health_t::timer_task, and sys_health_t::timer_task_valid.
task_mgr_get_health()
const sys_health_t * task_mgr_get_health (void)
Definition at line 104 of file kernel_service_task_manager.c.
{
    return &_health;
}
References _health.
thread_task_mgmt()
void thread_task_mgmt (void * arg)
Definition at line 145 of file kernel_service_task_manager.c.
{
    (void)arg;
    /* One-shot startup delay so all service threads have registered first */
    vTaskDelay(pdMS_TO_TICKS(TASK_MGR_SCAN_PERIOD_MS));
    while (1)
    {
        _scan_tasks();
        _scan_timer_task();
        _scan_heap();
        _health.stack_overflow_count = _stack_overflow_count;
        _health.malloc_fail_count    = _malloc_fail_count;
        vTaskDelay(pdMS_TO_TICKS(TASK_MGR_SCAN_PERIOD_MS));
    }
}
References _health, _malloc_fail_count, _scan_heap(), _scan_tasks(), _scan_timer_task(), _stack_overflow_count, sys_health_t::malloc_fail_count, sys_health_t::stack_overflow_count, and TASK_MGR_SCAN_PERIOD_MS.
vApplicationIdleHook()
void vApplicationIdleHook (void)
Definition at line 115 of file kernel_service_task_manager.c.
{
    _idle_tick_count++;
}
References _idle_tick_count.
vApplicationMallocFailedHook()
void vApplicationMallocFailedHook (void)
Definition at line 138 of file kernel_service_task_manager.c.
{
    _malloc_fail_count++;
}
References _malloc_fail_count.
vApplicationStackOverflowHook()
void vApplicationStackOverflowHook (TaskHandle_t xTask, char * pcTaskName)
Definition at line 125 of file kernel_service_task_manager.c.
{
    (void)xTask;
    (void)pcTaskName;
    _stack_overflow_count++;
    taskDISABLE_INTERRUPTS();
    for (;;) {}
}
References _stack_overflow_count.
Variable Documentation
_health
sys_health_t _health static
Definition at line 38 of file kernel_service_task_manager.c.
_idle_tick_count
volatile uint32_t _idle_tick_count = 0 static
Definition at line 44 of file kernel_service_task_manager.c.
_malloc_fail_count
volatile uint32_t _malloc_fail_count = 0 static
Definition at line 43 of file kernel_service_task_manager.c.
_stack_overflow_count
volatile uint32_t _stack_overflow_count = 0 static
Definition at line 42 of file kernel_service_task_manager.c.