FreeRTOS-OS: kernel_service_core.c File Reference
kernel_service_core.c File Reference
#include <os/kernel_services.h>
#include <os/kernel.h>
#include <services/gpio_mgmt.h>
#include <services/uart_mgmt.h>
Functions
status_t os_kernel_thread_register (void)
Function Documentation
os_kernel_thread_register()
status_t os_kernel_thread_register (void)
Definition at line 37 of file kernel_service_core.c.
{
    status_t status = OS_ERR_NONE;
    /* Task health monitor */
    if (os_thread_create(thread_task_mgmt, "task_mgr",
                         PROC_SERVICE_TASK_MGMT_STACK_SIZE,
                         PROC_SERVICE_TASK_MGMT_PRIORITY, NULL) < 0)
        status |= OS_ERR_OP;
    /* GPIO management */
    if (gpio_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#if (INC_SERVICE_UART_MGMT == 1)
    if (uart_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#endif
#if (INC_SERVICE_IIC_MGMT == 1)
    if (iic_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#endif
#if (BOARD_SPI_COUNT > 0)
    if (spi_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#endif
    /* Start interactive shell on UART_APP (USART2, PA2/PA3, /dev/ttyUSB0).
     * The shell task delays TIME_OFFSET_OS_SHELL_MGMT ms internally so it
     * waits for uart_mgmt to complete UART initialisation first. */
    os_shell_mgmt_start();
    return status;
}
References gpio_mgmt_start(), iic_mgmt_start(), OS_ERR_NONE, OS_ERR_OP, os_shell_mgmt_start(), os_thread_create(), PROC_SERVICE_TASK_MGMT_PRIORITY, PROC_SERVICE_TASK_MGMT_STACK_SIZE, spi_mgmt_start(), thread_task_mgmt(), and uart_mgmt_start().