FreeRTOS-OS: kernel_services.h File Reference
kernel_services.h File Reference
#include <def_std.h>
#include <def_err.h>
#include <conf_os.h>
#include <ipc/mqueue.h>
#include <FreeRTOS.h>
#include <task.h>
Macros
#define CONF_THREAD_IIC_MGMT_PRIORITY PROC_SERVICE_IIC_MGMT_PRIORITY
#define CONF_THREAD_IIC_MGMT_STACK_SIZE PROC_SERVICE_IIC_MGMT_STACK_SIZE
#define CONF_THREAD_UART_MGMT_PRIORITY PROC_SERVICE_SERIAL_MGMT_PRIORITY
#define CONF_THREAD_UART_MGMT_STACK_SIZE PROC_SERVICE_SERIAL_MGMT_STACK_SIZE
Functions
status_t os_kernel_thread_register (void)
void therad_iic_mgmt (void *arg)
void thread_task_mgmt (void *arg)
void thread_uart_mgmt (void *arg)
Macro Definition Documentation
CONF_THREAD_IIC_MGMT_PRIORITY
#define CONF_THREAD_IIC_MGMT_PRIORITY PROC_SERVICE_IIC_MGMT_PRIORITY
Definition at line 33 of file kernel_services.h.
CONF_THREAD_IIC_MGMT_STACK_SIZE
#define CONF_THREAD_IIC_MGMT_STACK_SIZE PROC_SERVICE_IIC_MGMT_STACK_SIZE
Definition at line 32 of file kernel_services.h.
CONF_THREAD_UART_MGMT_PRIORITY
#define CONF_THREAD_UART_MGMT_PRIORITY PROC_SERVICE_SERIAL_MGMT_PRIORITY
Definition at line 31 of file kernel_services.h.
CONF_THREAD_UART_MGMT_STACK_SIZE
#define CONF_THREAD_UART_MGMT_STACK_SIZE PROC_SERVICE_SERIAL_MGMT_STACK_SIZE
Definition at line 30 of file kernel_services.h.
Function Documentation
os_kernel_thread_register()
status_t os_kernel_thread_register (void)
Definition at line 37 of file kernel_service_core.c.
{
    status_t status = OS_ERR_NONE;
    /* Task health monitor */
    if (os_thread_create(thread_task_mgmt, "task_mgr",
                         PROC_SERVICE_TASK_MGMT_STACK_SIZE,
                         PROC_SERVICE_TASK_MGMT_PRIORITY, NULL) < 0)
        status |= OS_ERR_OP;
    /* GPIO management */
    if (gpio_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#if (INC_SERVICE_UART_MGMT == 1)
    if (uart_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#endif
#if (INC_SERVICE_IIC_MGMT == 1)
    if (iic_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#endif
#if (BOARD_SPI_COUNT > 0)
    if (spi_mgmt_start() != OS_ERR_NONE)
        status |= OS_ERR_OP;
#endif
    /* Start interactive shell on UART_APP (USART2, PA2/PA3, /dev/ttyUSB0).
     * The shell task delays TIME_OFFSET_OS_SHELL_MGMT ms internally so it
     * waits for uart_mgmt to complete UART initialisation first. */
    os_shell_mgmt_start();
    return status;
}
References gpio_mgmt_start(), iic_mgmt_start(), OS_ERR_NONE, OS_ERR_OP, os_shell_mgmt_start(), os_thread_create(), PROC_SERVICE_TASK_MGMT_PRIORITY, PROC_SERVICE_TASK_MGMT_STACK_SIZE, spi_mgmt_start(), thread_task_mgmt(), and uart_mgmt_start().
therad_iic_mgmt()
void therad_iic_mgmt (void * arg)
thread_task_mgmt()
void thread_task_mgmt (void * arg)
Definition at line 145 of file kernel_service_task_manager.c.
{
    (void)arg;
    /* One-shot startup delay so all service threads have registered first */
    vTaskDelay(pdMS_TO_TICKS(TASK_MGR_SCAN_PERIOD_MS));
    while (1)
    {
        _scan_tasks();
        _scan_timer_task();
        _scan_heap();
        _health.stack_overflow_count = _stack_overflow_count;
        _health.malloc_fail_count    = _malloc_fail_count;
        vTaskDelay(pdMS_TO_TICKS(TASK_MGR_SCAN_PERIOD_MS));
    }
}
References _health, _malloc_fail_count, _scan_heap(), _scan_tasks(), _scan_timer_task(), _stack_overflow_count, sys_health_t::malloc_fail_count, sys_health_t::stack_overflow_count, and TASK_MGR_SCAN_PERIOD_MS.
thread_uart_mgmt()
void thread_uart_mgmt (void * arg)