FreeRTOS-OS: kernel_thread.c File Reference
kernel_thread.c File Reference
All kernel thread operation api definition.
#include <os/kernel.h>
Functions
int32_t __attribute__ ((section(".os")))
A generic thread create api.
int32_t os_thread_count_get (void)
Return the number of threads created since boot (monotonic counter).
struct list_node * os_thread_list_get (void)
Return the head sentinel of the intrusive thread list.
Variables
static int32_t thread_counter = 0
Monotonically increasing counter used as thread IDs.
struct list_node thread_list = { &(thread_list), &(thread_list) }
This section contains all the static varibles used in this file.
Detailed Description
All kernel thread operation api definition.
Author
Subhajit Roy (subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Thread create delete resume pause delay
Date
2025-09-26
Note
This file is part of FreeRTOS-OS Project.
FreeRTOS-OS is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
FreeRTOS-OS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with FreeRTOS-KERNEL. If not, see https://www.gnu.org/licenses/.
Definition in file kernel_thread.c.
Function Documentation
__attribute__()
__attribute__ ((section(".os")))
A generic thread create api.
Resume a previously suspended thread by its ID.
Suspend an arbitrary thread by its ID.
Suspend the calling thread indefinitely.
Block the calling thread for ms milliseconds.
Delete a thread by ID and free its resources.
Note
Creates a dynamic FreeRTOS task and inserts the new thread_handle_t into the intrusive doubly-circular thread_list using list_add_tail(), mirroring the Linux kernel task list.
Parameters
thread_func Thread entry function pointer.
thread_name Name string for debugging.
thread_stack_depth Stack size in words.
priority Scheduling priority (0 = idle).
thread_parameter Opaque pointer forwarded to the thread.
Returns
Positive thread_id on success, negative OS_ERR_* on failure.
Note
Walks the intrusive list with list_for_each_entry(), calls vTaskDelete(), unlinks via list_delete(), then frees.
Parameters
thread_id ID returned by os_thread_create().
Returns
OS_ERR_NONE on success, OS_ERR_OP if the ID is not found.
Note
Equivalent to vTaskSuspend(NULL) — the thread must be resumed externally via os_resume_thread().
Walks the intrusive thread list to locate the handle then calls vTaskSuspend(), mirroring how the Linux kernel iterates task_struct via the tasks list.
Parameters
thread_id ID returned by os_thread_create().
Note
Walks the intrusive thread list and calls vTaskResume().
Parameters
thread_id ID returned by os_thread_create().
Definition at line 61 of file kernel_thread.c.
{
    if( (thread_func != NULL) && (thread_stack_depth != 0) )
    {
        thread_handle_t* handle = (thread_handle_t *) kmaloc(sizeof(thread_handle_t));
        if(handle != NULL)
        {
            handle->init_parameter  = thread_parameter;
            handle->priority        = priority;
            BaseType_t returned = xTaskCreate(thread_func,
                                            thread_name,
                                            thread_stack_depth,
                                            thread_parameter,
                                            (UBaseType_t)priority,
                                            &handle->thread_handle);
            if(returned == pdTRUE)
            {
                thread_counter++;
                handle->thread_id = thread_counter;
            }
            else
            {
                kfree(handle);
                return OS_ERR_OP;
            }
            /* Append to the tail of the thread list (Linux task_list style) */
            list_add_tail(&handle->list, &thread_list);
            return handle->thread_id;
        }
        else
        {
            return OS_ERR_MEM_OP;
        }
    }
    else
    {
        return OS_ERR_OP;
    }
}
References thread_handle_t::init_parameter, kfree(), kmaloc(), thread_handle_t::list, list_add_tail(), OS_ERR_MEM_OP, OS_ERR_OP, thread_handle_t::priority, thread_counter, thread_handle_t::thread_handle, thread_handle_t::thread_id, and thread_list.
Variable Documentation
thread_counter
int32_t thread_counter = 0 static
Monotonically increasing counter used as thread IDs.
Note
Starts at 0; first created thread receives ID 1.
Definition at line 46 of file kernel_thread.c.
thread_list
struct list_node thread_list = { &(thread_list), &(thread_list) }
This section contains all the static varibles used in this file.
variables declaration
Sentinel list node for the doubly-circular thread list.
Note
Follows the Linux kernel intrusive list pattern: thread_handle_t embeds a struct list_node so no separate pointer bookkeeping is needed. An empty list has thread_list.next == thread_list.prev == &thread_list.
Definition at line 40 of file kernel_thread.c.