FreeRTOS-OS: kernel_syscall.h File Reference
kernel_syscall.h File Reference
#include <def_std.h>
#include <conf_os.h>
#include <ipc/ringbuffer.h>
#include <drivers/timer/drv_time.h>
#include <ipc/global_var.h>
#include <FreeRTOS.h>
#include <atomic.h>
#include <stdarg.h>
Functions
int32_t printk (const char *fmt,...)
void printk_disable (void)
void printk_enable (void)
void printk_init (void)
Function Documentation
printk()
int32_t printk (const char * fmt, ...)
Definition at line 149 of file syscalls.c.
{
#if (NO_OF_UART > 0)
    if (!_printk_enabled)
        return 0;
    va_list args;
    int     ts_len, msg_len, i;
    va_start(args, fmt);
    ATOMIC_ENTER_CRITICAL();
    ts_len = snprintf(_time_buf, sizeof(_time_buf), "[%lu] ",
                      (unsigned long)drv_time_get_ticks());
    for (i = 0; i < ts_len; i++)
        if (_printk_rb) ringbuffer_putchar(_printk_rb, (uint8_t)_time_buf[i]);
    msg_len = vsnprintf(_msg_buf, sizeof(_msg_buf), fmt, args);
    if (msg_len > 0)
        for (i = 0; i < msg_len; i++)
            if (_printk_rb) ringbuffer_putchar(_printk_rb, (uint8_t)_msg_buf[i]);
    ATOMIC_EXIT_CRITICAL();
    va_end(args);
    drv_uart_tx_kick(COMM_PRINTK_HW_ID);
    return msg_len;
#else
    (void)fmt;
    return 0;
#endif
}
References _msg_buf, _printk_enabled, _printk_rb, _time_buf, COMM_PRINTK_HW_ID, drv_time_get_ticks(), drv_uart_tx_kick(), and ringbuffer_putchar().
printk_disable()
void printk_disable (void)
Definition at line 39 of file syscalls.c.
{ _printk_enabled = 0; }
References _printk_enabled.
printk_enable()
void printk_enable (void)
Definition at line 38 of file syscalls.c.
{ _printk_enabled = 1; }
References _printk_enabled.
printk_init()
void printk_init (void)
Definition at line 138 of file syscalls.c.
{
#ifdef COMM_PRINTK_HW_ID
    if (COMM_PRINTK_HW_ID < NO_OF_UART)
        _printk_rb = (struct ringbuffer *)
                     ipc_mqueue_get_handle(global_uart_tx_mqueue_list[COMM_PRINTK_HW_ID]);
#else
#  error "printk: COMM_PRINTK_HW_ID not defined — set it in conf_os.h"
#endif
}
References _printk_rb, COMM_PRINTK_HW_ID, global_uart_tx_mqueue_list, and ipc_mqueue_get_handle().