FreeRTOS-OS: fsm.h File Reference
fsm.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include "fsm_config.h"
Classes
struct fsm_ctx
Runtime context of one FSM instance.
struct fsm_event
FSM event object.
struct fsm_state
A single state in the FSM / HSM.
struct fsm_transition_t
One row of the transition table.
Macros
#define FSM_ERR_ALLOC (-2)
#define FSM_ERR_NULL (-1)
#define FSM_OK (0)
#define LIB_FSM_FSM_H_
Typedefs
typedef void(* fsm_action_fn) (const fsm_event_t *event, struct fsm_ctx *fsm)
Transition action callback.
typedef struct fsm_ctx fsm_ctx_t
Runtime context of one FSM instance.
typedef uint32_t fsm_event_id_t
Event identifier — define your own enum and cast to this.
typedef struct fsm_event fsm_event_t
FSM event object.
typedef void(* fsm_lock_fn) (void)
Lock / unlock hook for queue protection.
typedef void(* fsm_state_fn) (struct fsm_state *state, struct fsm_ctx *fsm)
State entry / exit callback.
typedef struct fsm_state fsm_state_t
A single state in the FSM / HSM.
typedef void(* fsm_unlock_fn) (void)
Functions
│ │ │ │ │ │ │ │ │ fsm_dispatch (fsm, EVT_START, NULL)
int fsm_dispatch (fsm_ctx_t *fsm, fsm_event_id_t id, void *data)
Post an event from task / thread context.
│ │ │ │ │ │ fsm_dispatch_from_isr (fsm, EVT_DONE, NULL)
int fsm_dispatch_from_isr (fsm_ctx_t *fsm, fsm_event_id_t id, void *data)
Post an event from an ISR.
int fsm_init (fsm_ctx_t *fsm, fsm_state_t *initial, const fsm_transition_t *table, size_t table_len, void *user_data)
Initialise an FSM instance.
│ │ fsm_run (fsm)
void fsm_run (fsm_ctx_t *fsm)
Process all pending events — call this in your task loop.
void fsm_stop (fsm_ctx_t *fsm)
Signal the FSM to stop after the current event finishes.
│ └──────────────────────────────────────────────────────────────┘ This file is part of FreeRTOS OS Project FreeRTOS OS is free either version of the or (at your option) any later version. */struct fsm_state
Variables
│ └──────────────────────────────────────────────────────────────┘ This file is part of FreeRTOS OS Project FreeRTOS OS is free either version of the License
│ └──────────────────────────────────────────────────────────────┘ This file is part of FreeRTOS OS Project FreeRTOS OS is free software
Macro Definition Documentation
FSM_ERR_ALLOC
#define FSM_ERR_ALLOC (-2)
malloc returned NULL
Definition at line 67 of file lib/fsm/fsm.h.
FSM_ERR_NULL
#define FSM_ERR_NULL (-1)
NULL pointer passed
Definition at line 66 of file lib/fsm/fsm.h.
FSM_OK
#define FSM_OK (0)
Definition at line 65 of file lib/fsm/fsm.h.
LIB_FSM_FSM_H_
#define LIB_FSM_FSM_H_
Typedef Documentation
fsm_action_fn
typedef void(* fsm_action_fn) (const fsm_event_t *event, struct fsm_ctx *fsm)
Transition action callback.
Executed between the exit handler(s) of the source state and the entry handler(s) of the target state.
Parameters
event Triggering event (read-only during action).
fsm FSM context — access application data via fsm->user_data.
Definition at line 107 of file lib/fsm/fsm.h.
fsm_ctx_t
typedef struct fsm_ctx fsm_ctx_t
Runtime context of one FSM instance.
Embed one per logical state machine; may be static or heap-allocated. Initialise with fsm_init() before use.
fsm_event_id_t
typedef uint32_t fsm_event_id_t
Event identifier — define your own enum and cast to this.
Definition at line 75 of file lib/fsm/fsm.h.
fsm_event_t
typedef struct fsm_event fsm_event_t
FSM event object.
Allocated on the heap by fsm_dispatch() / fsm_dispatch_from_isr() and automatically freed by fsm_run() after the transition completes.
'data' is a pointer to caller-managed storage; the FSM never touches or frees it.
fsm_lock_fn
typedef void(* fsm_lock_fn) (void)
Lock / unlock hook for queue protection.
Provide platform-specific implementations when FSM_THREAD_SAFE == 1.
Examples: Bare-metal ISR-safe: __disable_irq() / __enable_irq() FreeRTOS task: xSemaphoreTake / xSemaphoreGive FreeRTOS task+ISR: taskENTER_CRITICAL / taskEXIT_CRITICAL CMSIS-RTOS: osMutexAcquire / osMutexRelease
Definition at line 130 of file lib/fsm/fsm.h.
fsm_state_fn
typedef void(* fsm_state_fn) (struct fsm_state *state, struct fsm_ctx *fsm)
State entry / exit callback.
Parameters
state The state being entered or exited.
fsm FSM context.
Definition at line 116 of file lib/fsm/fsm.h.
fsm_state_t
typedef struct fsm_state fsm_state_t
A single state in the FSM / HSM.
Set 'parent' to enable hierarchical (nested) states — the FSM will automatically call exit/entry handlers in the correct top-down order.
Static initialiser example:
static fsm_state_t st_idle = {
    .id       = ST_IDLE,
    .parent   = NULL,
    .on_entry = idle_entry,
    .on_exit  = NULL,
};
fsm_unlock_fn
typedef void(* fsm_unlock_fn) (void)
Definition at line 131 of file lib/fsm/fsm.h.
Function Documentation
fsm_dispatch() [1/2]
│ │ │ │ │ │ │ │ │ fsm_dispatch (fsm , EVT_START , NULL)
fsm_dispatch() [2/2]
int fsm_dispatch (fsm_ctx_t * fsm, fsm_event_id_t id, void * data)
Post an event from task / thread context.
Allocates an event on the heap and appends it to the internal queue. The event is freed automatically by fsm_run() after processing.
Parameters
fsm FSM context.
id Event identifier.
data Optional payload pointer (caller manages lifetime).
Returns
FSM_OK, FSM_ERR_NULL, or FSM_ERR_ALLOC.
< NULL pointer passed
< malloc returned NULL
Definition at line 277 of file fsm.c.
{
    if (fsm == NULL)
    {
        return FSM_ERR_NULL;
    }
    fsm_event_t *e = fsm_event_alloc(id, data);
    if (e == NULL)
    {
        return FSM_ERR_ALLOC;
    }
    FSM_LOCK(fsm);
    queue_push(fsm, e);
    FSM_UNLOCK(fsm);
    return FSM_OK;
}
References FSM_ERR_ALLOC, FSM_ERR_NULL, fsm_event_alloc(), FSM_LOCK, FSM_OK, FSM_UNLOCK, and queue_push().
fsm_dispatch_from_isr() [1/2]
│ │ │ │ │ │ fsm_dispatch_from_isr (fsm , EVT_DONE , NULL)
fsm_dispatch_from_isr() [2/2]
int fsm_dispatch_from_isr (fsm_ctx_t * fsm, fsm_event_id_t id, void * data)
Post an event from an ISR.
Identical to fsm_dispatch() but uses the ISR lock/unlock hooks instead of the task hooks.
Note
malloc() is called internally. Ensure your heap allocator is interrupt-safe (e.g. FreeRTOS heap_4 with configUSE_NEWLIB_REENTRANT or a custom ISR-safe allocator). Alternatively call from a deferred interrupt task.
Parameters
fsm FSM context.
id Event identifier.
data Optional payload pointer.
Returns
FSM_OK, FSM_ERR_NULL, or FSM_ERR_ALLOC.
< NULL pointer passed
< malloc returned NULL
Definition at line 299 of file fsm.c.
{
    if (fsm == NULL)
    {
        return FSM_ERR_NULL;
    }
    fsm_event_t *e = fsm_event_alloc(id, data);
    if (e == NULL)
    {
        return FSM_ERR_ALLOC;
    }
    FSM_LOCK_ISR(fsm);
    queue_push(fsm, e);
    FSM_UNLOCK_ISR(fsm);
    return FSM_OK;
}
References FSM_ERR_ALLOC, FSM_ERR_NULL, fsm_event_alloc(), FSM_LOCK_ISR, FSM_OK, FSM_UNLOCK_ISR, and queue_push().
fsm_init()
int fsm_init (fsm_ctx_t * fsm, fsm_state_t * initial, const fsm_transition_t * table, size_t table_len, void * user_data)
Initialise an FSM instance.
Clears the internal queue, sets the initial state, and fires its on_entry handler.
Parameters
fsm FSM context (caller-allocated; may be static).
initial First active state.
table Transition table array (may be const / ROM).
table_len Number of rows in 'table'.
user_data Arbitrary context passed to every callback.
Returns
FSM_OK or FSM_ERR_NULL.
< NULL pointer passed
Definition at line 212 of file fsm.c.
{
    if (fsm == NULL || initial == NULL || table == NULL)
    {
        return FSM_ERR_NULL;
    }
    fsm->current    = initial;
    fsm->table      = table;
    fsm->table_len  = table_len;
    fsm->user_data  = user_data;
    fsm->queue_head = NULL;
    fsm->queue_tail = NULL;
    fsm->running    = 1;
#if (FSM_THREAD_SAFE == 1)
    fsm->lock        = NULL;
    fsm->unlock      = NULL;
    fsm->lock_isr    = NULL;
    fsm->unlock_isr  = NULL;
#endif
    /* Fire entry handler of the initial state */
    if (initial->on_entry != NULL)
    {
        initial->on_entry(initial, fsm);
    }
    return FSM_OK;
}
References fsm_ctx::current, FSM_ERR_NULL, FSM_OK, fsm_state::on_entry, fsm_ctx::queue_head, fsm_ctx::queue_tail, fsm_ctx::running, fsm_ctx::table, fsm_ctx::table_len, and fsm_ctx::user_data.
fsm_run() [1/2]
│ │ fsm_run (fsm)
fsm_run() [2/2]
void fsm_run (fsm_ctx_t * fsm)
Process all pending events — call this in your task loop.
Drains the internal queue: for each event it finds the matching transition, runs exit → action → entry handlers, updates the active state, and frees the event. Returns when the queue is empty.
Events with no matching transition for the current state are silently discarded.
Typical patterns:
// Bare-metal super-loop
for (;;) { fsm_run(&fsm); }
// RTOS task — unblock via semaphore/notification, then drain
for (;;) {
    ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
    fsm_run(&fsm);
}
Parameters
fsm FSM context.
Definition at line 321 of file fsm.c.
{
    if (fsm == NULL || fsm->running == 0)
    {
        return;
    }
    fsm_event_t *event;
    /* Drain the entire queue before returning */
    for (;;)
    {
        /* Pop under lock to avoid race with concurrent dispatch */
        FSM_LOCK(fsm);
        event = queue_pop(fsm);
        FSM_UNLOCK(fsm);
        if (event == NULL)
        {
            break;  /* Queue empty — done for this cycle */
        }
        /* Search transition table for (current_state, event_id) */
        for (size_t i = 0U; i < fsm->table_len; ++i)
        {
            if (fsm->table[i].from  == fsm->current &&
                fsm->table[i].event == event->id)
            {
                fsm_state_t *target = fsm->table[i].to;
                /* Find LCA for correct HSM entry/exit ordering */
                fsm_state_t *lca = fsm_lca(fsm->current, target);
                /* 1. Exit current state up to (not including) LCA */
                fsm_exit_up_to(fsm, lca);
                /* 2. Execute transition action */
                if (fsm->table[i].action != NULL)
                {
                    fsm->table[i].action(event, fsm);
                }
                /* 3. Enter target state down from LCA */
                fsm_enter_down_from(fsm, lca, target);
                /* 4. Commit new state */
                fsm->current = target;
                break;
            }
        }
        /* Events with no matching transition are silently discarded */
        free(event);
    }
}
References fsm_transition_t::action, fsm_ctx::current, fsm_transition_t::event, fsm_transition_t::from, fsm_enter_down_from(), fsm_exit_up_to(), fsm_lca(), FSM_LOCK, FSM_UNLOCK, fsm_event::id, queue_pop(), fsm_ctx::running, fsm_ctx::table, fsm_ctx::table_len, and fsm_transition_t::to.
fsm_stop()
void fsm_stop (fsm_ctx_t * fsm)
Signal the FSM to stop after the current event finishes.
Sets fsm->running = 0. fsm_run() will return immediately on the next call.
Parameters
fsm FSM context.
Definition at line 268 of file fsm.c.
{
    if (fsm != NULL)
    {
        fsm->running = 0;
    }
}
References fsm_ctx::running.
or()
│ └──────────────────────────────────────────────────────────────┘ This file is part of FreeRTOS OS Project FreeRTOS OS is free either version of the or (at your option)
Variable Documentation
License
│ └──────────────────────────────────────────────────────────────┘ This file is part of FreeRTOS OS Project FreeRTOS OS is free either version of the License
Definition at line 36 of file lib/fsm/fsm.h.
software
│ └──────────────────────────────────────────────────────────────┘ This file is part of FreeRTOS OS Project FreeRTOS OS is free software
Definition at line 33 of file lib/fsm/fsm.h.