FreeRTOS-OS: main.c File Reference
main.c File Reference
#include <device.h>
#include <board/mcu_config.h>
#include <ipc/mqueue.h>
#include <ipc/global_var.h>
#include <os/kernel.h>
#include <os/kernel_syscall.h>
#include <os/kernel_services.h>
#include <drivers/cpu/drv_cpu.h>
#include <drivers/drv_rcc.h>
#include <board/board_config.h>
#include <board/irq_hw_init_generated.h>
Functions
__attribute__ ((section(".boot")))
__attribute__ ((weak))
static void ipc_queues_init (void)
Function Documentation
__attribute__() [1/2]
__attribute__ ((section(".boot")))
Definition at line 91 of file main.c.
{
    /* 1. HAL init and system clock.  All peripheral clocks are derived from
     *    SYSCLK so this must complete before any peripheral is touched. */
    HAL_Init();
    drv_rcc_clock_init();
    /* 1a. Enable all RCC clocks (sys bus, peripherals, GPIO ports) so every
     *     HAL_xxx_MspInit() can configure GPIO and NVIC without enabling clocks
     *     itself.  Must run before irq_hw_init_all() and before any peripheral
     *     management thread calls HAL_xxx_Init(). */
    board_clk_enable();
    /* 2. Configure NVIC group bits required by FreeRTOS before any
     *    interrupt-driven peripheral is initialised. */
    drv_cpu_interrupt_prio_set();
    /* 2a. Initialise irq_desc table and bind irq_chip to all hardware-backed
     *     software IRQ IDs.  Must run before any request_irq() call.
     *     TIM1 (HAL tick) is already firing at this point; hal_timebase_stm32_irq_handler
     *     uses an early-boot fallback until handle_irq is populated here. */
    irq_hw_init_all();
    /* 3. IPC ring-buffer queues — UART mgmt reads ring-buffer handles after
     *    its startup delay, so these must be allocated first. */
    ipc_queues_init();
    /* 4. Register all OS service tasks in one call.
     *    See services/kernel_service_core.c for the full registration table. */
    os_kernel_thread_register();
    /* 5. Bind printk() to the TX ring-buffer of COMM_PRINTK_HW_ID.
     *    Must be called after ipc_queues_init() registers the queue. */
    printk_init();
    /* 6. Application layer.  app_main() creates tasks, optionally registers
     *    additional IRQ subscribers via irq_register(), then returns.
     *    Tasks are driven by the scheduler; app_main must not block. */
    app_main();
    /* 7. Hand over to FreeRTOS.  Interrupts are enabled for the first time
     *    inside vPortSVCHandler when the first task context loads. */
    vTaskStartScheduler();
    while (1) {}
}
References drv_cpu_interrupt_prio_set(), drv_rcc_clock_init(), ipc_queues_init(), os_kernel_thread_register(), and printk_init().
__attribute__() [2/2]
__attribute__ ((weak))
Definition at line 59 of file main.c.
{ return 0; }
ipc_queues_init()
static void ipc_queues_init (void) static
Definition at line 64 of file main.c.
{
    ipc_mqueue_init();
    for (uint8_t i = 0; i < NO_OF_UART; i++)
    {
        global_uart_tx_mqueue_list[i] = ipc_mqueue_register(
            IPC_MQUEUE_TYPE_UART_HW, (int32_t)i,
            (int32_t)sizeof(uint8_t), PIPE_UART_1_DRV_TX_SIZE);
        global_uart_rx_mqueue_list[i] = ipc_mqueue_register(
            IPC_MQUEUE_TYPE_UART_HW, (int32_t)i,
            (int32_t)sizeof(uint8_t), PIPE_UART_1_DRV_RX_SIZE);
    }
#if (NO_OF_IIC > 0)
    for (uint8_t i = 0; i < NO_OF_IIC; i++)
    {
        global_iic_tx_mqueue_list[i] = 0;
        global_iic_rx_mqueue_list[i] = 0;
    }
#endif
}
References global_iic_rx_mqueue_list, global_iic_tx_mqueue_list, global_uart_rx_mqueue_list, global_uart_tx_mqueue_list, ipc_mqueue_init(), ipc_mqueue_register(), IPC_MQUEUE_TYPE_UART_HW, PIPE_UART_1_DRV_RX_SIZE, and PIPE_UART_1_DRV_TX_SIZE.