FreeRTOS-OS: mqueue.c File Reference
mqueue.c File Reference
#include <ipc/mqueue.h>
Functions
struct list_node * ipc_get_mqueue_head (void)
void * ipc_mqueue_get_handle (int32_t mqueue_id)
status_type ipc_mqueue_init (void)
status_type ipc_mqueue_receive_item (uint32_t queue_id, void *item_ptr)
int32_t ipc_mqueue_register (type_mqueue queue_type, int32_t hardware_id, int32_t item_size, int32_t queue_size)
status_type ipc_mqueue_send_item (uint32_t queue_id, const void *item_ptr)
status_type ipc_mqueue_unregister (int32_t mqueue_id)
Variables
static int32_t mqueue_id_counter = 1
static struct list_node mqueue_list_head = { &(mqueue_list_head), &(mqueue_list_head) }
Function Documentation
ipc_get_mqueue_head()
struct list_node * ipc_get_mqueue_head (void)
Returns the list sentinel; iterate with list_for_each_entry(..., list).
Definition at line 33 of file mqueue.c.
{
    return &mqueue_list_head;
}
References mqueue_list_head.
ipc_mqueue_get_handle()
void * ipc_mqueue_get_handle (int32_t mqueue_id)
Definition at line 187 of file mqueue.c.
{
    void *mqueue_ptr = NULL;
    ATOMIC_ENTER_CRITICAL();
    type_message_queue_descriptor *pos;
    list_for_each_entry(pos, &mqueue_list_head, list)
    {
        if(pos->mqueue.queue_id == (uint32_t)mqueue_id)
        {
            mqueue_ptr = pos->mqueue.handle;
            break;
        }
    }
    ATOMIC_EXIT_CRITICAL();
    return mqueue_ptr;
}
References type_mqueue_descriptor_content::handle, list_for_each_entry, message_queue_descriptor::mqueue, mqueue_list_head, and type_mqueue_descriptor_content::queue_id.
ipc_mqueue_init()
status_type ipc_mqueue_init (void)
Definition at line 44 of file mqueue.c.
{
    list_init(&mqueue_list_head);
    mqueue_id_counter = 1;
    return ERROR_NONE;
}
References ERROR_NONE, list_init(), mqueue_id_counter, and mqueue_list_head.
ipc_mqueue_receive_item()
status_type ipc_mqueue_receive_item (uint32_t queue_id, void * item_ptr)
Definition at line 252 of file mqueue.c.
{
    status_type status = ERROR_OP;
    ATOMIC_ENTER_CRITICAL();
    type_message_queue_descriptor *pos;
    list_for_each_entry(pos, &mqueue_list_head, list)
    {
        if(pos->mqueue.queue_id == queue_id)
        {
            if(pos->mqueue.queue_type == IPC_MQUEUE_TYPE_PROC_TXN)
            {
                ATOMIC_EXIT_CRITICAL();
                /* Use task-context receive; 0 timeout (non-blocking) */
                BaseType_t ret = xQueueReceive(pos->mqueue.free_rtos_queue_handle,
                                               item_ptr, (TickType_t)0);
                status = (ret == pdTRUE) ? ERROR_NONE : ERROR_OP;
                return status;
            }
            break;
        }
    }
    ATOMIC_EXIT_CRITICAL();
    return status;
}
References ERROR_NONE, ERROR_OP, type_mqueue_descriptor_content::free_rtos_queue_handle, IPC_MQUEUE_TYPE_PROC_TXN, list_for_each_entry, message_queue_descriptor::mqueue, mqueue_list_head, type_mqueue_descriptor_content::queue_id, and type_mqueue_descriptor_content::queue_type.
ipc_mqueue_register()
int32_t ipc_mqueue_register (type_mqueue queue_type, int32_t hardware_id, int32_t item_size, int32_t queue_size)
Definition at line 58 of file mqueue.c.
{
    int32_t mqueue_id = 0;
    ATOMIC_ENTER_CRITICAL();
    type_message_queue_descriptor *new_node =
        (type_message_queue_descriptor *)kmaloc(sizeof(type_message_queue_descriptor));
    if(new_node != NULL)
    {
        switch(queue_type)
        {
            case IPC_MQUEUE_TYPE_PROC_TXN:
            {
                QueueHandle_t temp_queue_handle = xQueueCreate(queue_size, item_size);
                if(temp_queue_handle != NULL)
                {
                    new_node->mqueue.queue_id                   = mqueue_id_counter++;
                    mqueue_id                                   = new_node->mqueue.queue_id;
                    new_node->mqueue.queue_type                 = IPC_MQUEUE_TYPE_PROC_TXN;
                    new_node->mqueue.linked_hw_peripheral_id    = -1;
                    new_node->mqueue.free_rtos_queue_handle     = temp_queue_handle;
                    new_node->mqueue.handle                     = NULL;
                }
                else
                {
                    kfree(new_node);
                    new_node = NULL;
                }
                break;
            }
            case IPC_MQUEUE_TYPE_UART_HW:
            {
                struct ringbuffer *temp_buffer_handle =
                    ringbuffer_create((uint16_t)queue_size);
                if(temp_buffer_handle != NULL)
                {
                    new_node->mqueue.queue_id                   = mqueue_id_counter++;
                    mqueue_id                                   = new_node->mqueue.queue_id;
                    new_node->mqueue.queue_type                 = IPC_MQUEUE_TYPE_UART_HW;
                    new_node->mqueue.linked_hw_peripheral_id    = hardware_id;
                    new_node->mqueue.handle                     = (void *)temp_buffer_handle;
                    new_node->mqueue.free_rtos_queue_handle     = NULL;
                }
                else
                {
                    kfree(new_node);
                    new_node = NULL;
                }
                break;
            }
            default:
                kfree(new_node);
                new_node = NULL;
                break;
        }
        if(new_node != NULL)
        {
            /* Add at tail — O(1) with circular sentinel */
            list_add_tail(&new_node->list, &mqueue_list_head);
        }
    }
    ATOMIC_EXIT_CRITICAL();
    return mqueue_id;
}
References type_mqueue_descriptor_content::free_rtos_queue_handle, type_mqueue_descriptor_content::handle, IPC_MQUEUE_TYPE_PROC_TXN, IPC_MQUEUE_TYPE_UART_HW, kfree(), kmaloc(), type_mqueue_descriptor_content::linked_hw_peripheral_id, message_queue_descriptor::list, list_add_tail(), message_queue_descriptor::mqueue, mqueue_id_counter, mqueue_list_head, type_mqueue_descriptor_content::queue_id, type_mqueue_descriptor_content::queue_type, and ringbuffer_create().
ipc_mqueue_send_item()
status_type ipc_mqueue_send_item (uint32_t queue_id, const void * item_ptr)
Definition at line 215 of file mqueue.c.
{
    status_type status = ERROR_OP;
    ATOMIC_ENTER_CRITICAL();
    type_message_queue_descriptor *pos;
    list_for_each_entry(pos, &mqueue_list_head, list)
    {
        if(pos->mqueue.queue_id == queue_id)
        {
            if(pos->mqueue.queue_type == IPC_MQUEUE_TYPE_PROC_TXN)
            {
                ATOMIC_EXIT_CRITICAL();
                /* Use task-context send; 0 timeout (non-blocking) */
                BaseType_t ret = xQueueSend(pos->mqueue.free_rtos_queue_handle,
                                            item_ptr, (TickType_t)0);
                status = (ret == pdTRUE) ? ERROR_NONE : ERROR_OP;
                return status;
            }
            break;
        }
    }
    ATOMIC_EXIT_CRITICAL();
    return status;
}
References ERROR_NONE, ERROR_OP, type_mqueue_descriptor_content::free_rtos_queue_handle, IPC_MQUEUE_TYPE_PROC_TXN, list_for_each_entry, message_queue_descriptor::mqueue, mqueue_list_head, type_mqueue_descriptor_content::queue_id, and type_mqueue_descriptor_content::queue_type.
ipc_mqueue_unregister()
status_type ipc_mqueue_unregister (int32_t mqueue_id)
Definition at line 140 of file mqueue.c.
{
    status_type status = ERROR_NONE;
    ATOMIC_ENTER_CRITICAL();
    type_message_queue_descriptor *pos;
    list_for_each_entry(pos, &mqueue_list_head, list)
    {
        if(pos->mqueue.queue_id == (uint32_t)mqueue_id)
        {
            switch(pos->mqueue.queue_type)
            {
                case IPC_MQUEUE_TYPE_PROC_TXN:
                    vQueueDelete(pos->mqueue.free_rtos_queue_handle);
                    break;
                case IPC_MQUEUE_TYPE_UART_HW:
                    ringbuffer_destroy((struct ringbuffer *)pos->mqueue.handle);
                    break;
                default:
                    break;
            }
            list_delete(&pos->list);
            kfree(pos);
            ATOMIC_EXIT_CRITICAL();
            return ERROR_NONE;
        }
    }
    status = ERROR_OP;
    ATOMIC_EXIT_CRITICAL();
    return status;
}
References ERROR_NONE, ERROR_OP, type_mqueue_descriptor_content::free_rtos_queue_handle, type_mqueue_descriptor_content::handle, IPC_MQUEUE_TYPE_PROC_TXN, IPC_MQUEUE_TYPE_UART_HW, kfree(), message_queue_descriptor::list, list_delete(), list_for_each_entry, message_queue_descriptor::mqueue, mqueue_list_head, type_mqueue_descriptor_content::queue_id, type_mqueue_descriptor_content::queue_type, and ringbuffer_destroy().
Variable Documentation
mqueue_id_counter
int32_t mqueue_id_counter = 1 static
Definition at line 24 of file mqueue.c.
mqueue_list_head
struct list_node mqueue_list_head = { &(mqueue_list_head), &(mqueue_list_head) } static
Definition at line 22 of file mqueue.c.