FreeRTOS-OS: os_shell_management.c File Reference
os_shell_management.c File Reference
#include <services/os_shell_management.h>
#include <string.h>
#include <stdio.h>
#include <os/kernel.h>
#include <os/kernel_syscall.h>
#include <board/mcu_config.h>
#include <config/conf_os.h>
#include <def_err.h>
#include <ipc/ringbuffer.h>
#include <ipc/global_var.h>
#include <ipc/mqueue.h>
#include <drivers/drv_handle.h>
#include <drivers/timer/drv_time.h>
#include <task.h>
#include <FreeRTOS_CLI.h>
#include <shell/shell_task_mgmt.h>
#include <board/board_config.h>
Macros
#define _L(fmt, ...)
#define _W(s) _shell_write((s), (uint16_t)(sizeof(s) - 1))
#define _W(s) _shell_write((s), (uint16_t)(sizeof(s) - 1))
#define SHELL_PROMPT "\r\n> "
Functions
static BaseType_t _cmd_help_fn (char *out, size_t len, const char *in)
static BaseType_t _cmd_reboot_fn (char *out, size_t len, const char *in)
static BaseType_t _cmd_uptime_fn (char *out, size_t len, const char *in)
static BaseType_t _cmd_version_fn (char *out, size_t len, const char *in)
static void _os_shell_task (void *arg)
static void _print_banner (void)
static void _shell_process_line (void)
static void _shell_write (const char *str, uint16_t len)
int32_t os_shell_mgmt_start (void)
Create and start the OS shell management task.
Variables
static const CLI_Command_Definition_t _cmd_help
static const CLI_Command_Definition_t _cmd_reboot
static const CLI_Command_Definition_t _cmd_uptime
static const CLI_Command_Definition_t _cmd_version
static char _line_buf [(128)]
static uint16_t _line_pos
static char _out_buf [(128)]
Macro Definition Documentation
_L
#define _L (fmt, ...)
Value:
    do { n = (uint16_t)snprintf(_out_buf, sizeof(_out_buf), fmt, ##__VA_ARGS__); \
         _shell_write(_out_buf, n); } while (0)
_W [1/2]
#define _W (s) _shell_write((s), (uint16_t)(sizeof(s) - 1))
_W [2/2]
#define _W (s) _shell_write((s), (uint16_t)(sizeof(s) - 1))
SHELL_PROMPT
#define SHELL_PROMPT "\r\n> "
Definition at line 84 of file os_shell_management.c.
Function Documentation
_cmd_help_fn()
static BaseType_t _cmd_help_fn (char * out, size_t len, const char * in) static
Definition at line 265 of file os_shell_management.c.
{
    (void)in;
    /* FreeRTOS+CLI has a built-in "help" list, but we can produce a custom one.
     * Returning pdFALSE lets the CLI engine print the registered help strings. */
    snprintf(out, len,
             "Use FreeRTOS+CLI registered commands:\r\n"
             "  Type any command and press Enter.\r\n");
    return pdFALSE;
}
_cmd_reboot_fn()
static BaseType_t _cmd_reboot_fn (char * out, size_t len, const char * in) static
Definition at line 296 of file os_shell_management.c.
{
    (void)in;
    snprintf(out, len, "Rebooting...\r\n");
    /* Flush output before reset */
    _shell_write(out, (uint16_t)strlen(out));
    vTaskDelay(pdMS_TO_TICKS(50));
    NVIC_SystemReset();
    return pdFALSE; /* unreachable */
}
References _shell_write().
_cmd_uptime_fn()
static BaseType_t _cmd_uptime_fn (char * out, size_t len, const char * in) static
Definition at line 286 of file os_shell_management.c.
{
    (void)in;
    uint32_t ms = drv_time_get_ticks();
    snprintf(out, len,
             "Uptime: %lu ms  (%lu s)\r\n",
             (unsigned long)ms, (unsigned long)(ms / 1000UL));
    return pdFALSE;
}
References drv_time_get_ticks().
_cmd_version_fn()
static BaseType_t _cmd_version_fn (char * out, size_t len, const char * in) static
Definition at line 276 of file os_shell_management.c.
{
    (void)in;
    snprintf(out, len,
             "FreeRTOS-OS v1.0  built %s %s\r\n"
             "Kernel: FreeRTOS V202212.00\r\n",
             __DATE__, __TIME__);
    return pdFALSE;
}
_os_shell_task()
static void _os_shell_task (void * arg) static
Definition at line 184 of file os_shell_management.c.
{
    (void)arg;
    /* Wait for UART_SHELL to be registered by uart_mgmt */
    os_thread_delay(TIME_OFFSET_OS_SHELL_MGMT);
    /* Register built-in commands */
    FreeRTOS_CLIRegisterCommand(&_cmd_help);
    FreeRTOS_CLIRegisterCommand(&_cmd_version);
    FreeRTOS_CLIRegisterCommand(&_cmd_uptime);
    FreeRTOS_CLIRegisterCommand(&_cmd_reboot);
    /* Register shell command modules */
    shell_task_mgmt_register_cmds();
    /* Print welcome banner */
    _print_banner();
    _shell_write(SHELL_PROMPT, (uint16_t)(sizeof(SHELL_PROMPT) - 1));
    memset(_line_buf, 0, sizeof(_line_buf));
    _line_pos = 0;
    for (;;)
    {
        uint8_t byte;
        /* Poll the UART_SHELL RX ring buffer; yield when empty */
        struct ringbuffer *rx_rb = (struct ringbuffer *)
            ipc_mqueue_get_handle(global_uart_rx_mqueue_list[UART_SHELL_HW_ID]);
        if (rx_rb == NULL || ringbuffer_getchar(rx_rb, &byte) == 0)
        {
            vTaskDelay(pdMS_TO_TICKS(5));
            continue;
        }
        switch (byte)
        {
            case '\r':
            case '\n':
                _line_buf[_line_pos] = '\0';
                _shell_process_line();
                break;
            case '\b':   /* BS  */
            case 0x7FU:  /* DEL */
                if (_line_pos > 0)
                {
                    _line_pos--;
                    _line_buf[_line_pos] = '\0';
                    _shell_write("\b \b", 3);
                }
                break;
            case 0x1BU:  /* ESC — disable printk debug output */
                printk_disable();
                _shell_write("\r\n[debug off]\r\n", 15);
                _shell_write(SHELL_PROMPT, (uint16_t)(sizeof(SHELL_PROMPT) - 1));
                break;
            case 0x03U:  /* Ctrl-C — discard current line */
                memset(_line_buf, 0, sizeof(_line_buf));
                _line_pos = 0;
                _shell_write("^C", 2);
                _shell_write(SHELL_PROMPT, (uint16_t)(sizeof(SHELL_PROMPT) - 1));
                break;
            default:
                if (byte >= 0x20U && _line_pos < (SHELL_LINE_BUF_LEN - 1U))
                {
                    _line_buf[_line_pos++] = (char)byte;
                    _shell_write((const char *)&byte, 1); /* local echo */
                }
                break;
        }
    }
}
References _cmd_help, _cmd_reboot, _cmd_uptime, _cmd_version, _line_buf, _line_pos, _print_banner(), _shell_process_line(), _shell_write(), global_uart_rx_mqueue_list, ipc_mqueue_get_handle(), os_thread_delay(), printk_disable(), ringbuffer_getchar(), SHELL_LINE_BUF_LEN, SHELL_PROMPT, shell_task_mgmt_register_cmds(), TIME_OFFSET_OS_SHELL_MGMT, and UART_SHELL_HW_ID.
_print_banner()
static void _print_banner (void) static
Definition at line 115 of file os_shell_management.c.
{
    extern uint32_t SystemCoreClock;
    const board_config_t *brd = board_get_config();
    uint32_t mhz = SystemCoreClock / 1000000UL;
    uint16_t n;
/* Static art — written as a string literal, never touches _out_buf */
#define _W(s) _shell_write((s), (uint16_t)(sizeof(s) - 1))
    _W("\r\n");
    _W(" +-----------------------------------------+\r\n");
    _W(" |                                         |\r\n");
    _W(" |   ____              ___ _____ ___  ____  |\r\n");
    _W(" |  |  __| ___ ___ ___|  _|_   _/   \\/ ___| |\r\n");
    _W(" |  | |_  |  _| -_| -_|_  | | || o  \\___  | |\r\n");
    _W(" |  |____||_| |___|___|___| |_| \\___/|____/ |\r\n");
    _W(" |              O S   v 1 . 0               |\r\n");
    _W(" |                                         |\r\n");
    _W(" +-----------------------------------------+\r\n");
#undef _W
    /* Dynamic info lines — one snprintf per line, each ~46 B < SHELL_OUT_BUF_LEN */
#define _L(fmt, ...) \
    do { n = (uint16_t)snprintf(_out_buf, sizeof(_out_buf), fmt, ##__VA_ARGS__); \
         _shell_write(_out_buf, n); } while (0)
    _L(" |  Board    : %-28s|\r\n", brd ? brd->board_name : "unknown");
    _L(" |  MCU      : %-28s|\r\n", CONFIG_TARGET_MCU);
    _L(" |  CPU Clock: %-3lu MHz                      |\r\n", (unsigned long)mhz);
    _L(" |  Kernel   : FreeRTOS %-20s|\r\n", tskKERNEL_VERSION_NUMBER);
    _L(" |  Build    : %-28s|\r\n", __DATE__ " " __TIME__);
#undef _L
#define _W(s) _shell_write((s), (uint16_t)(sizeof(s) - 1))
    _W(" +-----------------------------------------+\r\n");
    _W("   Type 'help' for available commands.\r\n");
#undef _W
}
References _L, _W, CONFIG_TARGET_MCU, and SystemCoreClock.
_shell_process_line()
static void _shell_process_line (void) static
Definition at line 156 of file os_shell_management.c.
{
    BaseType_t more;
    if (_line_pos == 0)
    {
        _shell_write(SHELL_PROMPT, (uint16_t)(sizeof(SHELL_PROMPT) - 1));
        return;
    }
    _shell_write("\r\n", 2);
    do {
        memset(_out_buf, 0, sizeof(_out_buf));
        more = FreeRTOS_CLIProcessCommand(_line_buf, _out_buf, sizeof(_out_buf));
        uint16_t olen = (uint16_t)strlen(_out_buf);
        if (olen > 0)
            _shell_write(_out_buf, olen);
    } while (more == pdTRUE);
    _shell_write(SHELL_PROMPT, (uint16_t)(sizeof(SHELL_PROMPT) - 1));
    memset(_line_buf, 0, sizeof(_line_buf));
    _line_pos = 0;
}
References _line_buf, _line_pos, _out_buf, _shell_write(), and SHELL_PROMPT.
_shell_write()
static void _shell_write (const char * str, uint16_t len) static
Definition at line 96 of file os_shell_management.c.
{
    if (str == NULL || len == 0)
        return;
    struct ringbuffer *rb = (struct ringbuffer *)
        ipc_mqueue_get_handle(global_uart_tx_mqueue_list[UART_SHELL_HW_ID]);
    if (rb == NULL)
        return;
    for (uint16_t i = 0; i < len; i++)
        ringbuffer_putchar(rb, (uint8_t)str[i]);
    drv_uart_tx_kick(UART_SHELL_HW_ID);
}
References drv_uart_tx_kick(), global_uart_tx_mqueue_list, ipc_mqueue_get_handle(), ringbuffer_putchar(), and UART_SHELL_HW_ID.
os_shell_mgmt_start()
int32_t os_shell_mgmt_start (void)
Create and start the OS shell management task.
Must be called once from the OS init sequence before the scheduler starts. The task will delay TIME_OFFSET_OS_SHELL_MGMT ms before printing the banner and entering the read loop, ensuring the UART driver is initialised first.
Returns
OS_ERR_NONE on success, OS_ERR_OP if task creation fails.
Definition at line 309 of file os_shell_management.c.
{
    int32_t tid = os_thread_create(_os_shell_task,
                                   "os_shell",
                                   PROC_SERVICE_OS_SHELL_MGMT_STACK_SIZE,
                                   PROC_SERVICE_OS_SHELL_MGMT_PRIORITY,
                                   NULL);
    return (tid >= 0) ? OS_ERR_NONE : OS_ERR_OP;
}
References _os_shell_task(), OS_ERR_NONE, OS_ERR_OP, os_thread_create(), PROC_SERVICE_OS_SHELL_MGMT_PRIORITY, and PROC_SERVICE_OS_SHELL_MGMT_STACK_SIZE.
Variable Documentation
_cmd_help
const CLI_Command_Definition_t _cmd_help static
Initial value:
= {
    "help",
    "help\r\n  List all registered commands.\r\n",
    _cmd_help_fn, 0
}
Definition at line 61 of file os_shell_management.c.
{
    "help",
    "help\r\n  List all registered commands.\r\n",
    _cmd_help_fn, 0
};
_cmd_reboot
const CLI_Command_Definition_t _cmd_reboot static
Initial value:
= {
    "reboot",
    "reboot\r\n  Trigger a software reset (NVIC_SystemReset).\r\n",
    _cmd_reboot_fn, 0
}
Definition at line 76 of file os_shell_management.c.
{
    "reboot",
    "reboot\r\n  Trigger a software reset (NVIC_SystemReset).\r\n",
    _cmd_reboot_fn, 0
};
_cmd_uptime
const CLI_Command_Definition_t _cmd_uptime static
Initial value:
= {
    "uptime",
    "uptime\r\n  Print system uptime in milliseconds.\r\n",
    _cmd_uptime_fn, 0
}
Definition at line 71 of file os_shell_management.c.
{
    "uptime",
    "uptime\r\n  Print system uptime in milliseconds.\r\n",
    _cmd_uptime_fn, 0
};
_cmd_version
const CLI_Command_Definition_t _cmd_version static
Initial value:
= {
    "version",
    "version\r\n  Print firmware version and build date.\r\n",
    _cmd_version_fn, 0
}
Definition at line 66 of file os_shell_management.c.
{
    "version",
    "version\r\n  Print firmware version and build date.\r\n",
    _cmd_version_fn, 0
};
_line_buf
char _line_buf[(128)] static
Definition at line 86 of file os_shell_management.c.
_line_pos
uint16_t _line_pos static
Definition at line 87 of file os_shell_management.c.
_out_buf
char _out_buf[(128)] static
Definition at line 88 of file os_shell_management.c.