FreeRTOS-OS: shell_task_mgmt.c File Reference
shell_task_mgmt.c File Reference
#include <shell/shell_task_mgmt.h>
#include <os/kernel_task_mgr.h>
#include <os/kernel_syscall.h>
#include <FreeRTOS.h>
#include <task.h>
#include <FreeRTOS_CLI.h>
#include <stdio.h>
#include <string.h>
Functions
static BaseType_t _cmd_debug_fn (char *out, size_t len, const char *in)
static BaseType_t _cmd_heap_fn (char *out, size_t len, const char *in)
static BaseType_t _cmd_tasks_fn (char *out, size_t len, const char *in)
static const char * _state_to_str (eTaskState s)
void shell_task_mgmt_register_cmds (void)
Variables
static const CLI_Command_Definition_t _cmd_debug
static const CLI_Command_Definition_t _cmd_heap
static const CLI_Command_Definition_t _cmd_tasks
static const char *const _state_str []
static int16_t _tasks_line = -1
Function Documentation
_cmd_debug_fn()
static BaseType_t _cmd_debug_fn (char * out, size_t len, const char * in) static
Definition at line 190 of file shell_task_mgmt.c.
{
    BaseType_t plen;
    const char *param = FreeRTOS_CLIGetParameter(in, 1, &plen);
    if (param == NULL)
    {
        snprintf(out, len, "Usage: debug <en|dis>\r\n");
        return pdFALSE;
    }
    if (plen == 2 && strncmp(param, "en", 2) == 0)
    {
        printk_enable();
        snprintf(out, len, "Debug output enabled.\r\n");
    }
    else if (plen == 3 && strncmp(param, "dis", 3) == 0)
    {
        printk_disable();
        snprintf(out, len, "Debug output disabled.\r\n");
    }
    else
    {
        snprintf(out, len, "Unknown option '%.*s'. Usage: debug <en|dis>\r\n",
                 (int)plen, param);
    }
    return pdFALSE;
}
References printk_disable(), and printk_enable().
_cmd_heap_fn()
static BaseType_t _cmd_heap_fn (char * out, size_t len, const char * in) static
Definition at line 90 of file shell_task_mgmt.c.
{
    (void)in;
    const sys_health_t *h     = task_mgr_get_health();
    size_t              total = (size_t)configTOTAL_HEAP_SIZE;
    size_t              free  = (size_t)xPortGetFreeHeapSize();
    size_t              used  = total - free;
    size_t              minf  = (size_t)xPortGetMinimumEverFreeHeapSize();
    uint32_t            faults = h ? h->malloc_fail_count : 0U;
    snprintf(out, len,
             "Heap usage:\r\n"
             "  Total  : %6u B\r\n"
             "  Used   : %6u B\r\n"
             "  Free   : %6u B\r\n"
             "  MinFree: %6u B  (min ever free)\r\n"
             "  Errors : %lu malloc failure(s)\r\n",
             (unsigned)total,
             (unsigned)used,
             (unsigned)free,
             (unsigned)minf,
             (unsigned long)faults);
    return pdFALSE;
}
References configTOTAL_HEAP_SIZE, sys_health_t::malloc_fail_count, and task_mgr_get_health().
_cmd_tasks_fn()
static BaseType_t _cmd_tasks_fn (char * out, size_t len, const char * in) static
Definition at line 127 of file shell_task_mgmt.c.
{
    (void)in;
    const sys_health_t *h = task_mgr_get_health();
    if (h == NULL)
    {
        _tasks_line = -1;
        snprintf(out, len, "Task manager not available.\r\n");
        return pdFALSE;
    }
    /* ── Header ── */
    if (_tasks_line == -1)
    {
        snprintf(out, len,
                 "Tasks  (%u registered)\r\n"
                 "  ID  %-16s %-10s StackHWM\r\n"
                 "  ----------------------------------------\r\n",
                 (unsigned)h->task_count,
                 "Name", "State");
        _tasks_line = 0;
        return pdTRUE;
    }
    /* ── Per-task lines ── */
    if (_tasks_line < (int16_t)h->task_count)
    {
        const task_health_t *t = &h->tasks[_tasks_line];
        snprintf(out, len,
                 "  %2lu  %-16s %-10s %u w\r\n",
                 (unsigned long)t->thread_id,
                 t->name ? t->name : "?",
                 _state_to_str(t->state),
                 (unsigned)t->stack_hwm);
        _tasks_line++;
        return pdTRUE;
    }
    /* ── Timer-daemon line ── */
    if (_tasks_line == (int16_t)h->task_count && h->timer_task_valid)
    {
        const task_health_t *t = &h->timer_task;
        snprintf(out, len,
                 "  [T] %-16s %-10s %u w  (timer daemon)\r\n",
                 t->name ? t->name : "Tmr Svc",
                 _state_to_str(t->state),
                 (unsigned)t->stack_hwm);
        _tasks_line++;
        return pdTRUE;
    }
    /* ── Summary / final line ── */
    snprintf(out, len,
             "  Stack overflow events: %lu\r\n",
             (unsigned long)h->stack_overflow_count);
    _tasks_line = -1;
    return pdFALSE;
}
References _state_to_str(), _tasks_line, task_health_t::name, task_health_t::stack_hwm, sys_health_t::stack_overflow_count, task_health_t::state, sys_health_t::task_count, task_mgr_get_health(), sys_health_t::tasks, task_health_t::thread_id, sys_health_t::timer_task, and sys_health_t::timer_task_valid.
_state_to_str()
static const char * _state_to_str (eTaskState s) static
Definition at line 81 of file shell_task_mgmt.c.
{
    if ((unsigned)s < (sizeof(_state_str) / sizeof(_state_str[0])))
        return _state_str[(unsigned)s];
    return "?";
}
References _state_str.
shell_task_mgmt_register_cmds()
void shell_task_mgmt_register_cmds (void)
Definition at line 222 of file shell_task_mgmt.c.
{
    FreeRTOS_CLIRegisterCommand(&_cmd_heap);
    FreeRTOS_CLIRegisterCommand(&_cmd_tasks);
    FreeRTOS_CLIRegisterCommand(&_cmd_debug);
}
References _cmd_debug, _cmd_heap, and _cmd_tasks.
Variable Documentation
_cmd_debug
const CLI_Command_Definition_t _cmd_debug static
Initial value:
= {
    "debug",
    "debug <en|dis>\r\n"
    "  Enable or disable printk debug output.\r\n",
    _cmd_debug_fn, 1
}
Definition at line 68 of file shell_task_mgmt.c.
{
    "debug",
    "debug <en|dis>\r\n"
    "  Enable or disable printk debug output.\r\n",
    _cmd_debug_fn, 1
};
_cmd_heap
const CLI_Command_Definition_t _cmd_heap static
Initial value:
= {
    "heap",
    "heap\r\n"
    "  Show FreeRTOS heap: total, used, free, min-ever-free, malloc failures.\r\n",
    _cmd_heap_fn, 0
}
Definition at line 54 of file shell_task_mgmt.c.
{
    "heap",
    "heap\r\n"
    "  Show FreeRTOS heap: total, used, free, min-ever-free, malloc failures.\r\n",
    _cmd_heap_fn, 0
};
_cmd_tasks
const CLI_Command_Definition_t _cmd_tasks static
Initial value:
= {
    "tasks",
    "tasks\r\n"
    "  List all OS tasks with state and stack high-watermark (5 s snapshot).\r\n",
    _cmd_tasks_fn, 0
}
Definition at line 61 of file shell_task_mgmt.c.
{
    "tasks",
    "tasks\r\n"
    "  List all OS tasks with state and stack high-watermark (5 s snapshot).\r\n",
    _cmd_tasks_fn, 0
};
_state_str
const char* const _state_str[] static
Initial value:
= {
    "running", "ready", "blocked", "suspended", "deleted", "invalid"
}
Definition at line 77 of file shell_task_mgmt.c.
{
    "running", "ready", "blocked", "suspended", "deleted", "invalid"
};
_tasks_line
int16_t _tasks_line = -1 static
Definition at line 125 of file shell_task_mgmt.c.