FreeRTOS-OS: spi_app.c File Reference
spi_app.c File Reference
#include <drv_app/spi_app.h>
#include <services/spi_mgmt.h>
Functions
int32_t spi_async_transfer (uint8_t bus_id, const uint8_t *tx, uint8_t *rx, uint16_t len)
Non-blocking full-duplex transfer. Returns immediately after queuing.
int32_t spi_async_transmit (uint8_t bus_id, const uint8_t *data, uint16_t len)
Non-blocking transmit-only. Returns immediately after queuing.
int32_t spi_sync_receive (uint8_t bus_id, uint8_t *data, uint16_t len, uint32_t timeout_ms)
Blocking receive-only. TX line clocked with 0xFF dummy bytes.
int32_t spi_sync_transfer (uint8_t bus_id, const uint8_t *tx, uint8_t *rx, uint16_t len, uint32_t timeout_ms)
Blocking full-duplex transfer (TX and RX simultaneously).
int32_t spi_sync_transmit (uint8_t bus_id, const uint8_t *data, uint16_t len, uint32_t timeout_ms)
Blocking transmit-only. RX data clocked in is discarded.
Function Documentation
spi_async_transfer()
int32_t spi_async_transfer (uint8_t bus_id, const uint8_t * tx, uint8_t * rx, uint16_t len)
Non-blocking full-duplex transfer. Returns immediately after queuing.
Both tx and rx buffers must remain valid until the management thread processes the request. No completion notification is provided.
Definition at line 37 of file spi_app.c.
{
    return spi_mgmt_async_transfer(bus_id, tx, rx, len);
}
References spi_mgmt_async_transfer().
spi_async_transmit()
int32_t spi_async_transmit (uint8_t bus_id, const uint8_t * data, uint16_t len)
Non-blocking transmit-only. Returns immediately after queuing.
Data buffer must stay valid until the management thread drains the queue.
Definition at line 32 of file spi_app.c.
{
    return spi_mgmt_async_transmit(bus_id, data, len);
}
References spi_mgmt_async_transmit().
spi_sync_receive()
int32_t spi_sync_receive (uint8_t bus_id, uint8_t * data, uint16_t len, uint32_t timeout_ms)
Blocking receive-only. TX line clocked with 0xFF dummy bytes.
Definition at line 18 of file spi_app.c.
{
    return spi_mgmt_sync_receive(bus_id, data, len, timeout_ms);
}
References spi_mgmt_sync_receive().
spi_sync_transfer()
int32_t spi_sync_transfer (uint8_t bus_id, const uint8_t * tx, uint8_t * rx, uint16_t len, uint32_t timeout_ms)
Blocking full-duplex transfer (TX and RX simultaneously).
Parameters
tx TX buffer (NULL → dummy 0xFF bytes sent).
rx RX buffer (NULL → received bytes discarded).
Definition at line 24 of file spi_app.c.
{
    return spi_mgmt_sync_transfer(bus_id, tx, rx, len, timeout_ms);
}
References spi_mgmt_sync_transfer().
spi_sync_transmit()
int32_t spi_sync_transmit (uint8_t bus_id, const uint8_t * data, uint16_t len, uint32_t timeout_ms)
Blocking transmit-only. RX data clocked in is discarded.
Definition at line 12 of file spi_app.c.
{
    return spi_mgmt_sync_transmit(bus_id, data, len, timeout_ms);
}
References spi_mgmt_sync_transmit().