FreeRTOS-OS: stm32_exceptions.c File Reference
stm32_exceptions.c File Reference
Cortex-M4 core exception handlers for STM32.
#include <stdint.h>
#include <board/mcu_config.h>
Classes
struct fault_frame_t
struct fault_info_t
Macros
#define FAULT_TYPE_BUS 2U
#define FAULT_TYPE_HARD 0U
#define FAULT_TYPE_MEM 1U
#define FAULT_TYPE_USAGE 3U
#define USART2_BASE 0x40004400UL
#define USART2_DR (*(volatile uint32_t *)(USART2_BASE + 0x04U))
#define USART2_SR (*(volatile uint32_t *)(USART2_BASE + 0x00U))
#define USART2_TC (1UL << 6)
#define USART2_TXE (1UL << 7)
Functions
__attribute__ ((naked))
void __attribute__ ((used, noinline))
static void _decode_bfsr (uint32_t cfsr)
static void _decode_hfsr (uint32_t hfsr)
static void _decode_mmfsr (uint32_t cfsr)
static void _decode_ufsr (uint32_t cfsr)
static void _fault_print_dec (uint32_t v)
static void _fault_print_hex32 (uint32_t v)
static void _fault_putchar (char c)
static void _fault_puts (const char *s)
void DebugMon_Handler (void)
void NMI_Handler (void)
Variables
static const char * _fault_names []
volatile fault_info_t g_fault_info
Detailed Description
Cortex-M4 core exception handlers for STM32.
Author
Subhajit Roy (subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m)
Strong definitions for Cortex-M core exception handlers that override the weak symbols in startup_stm32f411vetx.c.
Fault handler chain (HardFault / MemManage / BusFault / UsageFault):
CPU fires exception │ ▼ naked trampoline (_Handler) determine active SP from EXC_RETURN bit[2]: bit[2]==0 → MSP was active (running in handler or MSP task) bit[2]==1 → PSP was active (running in a FreeRTOS task) │ ▼ _fault_handler_c(frame*, exc_return, fault_type) capture hardware exception frame (r0–r3, r12, lr, pc, xpsr) capture SCB->HFSR, CFSR, BFAR, MMFAR write g_fault_info (visible in debugger / crash dump) emit diagnostic text directly via USART2 (no ring buffer, no RTOS) halt in spin loop
Note
This module is compiled only when CONFIG_DEVICE_VARIANT == MCU_VAR_STM.
This file is part of FreeRTOS-OS Project.
Definition in file stm32_exceptions.c.
Macro Definition Documentation
FAULT_TYPE_BUS
#define FAULT_TYPE_BUS 2U
Definition at line 41 of file stm32_exceptions.c.
FAULT_TYPE_HARD
#define FAULT_TYPE_HARD 0U
Definition at line 39 of file stm32_exceptions.c.
FAULT_TYPE_MEM
#define FAULT_TYPE_MEM 1U
Definition at line 40 of file stm32_exceptions.c.
FAULT_TYPE_USAGE
#define FAULT_TYPE_USAGE 3U
Definition at line 42 of file stm32_exceptions.c.
USART2_BASE
#define USART2_BASE 0x40004400UL
Definition at line 80 of file stm32_exceptions.c.
USART2_DR
#define USART2_DR (*(volatile uint32_t *)(USART2_BASE + 0x04U))
Definition at line 82 of file stm32_exceptions.c.
USART2_SR
#define USART2_SR (*(volatile uint32_t *)(USART2_BASE + 0x00U))
Definition at line 81 of file stm32_exceptions.c.
USART2_TC
#define USART2_TC (1UL << 6)
Definition at line 84 of file stm32_exceptions.c.
USART2_TXE
#define USART2_TXE (1UL << 7)
Definition at line 83 of file stm32_exceptions.c.
Function Documentation
__attribute__() [1/2]
__attribute__ ((naked))
Definition at line 263 of file stm32_exceptions.c.
{
    __asm volatile(
        "tst  lr, #4          \n"
        "ite  eq              \n"
        "mrseq r0, msp        \n"
        "mrsne r0, psp        \n"
        "mov  r1, lr          \n"
        "mov  r2, %0          \n"
        "b    _fault_handler_c\n"
        :
        : "i" (FAULT_TYPE_HARD)
    );
}
References FAULT_TYPE_HARD.
__attribute__() [2/2]
void __attribute__ ((used, noinline))
Definition at line 177 of file stm32_exceptions.c.
{
    /* Capture SCB fault registers before anything can modify them */
    uint32_t hfsr  = *(volatile uint32_t *)0xE000ED2CUL;
    uint32_t cfsr  = *(volatile uint32_t *)0xE000ED28UL;
    uint32_t mmfar = *(volatile uint32_t *)0xE000ED34UL;
    uint32_t bfar  = *(volatile uint32_t *)0xE000ED38UL;
    /* Fill diagnostic record */
    g_fault_info.frame.r0       = frame[0];
    g_fault_info.frame.r1       = frame[1];
    g_fault_info.frame.r2       = frame[2];
    g_fault_info.frame.r3       = frame[3];
    g_fault_info.frame.r12      = frame[4];
    g_fault_info.frame.lr       = frame[5];
    g_fault_info.frame.pc       = frame[6];
    g_fault_info.frame.xpsr     = frame[7];
    g_fault_info.hfsr           = hfsr;
    g_fault_info.cfsr           = cfsr;
    g_fault_info.bfar           = bfar;
    g_fault_info.mmfar          = mmfar;
    g_fault_info.exc_return     = exc_return;
    g_fault_info.fault_type     = fault_type;
    /* Emit diagnostic over USART2 */
    _fault_puts("\r\n\r\n*** ");
    _fault_puts(fault_type < 4U ? _fault_names[fault_type] : "Fault");
    _fault_puts(" ***\r\n");
    _fault_puts("PC   : "); _fault_print_hex32(frame[6]); _fault_puts("\r\n");
    _fault_puts("LR   : "); _fault_print_hex32(frame[5]); _fault_puts("\r\n");
    _fault_puts("SP   : "); _fault_print_hex32((uint32_t)frame); _fault_puts("\r\n");
    _fault_puts("R0   : "); _fault_print_hex32(frame[0]); _fault_puts("\r\n");
    _fault_puts("R1   : "); _fault_print_hex32(frame[1]); _fault_puts("\r\n");
    _fault_puts("R2   : "); _fault_print_hex32(frame[2]); _fault_puts("\r\n");
    _fault_puts("R3   : "); _fault_print_hex32(frame[3]); _fault_puts("\r\n");
    _fault_puts("R12  : "); _fault_print_hex32(frame[4]); _fault_puts("\r\n");
    _fault_puts("xPSR : "); _fault_print_hex32(frame[7]); _fault_puts("\r\n");
    _fault_puts("HFSR : "); _fault_print_hex32(hfsr); _fault_puts("\r\n");
    _fault_puts("CFSR : "); _fault_print_hex32(cfsr); _fault_puts("\r\n");
    _decode_hfsr(hfsr);
    _decode_mmfsr(cfsr);
    _decode_bfsr(cfsr);
    _decode_ufsr(cfsr);
    if ((cfsr >> 8U) & (1U << 7)) /* BFARVALID */
    {
        _fault_puts("BFAR : "); _fault_print_hex32(bfar); _fault_puts("\r\n");
    }
    if (cfsr & (1U << 7)) /* MMARVALID */
    {
        _fault_puts("MMFAR: "); _fault_print_hex32(mmfar); _fault_puts("\r\n");
    }
    _fault_puts("EXC_RETURN: "); _fault_print_hex32(exc_return);
    _fault_puts((exc_return & 4U) ? "  (PSP)\r\n" : "  (MSP)\r\n");
    /* Wait for last byte to drain */
    while (!(USART2_SR & USART2_TC))
        ;
    for (;;)
        ;  /* halt — attach debugger, inspect g_fault_info */
}
References _decode_bfsr(), _decode_hfsr(), _decode_mmfsr(), _decode_ufsr(), _fault_names, _fault_print_hex32(), _fault_puts(), fault_info_t::bfar, fault_info_t::cfsr, fault_info_t::exc_return, fault_info_t::fault_type, fault_info_t::frame, g_fault_info, fault_info_t::hfsr, fault_frame_t::lr, fault_info_t::mmfar, fault_frame_t::pc, fault_frame_t::r0, fault_frame_t::r1, fault_frame_t::r12, fault_frame_t::r2, fault_frame_t::r3, USART2_SR, USART2_TC, and fault_frame_t::xpsr.
_decode_bfsr()
static void _decode_bfsr (uint32_t cfsr) static
Definition at line 133 of file stm32_exceptions.c.
{
    uint32_t b = (cfsr >> 8U) & 0xFFU;
    if (!b) return;
    _fault_puts("  BFSR:");
    if (b & (1U << 7)) _fault_puts(" BFARVALID");
    if (b & (1U << 5)) _fault_puts(" LSPERR");
    if (b & (1U << 4)) _fault_puts(" STKERR");
    if (b & (1U << 3)) _fault_puts(" UNSTKERR");
    if (b & (1U << 2)) _fault_puts(" IMPRECISERR");
    if (b & (1U << 1)) _fault_puts(" PRECISERR");
    if (b & (1U << 0)) _fault_puts(" IBUSERR");
    _fault_puts("\r\n");
}
References _fault_puts().
_decode_hfsr()
static void _decode_hfsr (uint32_t hfsr) static
Definition at line 162 of file stm32_exceptions.c.
{
    _fault_puts("  HFSR:");
    if (hfsr & (1U << 31)) _fault_puts(" DEBUGEVT");
    if (hfsr & (1U << 30)) _fault_puts(" FORCED");
    if (hfsr & (1U <<  1)) _fault_puts(" VECTBL");
    _fault_puts("\r\n");
}
References _fault_puts().
_decode_mmfsr()
static void _decode_mmfsr (uint32_t cfsr) static
Definition at line 119 of file stm32_exceptions.c.
{
    uint32_t m = cfsr & 0xFFU;
    if (!m) return;
    _fault_puts("  MMFSR:");
    if (m & (1U << 7)) _fault_puts(" MMARVALID");
    if (m & (1U << 5)) _fault_puts(" MLSPERR");
    if (m & (1U << 4)) _fault_puts(" MSTKERR");
    if (m & (1U << 3)) _fault_puts(" MUNSTKERR");
    if (m & (1U << 1)) _fault_puts(" DACCVIOL");
    if (m & (1U << 0)) _fault_puts(" IACCVIOL");
    _fault_puts("\r\n");
}
References _fault_puts().
_decode_ufsr()
static void _decode_ufsr (uint32_t cfsr) static
Definition at line 148 of file stm32_exceptions.c.
{
    uint32_t u = (cfsr >> 16U) & 0xFFFFU;
    if (!u) return;
    _fault_puts("  UFSR:");
    if (u & (1U << 9)) _fault_puts(" DIVBYZERO");
    if (u & (1U << 8)) _fault_puts(" UNALIGNED");
    if (u & (1U << 3)) _fault_puts(" NOCP");
    if (u & (1U << 2)) _fault_puts(" INVPC");
    if (u & (1U << 1)) _fault_puts(" INVSTATE");
    if (u & (1U << 0)) _fault_puts(" UNDEFINSTR");
    _fault_puts("\r\n");
}
References _fault_puts().
_fault_print_dec()
static void _fault_print_dec (uint32_t v) static
Definition at line 108 of file stm32_exceptions.c.
{
    if (v == 0) { _fault_putchar('0'); return; }
    char buf[10];
    int  n = 0;
    while (v) { buf[n++] = (char)('0' + v % 10U); v /= 10U; }
    while (n > 0) { n--; _fault_putchar(buf[n]); }
}
References _fault_putchar().
_fault_print_hex32()
static void _fault_print_hex32 (uint32_t v) static
Definition at line 99 of file stm32_exceptions.c.
{
    static const char hex[] = "0123456789ABCDEF";
    _fault_putchar('0');
    _fault_putchar('x');
    for (int i = 28; i >= 0; i -= 4)
        _fault_putchar(hex[(v >> i) & 0xFU]);
}
References _fault_putchar().
_fault_putchar()
static void _fault_putchar (char c) static
Definition at line 86 of file stm32_exceptions.c.
{
    while (!(USART2_SR & USART2_TXE))
        ;
    USART2_DR = (uint32_t)(uint8_t)c;
}
References USART2_DR, USART2_SR, and USART2_TXE.
_fault_puts()
static void _fault_puts (const char * s) static
Definition at line 93 of file stm32_exceptions.c.
{
    while (*s)
        _fault_putchar(*s++);
}
References _fault_putchar().
DebugMon_Handler()
void DebugMon_Handler (void)
Definition at line 325 of file stm32_exceptions.c.
{
    for (;;)
        ;
}
NMI_Handler()
void NMI_Handler (void)
Definition at line 246 of file stm32_exceptions.c.
{
    _fault_puts("\r\n*** NMI ***\r\n");
    while (!(USART2_SR & USART2_TC))
        ;
    for (;;)
        ;
}
References _fault_puts(), USART2_SR, and USART2_TC.
Variable Documentation
_fault_names
const char* _fault_names[] static
Initial value:
= {
    "HardFault", "MemManage", "BusFault", "UsageFault"
}
Definition at line 173 of file stm32_exceptions.c.
{
    "HardFault", "MemManage", "BusFault", "UsageFault"
};
g_fault_info
volatile fault_info_t g_fault_info
Definition at line 71 of file stm32_exceptions.c.