FreeRTOS-OS: syscalls.c File Reference
syscalls.c File Reference
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include <os/kernel_syscall.h>
#include <ipc/mqueue.h>
#include <drivers/drv_handle.h>
#include <stdarg.h>
Functions
__attribute__ ((weak))
int __io_getchar (void)
int __io_putchar (int ch)
int _close (int file)
int _execve (char *name, char **argv, char **env)
void _exit (int status)
int _fork (void)
int _fstat (int file, struct stat *st)
int _getpid (void)
int _isatty (int file)
int _kill (int pid, int sig)
int _link (char *old, char *new)
int _lseek (int file, int ptr, int dir)
int _open (char *path, int flags,...)
int _stat (char *file, struct stat *st)
int _times (struct tms *buf)
int _unlink (char *name)
int _wait (int *status)
void initialise_monitor_handles (void)
int32_t printk (const char *fmt,...)
void printk_disable (void)
void printk_enable (void)
void printk_init (void)
Variables
char * __env [1] = { 0 }
static char _msg_buf [64]
static volatile uint8_t _printk_enabled = 0
static struct ringbuffer * _printk_rb
static char _time_buf [10]
char ** environ = __env
Function Documentation
__attribute__()
__attribute__ ((weak))
Definition at line 70 of file syscalls.c.
{
    (void)file;
    for (int i = 0; i < len; i++)
        *ptr++ = (char)__io_getchar();
    return len;
}
References __io_getchar().
__io_getchar()
int __io_getchar (void)
Definition at line 44 of file syscalls.c.
{ return 0; }
__io_putchar()
int __io_putchar (int ch)
Definition at line 43 of file syscalls.c.
{ (void)ch; return 0; }
_close()
int _close (int file)
Definition at line 86 of file syscalls.c.
{ (void)file; return -1; }
_execve()
int _execve (char * name, char ** argv, char ** env)
Definition at line 129 of file syscalls.c.
{
    (void)name; (void)argv; (void)env;
    errno = ENOMEM;
    return -1;
}
_exit()
void _exit (int status)
Definition at line 64 of file syscalls.c.
{
    _kill(status, -1);
    while (1) {}
}
References _kill().
_fork()
int _fork (void)
Definition at line 127 of file syscalls.c.
{ errno = EAGAIN; return -1; }
_fstat()
int _fstat (int file, struct stat * st)
Definition at line 88 of file syscalls.c.
{
    (void)file;
    st->st_mode = S_IFCHR;
    return 0;
}
_getpid()
int _getpid (void)
Definition at line 55 of file syscalls.c.
{ return 1; }
_isatty()
int _isatty (int file)
Definition at line 95 of file syscalls.c.
{ (void)file; return 1; }
_kill()
int _kill (int pid, int sig)
Definition at line 57 of file syscalls.c.
{
    (void)pid; (void)sig;
    errno = EINVAL;
    return -1;
}
_link()
int _link (char * old, char * new)
Definition at line 120 of file syscalls.c.
{
    (void)old; (void)new;
    errno = EMLINK;
    return -1;
}
_lseek()
int _lseek (int file, int ptr, int dir)
Definition at line 97 of file syscalls.c.
{
    (void)file; (void)ptr; (void)dir;
    return 0;
}
_open()
int _open (char * path, int flags, ...)
Definition at line 103 of file syscalls.c.
{
    (void)path; (void)flags;
    return -1;
}
_stat()
int _stat (char * file, struct stat * st)
Definition at line 113 of file syscalls.c.
{
    (void)file;
    st->st_mode = S_IFCHR;
    return 0;
}
_times()
int _times (struct tms * buf)
Definition at line 111 of file syscalls.c.
{ (void)buf;    return -1; }
_unlink()
int _unlink (char * name)
Definition at line 110 of file syscalls.c.
{ (void)name;   errno = ENOENT; return -1; }
_wait()
int _wait (int * status)
Definition at line 109 of file syscalls.c.
{ (void)status; errno = ECHILD; return -1; }
initialise_monitor_handles()
void initialise_monitor_handles (void)
Definition at line 51 of file syscalls.c.
{}
printk()
int32_t printk (const char * fmt, ...)
Definition at line 149 of file syscalls.c.
{
#if (NO_OF_UART > 0)
    if (!_printk_enabled)
        return 0;
    va_list args;
    int     ts_len, msg_len, i;
    va_start(args, fmt);
    ATOMIC_ENTER_CRITICAL();
    ts_len = snprintf(_time_buf, sizeof(_time_buf), "[%lu] ",
                      (unsigned long)drv_time_get_ticks());
    for (i = 0; i < ts_len; i++)
        if (_printk_rb) ringbuffer_putchar(_printk_rb, (uint8_t)_time_buf[i]);
    msg_len = vsnprintf(_msg_buf, sizeof(_msg_buf), fmt, args);
    if (msg_len > 0)
        for (i = 0; i < msg_len; i++)
            if (_printk_rb) ringbuffer_putchar(_printk_rb, (uint8_t)_msg_buf[i]);
    ATOMIC_EXIT_CRITICAL();
    va_end(args);
    drv_uart_tx_kick(COMM_PRINTK_HW_ID);
    return msg_len;
#else
    (void)fmt;
    return 0;
#endif
}
References _msg_buf, _printk_enabled, _printk_rb, _time_buf, COMM_PRINTK_HW_ID, drv_time_get_ticks(), drv_uart_tx_kick(), and ringbuffer_putchar().
printk_disable()
void printk_disable (void)
Definition at line 39 of file syscalls.c.
{ _printk_enabled = 0; }
References _printk_enabled.
printk_enable()
void printk_enable (void)
Definition at line 38 of file syscalls.c.
{ _printk_enabled = 1; }
References _printk_enabled.
printk_init()
void printk_init (void)
Definition at line 138 of file syscalls.c.
{
#ifdef COMM_PRINTK_HW_ID
    if (COMM_PRINTK_HW_ID < NO_OF_UART)
        _printk_rb = (struct ringbuffer *)
                     ipc_mqueue_get_handle(global_uart_tx_mqueue_list[COMM_PRINTK_HW_ID]);
#else
#  error "printk: COMM_PRINTK_HW_ID not defined — set it in conf_os.h"
#endif
}
References _printk_rb, COMM_PRINTK_HW_ID, global_uart_tx_mqueue_list, and ipc_mqueue_get_handle().
Variable Documentation
__env
char* __env[1] = { 0 }
Definition at line 48 of file syscalls.c.
{ 0 };
_msg_buf
char _msg_buf[ 64] static
Definition at line 34 of file syscalls.c.
_printk_enabled
volatile uint8_t _printk_enabled = 0 static
Definition at line 36 of file syscalls.c.
_printk_rb
struct ringbuffer* _printk_rb static
Definition at line 35 of file syscalls.c.
_time_buf
char _time_buf[10] static
Definition at line 33 of file syscalls.c.
environ
char** environ = __env
Definition at line 49 of file syscalls.c.