FreeRTOS-OS: uart_mgmt.c File Reference
uart_mgmt.c File Reference
#include <services/uart_mgmt.h>
#include <os/kernel.h>
#include <drivers/drv_handle.h>
#include <board/board_config.h>
#include <ipc/ringbuffer.h>
#include <ipc/global_var.h>
#include <ipc/mqueue.h>
#include <irq/irq_notify.h>
#include <drivers/com/hal/stm32/hal_uart_stm32.h>
Functions
static void _uart_err_cb (irq_id_t id, void *data, void *arg, BaseType_t *pxHPT)
static void _uart_rx_cb (irq_id_t id, void *data, void *arg, BaseType_t *pxHPT)
int32_t uart_mgmt_async_transmit (uint8_t dev_id, const uint8_t *data, uint16_t len)
Post an async transmit request to the management queue.
QueueHandle_t uart_mgmt_get_queue (void)
Return the management queue handle.
int32_t uart_mgmt_read_byte (uint8_t dev_id, uint8_t *byte)
Read one byte from the UART RX ring buffer.
int32_t uart_mgmt_start (void)
Create and start the UART management thread.
static void uart_mgmt_thread (void *arg)
Variables
static QueueHandle_t _mgmt_queue = NULL
Function Documentation
_uart_err_cb()
static void _uart_err_cb (irq_id_t id, void * data, void * arg, BaseType_t * pxHPT) static
Definition at line 84 of file uart_mgmt.c.
{
    (void)id;
    (void)data;
    (void)pxHPT;
    drv_uart_handle_t *h = (drv_uart_handle_t *)arg;
    if (h != NULL)
        h->last_err = OS_ERR_OP;
}
References drv_uart_handle::last_err, and OS_ERR_OP.
_uart_rx_cb()
static void _uart_rx_cb (irq_id_t id, void * data, void * arg, BaseType_t * pxHPT) static
Definition at line 68 of file uart_mgmt.c.
{
    (void)id;
    (void)pxHPT;
    if (data == NULL || arg == NULL)
        return;
    ringbuffer_putchar((struct ringbuffer *)arg, *(uint8_t *)data);
}
References ringbuffer_putchar().
uart_mgmt_async_transmit()
int32_t uart_mgmt_async_transmit (uint8_t dev_id, const uint8_t * data, uint16_t len)
Post an async transmit request to the management queue.
Non-blocking. Returns OS_ERR_OP if the queue is full.
Parameters
dev_id UART device index.
data Pointer to the data buffer (must remain valid until sent).
len Number of bytes.
Definition at line 221 of file uart_mgmt.c.
{
    if (_mgmt_queue == NULL || data == NULL || len == 0)
        return OS_ERR_OP;
    uart_mgmt_msg_t msg = {
        .cmd           = UART_MGMT_CMD_TRANSMIT,
        .dev_id        = dev_id,
        .data          = data,
        .len           = len,
        .result_notify = NULL,
        .result_code   = NULL,
    };
    BaseType_t ok = xQueueSend(_mgmt_queue, &msg, 0);
    return (ok == pdTRUE) ? OS_ERR_NONE : OS_ERR_OP;
}
References _mgmt_queue, uart_mgmt_msg_t::cmd, OS_ERR_NONE, OS_ERR_OP, and UART_MGMT_CMD_TRANSMIT.
uart_mgmt_get_queue()
QueueHandle_t uart_mgmt_get_queue (void)
Return the management queue handle.
Upper layers post uart_mgmt_msg_t items to this queue to request asynchronous UART operations.
Definition at line 216 of file uart_mgmt.c.
{
    return _mgmt_queue;
}
References _mgmt_queue.
uart_mgmt_read_byte()
int32_t uart_mgmt_read_byte (uint8_t dev_id, uint8_t * byte)
Read one byte from the UART RX ring buffer.
Non-blocking. Returns OS_ERR_NONE and stores the byte at *byte when one is available, or OS_ERR_OP when the buffer is empty.
Parameters
dev_id UART device index.
byte Output pointer for the received byte.
Definition at line 239 of file uart_mgmt.c.
{
    if (dev_id >= NO_OF_UART || byte == NULL)
        return OS_ERR_OP;
    struct ringbuffer *rb =
        (struct ringbuffer *)ipc_mqueue_get_handle(
            global_uart_rx_mqueue_list[dev_id]);
    if (rb == NULL)
        return OS_ERR_OP;
    return (ringbuffer_getchar(rb, byte) > 0U) ? OS_ERR_NONE : OS_ERR_OP;
}
References global_uart_rx_mqueue_list, ipc_mqueue_get_handle(), OS_ERR_NONE, OS_ERR_OP, and ringbuffer_getchar().
uart_mgmt_start()
int32_t uart_mgmt_start (void)
Create and start the UART management thread.
Call this once from the OS init sequence, before the FreeRTOS scheduler starts. The thread will perform hardware initialisation after the scheduler starts (after the startup delay defined in os_config.h).
Returns
OS_ERR_NONE on success, negative OS_ERR_* on failure.
Definition at line 202 of file uart_mgmt.c.
{
    _mgmt_queue = xQueueCreate(UART_MGMT_QUEUE_DEPTH, sizeof(uart_mgmt_msg_t));
    if (_mgmt_queue == NULL)
        return OS_ERR_MEM_OF;
    int32_t tid = os_thread_create(uart_mgmt_thread,
                                   "uart_mgmt",
                                   PROC_SERVICE_SERIAL_MGMT_STACK_SIZE,
                                   PROC_SERVICE_SERIAL_MGMT_PRIORITY,
                                   NULL);
    return (tid >= 0) ? OS_ERR_NONE : OS_ERR_OP;
}
References _mgmt_queue, OS_ERR_MEM_OF, OS_ERR_NONE, OS_ERR_OP, os_thread_create(), PROC_SERVICE_SERIAL_MGMT_PRIORITY, PROC_SERVICE_SERIAL_MGMT_STACK_SIZE, UART_MGMT_QUEUE_DEPTH, and uart_mgmt_thread().
uart_mgmt_thread()
static void uart_mgmt_thread (void * arg) static
Definition at line 99 of file uart_mgmt.c.
{
    (void)arg;
    os_thread_delay(TIME_OFFSET_SERIAL_MANAGEMENT);
    /* ── Register and initialise all enabled UART devices ── */
    {
        const drv_uart_hal_ops_t *ops =
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
            hal_uart_stm32_get_ops();
#elif (CONFIG_DEVICE_VARIANT == MCU_VAR_INFINEON)
            hal_uart_infineon_get_ops();
#else
            NULL;
#endif
        if (ops != NULL)
        {
            const board_config_t *bc = board_get_config();
            for (uint8_t i = 0; i < bc->uart_count; i++)
            {
                const board_uart_desc_t *d = &bc->uart_table[i];
                drv_uart_handle_t       *h = drv_uart_get_handle(d->dev_id);
#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)
                hal_uart_stm32_set_config(h, d->instance,
                                          d->word_len, d->stop_bits,
                                          d->parity,   d->mode);
#endif
                int32_t err = drv_uart_register(d->dev_id, ops,
                                                d->baudrate, 10);
                (void)err;
                /*
                 * Subscribe to the generic IRQ notification framework.
                 *
                 * _uart_rx_cb feeds every received byte straight into the
                 * channel's RX ring buffer, which callers drain via
                 * uart_mgmt_read_byte().  The arg pointer is retrieved here
                 * after ipc_queues_init() has already allocated the buffer.
                 */
                struct ringbuffer *rb = (struct ringbuffer *)
                    ipc_mqueue_get_handle(
                        global_uart_rx_mqueue_list[d->dev_id]);
                irq_register(IRQ_ID_UART_RX(d->dev_id),    _uart_rx_cb,  rb);
                irq_register(IRQ_ID_UART_ERROR(d->dev_id),  _uart_err_cb, h);
            }
        }
    }
    /* ── Main event loop ── */
    uart_mgmt_msg_t msg;
    for (;;)
    {
        if (xQueueReceive(_mgmt_queue, &msg, portMAX_DELAY) != pdTRUE)
            continue;
        drv_uart_handle_t *h = drv_uart_get_handle(msg.dev_id);
        if (h == NULL)
            continue;
        int32_t result = OS_ERR_OP;
        switch (msg.cmd)
        {
            case UART_MGMT_CMD_TRANSMIT:
                if (msg.data != NULL && msg.len > 0)
                {
                    result = h->ops->transmit(h, msg.data, msg.len, h->timeout_ms);
                    if (result != OS_ERR_NONE)
                    {
                        h->ops->hw_deinit(h);
                        h->ops->hw_init(h);
                    }
                }
                break;
            case UART_MGMT_CMD_REINIT:
                h->ops->hw_deinit(h);
                result = h->ops->hw_init(h);
                break;
            case UART_MGMT_CMD_DEINIT:
                h->ops->hw_deinit(h);
                result = OS_ERR_NONE;
                break;
            default:
                break;
        }
        if (msg.result_code != NULL)
            *msg.result_code = result;
        if (msg.result_notify != NULL)
            xTaskNotifyGive(msg.result_notify);
    }
}
References _mgmt_queue, _uart_err_cb(), _uart_rx_cb(), uart_mgmt_msg_t::cmd, uart_mgmt_msg_t::data, uart_mgmt_msg_t::dev_id, drv_uart_get_handle(), drv_uart_register(), global_uart_rx_mqueue_list, hal_uart_stm32_get_ops(), hal_uart_stm32_set_config(), drv_uart_hal_ops::hw_deinit, drv_uart_hal_ops::hw_init, ipc_mqueue_get_handle(), irq_register(), uart_mgmt_msg_t::len, drv_uart_handle::ops, OS_ERR_NONE, OS_ERR_OP, os_thread_delay(), uart_mgmt_msg_t::result_code, uart_mgmt_msg_t::result_notify, TIME_OFFSET_SERIAL_MANAGEMENT, drv_uart_handle::timeout_ms, drv_uart_hal_ops::transmit, UART_MGMT_CMD_DEINIT, UART_MGMT_CMD_REINIT, and UART_MGMT_CMD_TRANSMIT.
Variable Documentation
_mgmt_queue
QueueHandle_t _mgmt_queue = NULL static
Definition at line 59 of file uart_mgmt.c.