FreeRTOS-OS: uart_mgmt.h File Reference
uart_mgmt.h File Reference
#include <def_std.h>
#include <def_err.h>
#include <board/mcu_config.h>
#include <config/conf_os.h>
#include <drivers/drv_handle.h>
#include "FreeRTOS.h"
#include "queue.h"
#include "task.h"
Classes
struct uart_mgmt_msg_t
Message posted to the management thread queue.
Macros
#define UART_MGMT_QUEUE_DEPTH 16
Enumerations
enum uart_mgmt_cmd_t { UART_MGMT_CMD_TRANSMIT = 0 , UART_MGMT_CMD_REINIT , UART_MGMT_CMD_DEINIT }
Functions
int32_t uart_mgmt_async_transmit (uint8_t dev_id, const uint8_t *data, uint16_t len)
Post an async transmit request to the management queue.
QueueHandle_t uart_mgmt_get_queue (void)
Return the management queue handle.
int32_t uart_mgmt_read_byte (uint8_t dev_id, uint8_t *byte)
Read one byte from the UART RX ring buffer.
int32_t uart_mgmt_start (void)
Create and start the UART management thread.
Macro Definition Documentation
UART_MGMT_QUEUE_DEPTH
#define UART_MGMT_QUEUE_DEPTH 16
Definition at line 62 of file uart_mgmt.h.
Enumeration Type Documentation
uart_mgmt_cmd_t
enum uart_mgmt_cmd_t
Enumerator
UART_MGMT_CMD_TRANSMIT
Async transmit request
UART_MGMT_CMD_REINIT
Re-initialise peripheral after error
UART_MGMT_CMD_DEINIT
Graceful shutdown of a UART device
Definition at line 36 of file uart_mgmt.h.
             {
    UART_MGMT_CMD_TRANSMIT = 0,  /**< Async transmit request               */
    UART_MGMT_CMD_REINIT,        /**< Re-initialise peripheral after error  */
    UART_MGMT_CMD_DEINIT,        /**< Graceful shutdown of a UART device    */
} uart_mgmt_cmd_t;
Function Documentation
uart_mgmt_async_transmit()
int32_t uart_mgmt_async_transmit (uint8_t dev_id, const uint8_t * data, uint16_t len)
Post an async transmit request to the management queue.
Non-blocking. Returns OS_ERR_OP if the queue is full.
Parameters
dev_id UART device index.
data Pointer to the data buffer (must remain valid until sent).
len Number of bytes.
Definition at line 221 of file uart_mgmt.c.
{
    if (_mgmt_queue == NULL || data == NULL || len == 0)
        return OS_ERR_OP;
    uart_mgmt_msg_t msg = {
        .cmd           = UART_MGMT_CMD_TRANSMIT,
        .dev_id        = dev_id,
        .data          = data,
        .len           = len,
        .result_notify = NULL,
        .result_code   = NULL,
    };
    BaseType_t ok = xQueueSend(_mgmt_queue, &msg, 0);
    return (ok == pdTRUE) ? OS_ERR_NONE : OS_ERR_OP;
}
References _mgmt_queue, uart_mgmt_msg_t::cmd, OS_ERR_NONE, OS_ERR_OP, and UART_MGMT_CMD_TRANSMIT.
uart_mgmt_get_queue()
QueueHandle_t uart_mgmt_get_queue (void)
Return the management queue handle.
Upper layers post uart_mgmt_msg_t items to this queue to request asynchronous UART operations.
Definition at line 216 of file uart_mgmt.c.
{
    return _mgmt_queue;
}
References _mgmt_queue.
uart_mgmt_read_byte()
int32_t uart_mgmt_read_byte (uint8_t dev_id, uint8_t * byte)
Read one byte from the UART RX ring buffer.
Non-blocking. Returns OS_ERR_NONE and stores the byte at *byte when one is available, or OS_ERR_OP when the buffer is empty.
Parameters
dev_id UART device index.
byte Output pointer for the received byte.
Definition at line 239 of file uart_mgmt.c.
{
    if (dev_id >= NO_OF_UART || byte == NULL)
        return OS_ERR_OP;
    struct ringbuffer *rb =
        (struct ringbuffer *)ipc_mqueue_get_handle(
            global_uart_rx_mqueue_list[dev_id]);
    if (rb == NULL)
        return OS_ERR_OP;
    return (ringbuffer_getchar(rb, byte) > 0U) ? OS_ERR_NONE : OS_ERR_OP;
}
References global_uart_rx_mqueue_list, ipc_mqueue_get_handle(), OS_ERR_NONE, OS_ERR_OP, and ringbuffer_getchar().
uart_mgmt_start()
int32_t uart_mgmt_start (void)
Create and start the UART management thread.
Call this once from the OS init sequence, before the FreeRTOS scheduler starts. The thread will perform hardware initialisation after the scheduler starts (after the startup delay defined in os_config.h).
Returns
OS_ERR_NONE on success, negative OS_ERR_* on failure.
Definition at line 202 of file uart_mgmt.c.
{
    _mgmt_queue = xQueueCreate(UART_MGMT_QUEUE_DEPTH, sizeof(uart_mgmt_msg_t));
    if (_mgmt_queue == NULL)
        return OS_ERR_MEM_OF;
    int32_t tid = os_thread_create(uart_mgmt_thread,
                                   "uart_mgmt",
                                   PROC_SERVICE_SERIAL_MGMT_STACK_SIZE,
                                   PROC_SERVICE_SERIAL_MGMT_PRIORITY,
                                   NULL);
    return (tid >= 0) ? OS_ERR_NONE : OS_ERR_OP;
}
References _mgmt_queue, OS_ERR_MEM_OF, OS_ERR_NONE, OS_ERR_OP, os_thread_create(), PROC_SERVICE_SERIAL_MGMT_PRIORITY, PROC_SERVICE_SERIAL_MGMT_STACK_SIZE, UART_MGMT_QUEUE_DEPTH, and uart_mgmt_thread().