FreeRTOS-OS: uart_app.h File Reference
uart_app.h File Reference
#include <def_std.h>
#include <def_err.h>
Functions
int32_t uart_async_read_byte (uint8_t dev_id, uint8_t *byte)
Read one byte from the RX ring buffer without blocking.
int32_t uart_async_transmit (uint8_t dev_id, const uint8_t *data, uint16_t len)
Post a transmit request and return immediately.
int32_t uart_sync_receive (uint8_t dev_id, uint8_t *buf, uint16_t len, uint32_t timeout_ms)
Receive exactly len bytes from the UART RX ring buffer, blocking until all bytes arrive or timeout expires.
int32_t uart_sync_transmit (uint8_t dev_id, const uint8_t *data, uint16_t len, uint32_t timeout_ms)
Transmit data over UART and block until the transfer completes.
Function Documentation
uart_async_read_byte()
int32_t uart_async_read_byte (uint8_t dev_id, uint8_t * byte)
Read one byte from the RX ring buffer without blocking.
Parameters
byte Output: the received byte (valid only when returning OS_ERR_NONE).
Returns
OS_ERR_NONE if a byte was available, OS_ERR_OP if buffer empty.
Definition at line 75 of file uart_app.c.
{
    return uart_mgmt_read_byte(dev_id, byte);
}
References uart_mgmt_read_byte().
uart_async_transmit()
int32_t uart_async_transmit (uint8_t dev_id, const uint8_t * data, uint16_t len)
Post a transmit request and return immediately.
The data buffer must remain valid until the management thread drains the queue (use a static or long-lived buffer).
Returns
OS_ERR_NONE if queued, OS_ERR_OP if queue is full.
Definition at line 70 of file uart_app.c.
{
    return uart_mgmt_async_transmit(dev_id, data, len);
}
References uart_mgmt_async_transmit().
uart_sync_receive()
int32_t uart_sync_receive (uint8_t dev_id, uint8_t * buf, uint16_t len, uint32_t timeout_ms)
Receive exactly len bytes from the UART RX ring buffer, blocking until all bytes arrive or timeout expires.
Polls the RX ring buffer in 1 ms ticks. Suitable for low-to-medium baud rates where byte arrival is reliably within the OS tick period.
Parameters
dev_id UART device index.
buf Buffer to store received bytes.
len Number of bytes to receive.
timeout_ms Maximum total wait time.
Returns
OS_ERR_NONE if all bytes received, OS_ERR_OP on timeout.
Definition at line 41 of file uart_app.c.
{
    if (buf == NULL || len == 0)
        return OS_ERR_OP;
    uint32_t elapsed = 0;
    uint16_t received = 0;
    while (received < len)
    {
        if (uart_mgmt_read_byte(dev_id, &buf[received]) == OS_ERR_NONE)
        {
            received++;
        }
        else
        {
            if (elapsed >= timeout_ms)
                return OS_ERR_OP;
            os_thread_delay(1);
            elapsed++;
        }
    }
    return OS_ERR_NONE;
}
References OS_ERR_NONE, OS_ERR_OP, os_thread_delay(), and uart_mgmt_read_byte().
uart_sync_transmit()
int32_t uart_sync_transmit (uint8_t dev_id, const uint8_t * data, uint16_t len, uint32_t timeout_ms)
Transmit data over UART and block until the transfer completes.
Posts a transmit request to the UART management queue and waits for the management thread to notify completion via task notification.
Parameters
dev_id UART device index (from board_device_ids.h).
data Pointer to the data buffer.
len Number of bytes to transmit.
timeout_ms Maximum time to wait for queue + completion.
Returns
OS_ERR_NONE on success, OS_ERR_OP on failure or timeout.
Definition at line 16 of file uart_app.c.
{
    QueueHandle_t q = uart_mgmt_get_queue();
    if (q == NULL || data == NULL || len == 0)
        return OS_ERR_OP;
    int32_t result = OS_ERR_OP;
    uart_mgmt_msg_t msg = {
        .cmd           = UART_MGMT_CMD_TRANSMIT,
        .dev_id        = dev_id,
        .data          = data,
        .len           = len,
        .result_notify = xTaskGetCurrentTaskHandle(),
        .result_code   = &result,
    };
    if (xQueueSend(q, &msg, pdMS_TO_TICKS(timeout_ms)) != pdTRUE)
        return OS_ERR_OP;
    ulTaskNotifyTake(pdTRUE, pdMS_TO_TICKS(timeout_ms));
    return result;
}
References uart_mgmt_msg_t::cmd, OS_ERR_OP, UART_MGMT_CMD_TRANSMIT, and uart_mgmt_get_queue().